rust-lang/mdBook

- Cargo.toml
- src/main.rs
If you're interested I used [clap](https://github.com/kbknapp/clap-rs) to greatly simplify your CLI. It still has all the same functionality as the original, but far less manual code. It also has some additional functionality "for free" since it's included by default with `clap`
Things like suggestions, where if a user mistakenly types `$ mdbook buld` (note the missing `i` in `build`), this error would appear and exit gracefully:
```
$ mdbook buld
error: The subcommand 'buld' isn't valid
Did you mean 'build' ?
If you received this message in error, try re-running with 'mdbook -- buld'
USAGE:
mdbook [FLAGS] <SUBCOMMAND>
For more information try --help
```
There are also things like colored output automatically on linux/osx (Windows works the same, only without color). This color can be …
> uses clap to simplify CLI

- src/book/bookconfig.rs
- src/book/bookitem.rs
- src/book/mdbook.rs
- src/parse/summary.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/utils/mod.rs
Mostly I took whatever suggestions I found because the result seemed good.
I thought dereferencing a match would result in a move so I wasn't sure about:
```rust
// This
match *a {
A::B => {},
A::C => {},
}
// Instead of
match a {
&A::B => {},
&A::C => {},
}
```
But I tried it and didn't get any errors. I'll have to experiment with it in the future sometime later.
> Fix many minor warnings found by clippy

- Cargo.toml
Removes the `*` so this can be installed via `cargo install mdbook`
Also, I locked the `handlebars` dep to `0.11.2` because the current `0.11.3` fails to build.
> adds version for deps to make cargo installable

- src/theme/book.css
- src/theme/highlight.css
- src/theme/stylus/themes/base.styl
As far as I can tell, the top two blocks in `highlight.css` are added/tweaked from the original (included in hightlight.js) while the remaining part of the original css file basically remains identical. The problem is the `:not(pre) > .hljs` isn't included for dark themes which causes issues like https://github.com/azerupi/mdBook/issues/74.
If possible, I'd move away from modified themes so they can just be updated to the latest version of whatever highlight.js is using. I tried backing out the theme tweak but reverted it because the code backgrounds were a weird yellow.
Fixes #74
> Generalize inline code to all themes

- src/theme/book.js
This bit of js resolves #21 by scrolling the sidebar to the link for the currently-active chapter.
First time contributing to this project, so please excuse anything unexpected. There is some formatting inconsistency in the surrounding js about spaces and quotation marks and whatnot, but I tried to write code that fit in. Please let me know if there's anything that could be improved!
> On page load, scroll sidebar to active section. Resolves #21.

- src/renderer/html_handlebars/hbs_renderer.rs
This is an inelegant fix for #76. I read about better ways to do this using `intersperse` and `join` but couldn't make the types work out. Happy for someone else to show me a better way.
> Add newlines back in to generated index.html files.

- src/theme/book.css
- src/theme/book.js
- src/theme/stylus/themes/base.styl
This is one way to address #72, creating anchors for sections in the text.
- Just uses the header's text as its anchor name. Spaces in the names work fine in URLs. In the browsers I tested, scrolling to the anchor in the URL works even when the anchor is added after the DOM loads.
- Adjust theme css to only style links, not <a> tags used as anchors.
> Add anchors around all headers in the content.

- book-example/src/SUMMARY.md
- book-example/src/cli/build.md
- book-example/src/cli/cli-tool.md
- book-example/src/cli/init.md
- book-example/src/cli/test.md
- book-example/src/cli/watch.md
- book-example/src/lib/lib.md
Part of https://github.com/azerupi/mdBook/issues/80
Feel free to not take the second commit; I don't know if you want to bother testing the book, but figured I'd give it a shot :)
> mdbook test documentation

- src/theme/book.js
- src/theme/index.hbs
Add navigation to next and previous pages by 'alt + &rarr;' and 'alt + &larr;' combinations. Issue #81 with modification (add alt key)
> Add navigation by keyboard using alt + left/right arrows

- README.md
Replace two contractions with possessive pronouns: it's => its.
> Fix "it's" typos in README.md

- Cargo.toml
Pulldown-mark with fixed table support: #102 and [google/pulldown-cmark#16](https://github.com/google/pulldown-cmark#16)
> pulldown-mark version bump

- book-example/book.json
- book-example/src/format/config.md
- src/book/bookconfig.rs
- src/book/mdbook.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
There seems to be a bug in the index.hbs template.
```
<meta name="description" content="{% block description %}{% endblock %}">
```
I fixed this, adding a `"description": "..."` option to `book.json`.
> Add description config option

- src/bin/mdbook.rs
- src/book/mdbook.rs
- src/lib.rs
Handles: https://github.com/azerupi/mdBook/issues/110
Generates a simple `.gitignore` file inside the book's destination folder with the following contents:
```
*
!.gitignore
```
It is intended to instruct git to ignore the auto-generated destination folder's contents.
> Generate simple .gitignore on init

- src/bin/mdbook.rs
- src/book/mdbook.rs
Continuation of https://github.com/azerupi/mdBook/pull/111 after [realising a bug in the logic of the implementation](https://github.com/azerupi/mdBook/pull/111#issuecomment-191642716).
---
Generates a `.gitignore` file directly under the `root` folder instead of under the `dest` folder.
Makes use of the newly stabilised ([as of 1.7.0](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-170-2016-03-03) :smile:) [Path.strip_prefix](http://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.strip_prefix) method.
> Move `.gitignore` directly under the root folder

- .travis.yml
- ci/before_deploy.sh
- ci/install.sh
- ci/script.sh
- deploy.sh
This one is more complex. I hope I got it right on the first try. *crosses fingers*
> Travis CI: expand to test and deploy for Linux and Mac

- src/bin/mdbook.rs
This also fixes
Error while building: Error { repr: Os { code: 2, message: "No such file or directory" } }
as that was caused by several file events happening directly after each other (e.g. swap file created by editor) and trying to clean the target directory simultaneously.
> Fix watch event cooldown

- src/theme/index.hbs
Chrome and Firefox will not allow `http` content to be loaded when the site is accessed from `https`. This PR just moves the font, bootstrap, and jQuery to `https`. All the links support `https` and I have tested them.
> Fix for insecure content on HTTPS enabled sites

- .travis.yml
- ci/before_deploy.sh
- ci/install.sh
- ci/script.sh
this ensures we install the correct set of standard crates when working
in the beta channel
> travis: use rustup instead of Travis built-in Rust support

- src/bin/mdbook.rs
- src/book/mod.rs
I believe it's currently not possible to do leave out the livereload field as it's used in other parts of the code where we can't utilize conditional compilation without ugly hacks.
Fixes: #136 
related: https://github.com/rust-lang/rust/issues/15701
> Fix no-default-features build

- src/theme/book.css
Before (only one page; content is cut off):
After:
> Add print media query

- src/bin/mdbook.rs
Fix issue azerupi/mdBook#133 by adding a link to the source code at the end of the `--help` output.
Before:
```
[...]
For more information about a specific command, try `mdbook <command> --help`
```
After:
```
[...]
For more information about a specific command, try `mdbook <command> --help`
Source code for mdbook available at: https://github.com/azerupi/mdBook
```
> Fix azerupi/mdBook#133: Add link to source code

- src/theme/index.hbs
mdBook is setting theme (by adding a class attribute to body tag) with javascript.
Page is not using any theme by default and page is not using any styling unless
javascript is enabled.
This patch is adding class attribute to body tag and making mdBook to use `light`
theme when javascript is disabled.
Fixes: #144
> Use light theme when javascript is disabled

- src/renderer/html_handlebars/helpers/toc.rs
I was seeing missing closing tags in the TOC and had a go at fixing the issue. Every `<ul>` should now have a closing `</ul>`
> Make sure <ul><li> and </li></ul> are balanced

- src/theme/book.js
also fixes https://github.com/rust-lang/book/issues/166 anchors duplication
Thanks @azerupi for mentoring in #156 !
Cheers!
Note: `split("#")[0]` does return the full url if there are no `#` (anchor) to strip out - just making sure that case was handled :)
> Fixes #156 - anchors are now URI encoded

- book-example/src/SUMMARY.md
- book-example/src/cli/serve.md
- src/bin/mdbook.rs
Made the following changes:
* Added option to specify interface for http and websocket server to listen on. `-i` flag.
* Added option to specify host for browser to connect to websocket server from. `-a` flag
* Added page to the `book-example` for serve command.
Let me know if anything is missing or needs to be done!
Cheers,
code-ape
> Added option to configure serve interface and public websocket address.

- book-example/src/format/mathjax.md
- book-example/src/format/rust.md
- book-example/src/format/theme/syntax-highlighting.md
These changes will make book-example pass `mdbook test` again :)
> Fix book-example tests

- src/bin/mdbook.rs
A branch of the book had [a code example that failed with `mdbook test`, but travis reported a success](https://travis-ci.org/rust-lang/book/jobs/149313558). This is because the exit status of `mdbook test` (and other commands) is still 0 even when there are errors.
I [made a little repo](https://github.com/carols10cents/mdbook-test-exit-status) that has an example to test with, but the book-example in this repo also currently has an error with `mdbook test` 😱
Before this patch, if I run `mdbook test` on those, I get an exit status of 0 when I expect to get nonzero. After this patch, I get the nonzero exit status that I expected (I went with 101 because that's what `rustdoc --test` returns if it fails), and I continue to get an exit status of 0 when running `mdbook test` on a book that …
> Exit with a nonzero status if we get an error

- src/theme/book.css
- src/theme/stylus/sidebar.styl
> Make line-height for chapter greater than section

- src/utils/fs.rs
I needed this feature recently (e.g. to have a README file copied automatically), so here's a patch, if it is useful to someone.
> Copy files with no extension

- src/theme/book.js
The current section headers are url encoded.  Because of that they
have some funny characters like %20.  We can clean that up by removing
all of the non-word characters before placing them in the anchor.
I originally planned to use `/\s/g` as the regex to preserve other url encoded characters like ‰ or ¥ that might be useful, but I double checked what Github does on gists and it looks like they strip everything.
hi ‰ there
becomes #hi--there in the url.
mdbook urls will now match that style.
fixes #168
> slugify section headers

- src/utils/fs.rs
PR removes warning:
```rust
warning: unused import, #[warn(unused_imports)] on by default
--> src/utils/fs.rs:4:21
|
4 | use std::fs::{self, metadata, File};
|                     ^^^^^^^^
```
It's really unused.
> Remove unused metadata import

- Cargo.toml
- src/book/bookconfig.rs
- src/book/bookitem.rs
- src/lib.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
This PR switches from rustc-serialize to serde. We actually don't even need codegen from serde. Only the `Chapter` struct had to implement `Serialize` but that was trivial to do.
> Switch from rustc_serialize to serde

- src/theme/book.js
Fixes #179.
Highlight.js does not apply syntax highlighting to code blocks marked
no-highlight, nohighlight, plain, or text. When it finds blocks of those
languages, it does not add the `hljs` class to those code blocks either.
highlight.css and tomorrow-night.css use the `hljs` class to give code
blocks their backrgound color and text color, and we want that to apply
even if the code doesn't get syntax highlighting markup.
This is a somewhat hacky solution to get just that behavior! After this
commit, code blocks with no-highlight, nohighlight, plain, or text
language set on them will indeed get the hljs colors.
> Add hljs class to all code blocks, regardless of highlighting

- book-example/src/format/config.md
- src/book/bookconfig.rs
- src/book/mod.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/mod.rs
This allows the `src` and `theme_path` keys in book.json to set source and theme directories.
> Book json keys

- Cargo.toml
- book-example/book.json
- book-example/book.toml
- book-example/src/SUMMARY.md
- book-example/src/cli/test.md
- book-example/src/format/config.md
- book-example/src/format/format.md
- book-example/src/format/theme/index-hbs.md
- book-example/src/format/theme/syntax-highlighting.md
- book-example/src/lib/lib.md
- book-example/src/misc/introduction.md
- src/book/bookconfig.rs
- src/book/bookconfig_test.rs
- src/book/mod.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
Some work towards #96. It parses the same config as either from `book.toml` or `book.json`.
This can be merged without concern for the larger refactoring.
> Parse toml

- book-example/src/cli/init.md
This fixes a broken link on http://azerupi.github.io/mdBook/cli/init.html
The `..` is redundant because the document's base URI is set to
`path_to_root`.  It breaks if the base URI is not at the server root.
> Fix a broken link in the documentation

- book-example/src/cli/build.md
- book-example/src/cli/serve.md
- book-example/src/cli/watch.md
Forgot to do this at the time. Sorry!
> Add docs for --dest-dir option

- src/theme/book.css
Wider hit regions are easier to pick with mouse.
> widen hit regions of menu buttons

- Cargo.toml
- src/lib.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
> Generate links at compile-time rather than use JS

- src/renderer/html_handlebars/hbs_renderer.rs
This got left out of https://github.com/azerupi/mdBook/pull/207
It'd be nice if we could get a point release with this in it for https://github.com/rust-lang/rust/pull/39976
This should be the last change like this 😄
> Print version: fix up header links

- src/renderer/html_handlebars/hbs_renderer.rs
Fixes #155 
This PR iterates over all code blocks and replace all commas in the class attribute by spaces. This allows to specify multiple classes in code blocks. This is mostly for the Rust book that uses:
```rust,should_panic
fn main() {
// Code here
}
```
@steveklabnik Is this better than #213 ?
> Fix code blocks with comma separated classes

- src/renderer/html_handlebars/hbs_renderer.rs
This should fix #211 
\cc @steveklabnik 
You can merge this, unless you have a cleaner way to solve this :)
> Fix anchors #211

- src/renderer/html_handlebars/hbs_renderer.rs
Fixes #29 
So, this all works, and fixes an important regression in mdbook for the rust book.
However.
The big issue remaining is the "wrap in `main`" rules from rustdoc. In other words, something like this:
```rust
let x = 5;
```
will fail, as it needs to be inside of `main`.
I'm not sure what the right way is to go here, exactly. I'm imagining duplicating the logic of rustdoc here makes sense.
Thoughts @azerupi @carols10cents @frewsxcv ?
> Implement playpen support for ```rust

- src/renderer/html_handlebars/hbs_renderer.rs
Header fragment links now use "id" attribute instead of the depreciated "name" attribute.
Similar headers are given numbered ids to avoid id collisions.
For instance, if there are three headers named "Example", their ids would be "example", "example-1", and "example-2" respectively.
Fixes #219 and #220.
> Fix header links

- .gitattributes
This should prevent stuff like https://github.com/azerupi/mdBook/issues/234 even for people who don't have git configured properly.
> add a .gitattributes to ensure proper line ending settings

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
This also brings us to parity with rustdoc regarding attributes in
general; while this PR was focused on enabling nightly, that was a
happy accident.
Fixes #241 
Check it out:
This is after clicking "run" on each. Top goes to stable, bottom to nightly.
> Accept nightly examples.

- src/theme/book.css
- src/theme/index.hbs
- src/theme/stylus/general.styl
Even Github seams to not be capable of properly showing curses-style box-drawing characters:
```
╭────────────────────╮
╭→│ boxes are awesome! ├─╮
│ ╰────────────────────╯ │
╰────────────────────────╯
```
With this PR mdBook would be (`$ cargo doc` does support them, too!).
> Added monospace font with support for box-drawing chars

- src/renderer/html_handlebars/helpers/playpen.rs
The playpen helper now uses a simple pre block instead of a pre block
with class playpen as it led to nested playpens.
Fixes #251.
> Remove the extra run button on runnable rust files

- src/bin/mdbook.rs
- src/book/mod.rs
Fixes https://github.com/azerupi/mdBook/issues/253.
> Implement new 'no-create' build flag.

- src/theme/index.hbs
Because the [MathJax CDN will soon be retired](https://www.mathjax.org/cdn-shutting-down/).
> Change MathJax to use CDNJS

- src/book/bookconfig.rs
- src/book/bookconfig_test.rs
- src/book/mod.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
I've added support for including google analytics in your rendered book. You simply need to add the `google_analytics_id` key to your `book.toml` and that should be enough to tell `mdbook` to insert the usual snippet at the bottom of each page.
(fixes #268)
> Support for Google Analytics

- book-example/src/format/config.md
When making #272 I forgot to add a bit explaining the config key in the accompanying documentation.
> Added a note about google analytics to the docs

- src/renderer/html_handlebars/hbs_renderer.rs
Code snippets using quick_main! macro from error-chain
https://docs.rs/error-chain/0.10.0/error_chain/macro.quick_main.html
no longer have `fn main` implicitly added
resolves https://github.com/azerupi/mdBook/issues/282
> Do not add playpen boilerplate when using quick_main!

- src/theme/book.js
Hidden code blocks are no longer indented with
one additional space (required for doctests to compile in some cases)
Now the behavior is similar to the rustdoc's
Please note that I have zero experience with js so I am really open to criticism here ;)
resolves https://github.com/azerupi/mdBook/issues/281
> Fix indentation of hidden code blocks

- src/theme/book.css
- src/theme/stylus/themes/base.styl
Inline code with hyperlink has now the same color and on hover underline as standard hyperlink.
This is how it looks in rust-cookbook
Please note that I have zero experience with css / webdev so I am really open to criticism.
solves: https://github.com/azerupi/mdBook/issues/261
> Inline code with hyperlink is now highlighted

- Cargo.toml
- build.rs
`cargo build --features=regenerate-css` should now have nicer errors and work on windows
It is written mostly to solve: https://github.com/azerupi/mdBook/issues/293
but also fixes: https://github.com/azerupi/mdBook/issues/294
Please note that I have very little Rust experience so I would be very glad for critical review. 
Build.rs has become quite wordy and error-chain was added as build-dependency which is quite hevyweight for what the script does.
> Friendlier errors from build.rs and support for Windows stylus build

- src/theme/book.css
- src/theme/stylus/general.styl
List of system fonts (R, I, B means roman, italic and bold. Ubuntu probably comes with more fonts, but I couldn't find a list to confirm.):
```txt
Windows
----------
Consolas            R RI  B BI
Courier             R
Courier New         R RI  B BI
Lucida Console      R
Mac
----------
Andale Mono         R
Courier             R RI  B BI
Courier New         R RI  B BI
Menlo               R RI  B BI
Monaco              R
Ubuntu
----------
Ubuntu Mono         R RI  B BI
DejaVu Sans Mono    R RI  B BI
```
```css
font-family: Consolas, "Ubuntu Mono", Menlo, "DejaVu Sans Mono", monospace, monospace;
```
Consolas and Ubuntu are professionally designed fonts ([Lucas de Groot][1] and [Dalton Maag][2]), with true, calligraphic italic, so they go at the top of the stack.
Menlo is [based on DejaVu …
> CSS: better fallback stack for monospaced fonts

- src/bin/mdbook.rs
Websocket port option does not work since mdbook.rs use --websocket-port in arguments and use ws-port in implementation.
> Fix websocket port option for serve

- src/bin/mdbook.rs
Now we have: `Serving on: http://localhost:3000`
I am aware of the `-o` option but it has been raised as desirable to be able to just copy and paste the address from terminal.
fixes: https://github.com/azerupi/mdBook/issues/299
> Reformatted "Serving on " message for easier consumption

- book-example/src/format/theme/theme.md
- src/bin/mdbook.rs
As `theme` dir is no longer under `src`. Updates to "theme" did not
trigger book rebuild.
Also fixed misleading docs about `theme` dir being located in `src`
fixes https://github.com/azerupi/mdBook/issues/306
> Now changes to `theme` directory trigger rebuild for `mdbook serve`

- src/theme/book.js
Currently book.js contains pure ES5 code, so it is not a big deal to backport just two lines to make old browsers happy.
Thanks!
> Fix ES5 compatibility.

- src/theme/book.js
Yet another fix for missing [String.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes). Actually, there is a polyfill for it, but since it is just one place - it is easier to use `indexOf` here.
Sorry for two PRs, I didn't expect previous to be merged so fast :)
> One more ES5 fix.

- src/theme/book.js
Hide sidebar on sidebar link link selection when sidebar occupies large space in relation to the whole screen width (solves problems on phones)
Calculates if sidebar width is large (> 0.4 * screen width) and if yes closes the sidebar.
This intentionally leaves the old behavior on tablets or in landscape mode if there  is enough space on screen.
Originally wanted to use css in conjunction with js but ended up with js only solution.
fixes https://github.com/azerupi/mdBook/issues/125
fixes https://github.com/azerupi/mdBook/issues/318
> Hide sidebar on link selection when it occupies large space

- src/book/mod.rs
- src/config/htmlconfig.rs
- src/config/tomlconfig.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
- tests/tomlconfig.rs
I might need some refactoring but it is functionally on par with "custom css" functionality. 
fixes https://github.com/azerupi/mdBook/issues/311
> Implemented support for additional JS

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/ayu-highlight.css
- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/mod.rs
- src/theme/stylus/themes/ayu.styl
- src/theme/stylus/themes/base.styl
- src/theme/stylus/themes/coal.styl
- src/theme/stylus/themes/index.styl
- src/theme/stylus/themes/light.styl
- src/theme/stylus/themes/rust.styl
Closes #223.
I finally got this done! Here is a comparison between the new theme (left) and the Navy theme (right):
The only modification I had to make to mdBook itself (beyond the addition of the theme throughout the codebase, of course) was to introduce a variable so that I could change inline code's text color. If you don't want this it can certainly be removed (although I feel that it makes the theme more readable).
And finally, to be clear: if you don't feel like mdBook should ship with this theme, feel free to say so. I'm not trying to force it on anyone :)
> Add `Ayu` theme

- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/stylus/page.styl
fixing problems with keyboard navigation
fixes https://github.com/azerupi/mdBook/issues/235
I also have a variant that selects the right pane whenever sidebar gains focus which is nice as the keyboard navigation always works even if someone misclicks on sidebar not hitting a link. But then keyboard navigation on sidebar itself stops being possible. So I've decided to just post this minimal version as it causes no regressions.
> Select right pane content on page load

- src/theme/index.hbs
mdBook is a mostly pleasant experience in emacs' 'eww' browser (and probably other non-JS browsers). Next and prev links make it a bit more seemless.
> Relative links for non-JS browsers

- src/renderer/html_handlebars/helpers/playpen.rs
Potential code for #345 for reference. Adding `editable` passthrough while we're at it.
Doing something like may have unintended consequences, of course.
> Creating markdown code from playpen files instead of HTML #345

- book-example/src/format/config.md
- src/bin/mdbook.rs
- src/book/mod.rs
- src/config/bookconfig.rs
- src/config/htmlconfig.rs
- src/config/jsonconfig.rs
- src/config/tomlconfig.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/utils/mod.rs
- tests/jsonconfig.rs
- tests/tomlconfig.rs
This updates `render_markdown` in `utils/mod.rs` to convert all straight quotes to curly quotes,
except for those that occur in code blocks and code spans.
This was motivated by my search for the best way to fix [inconsistent curly quotes in the Rust book](https://github.com/rust-lang/book/issues/363), and it seemed like enhancing mdbook might be the cleanest way to do it. Let me know what you think!
> Convert to curly quotes when rendering markdown

- src/theme/book.css
- src/theme/stylus/general.styl
- src/theme/stylus/nav-icons.styl
- src/theme/stylus/page.styl
- src/theme/stylus/sidebar.styl
- src/theme/stylus/variables.styl
Hello! This fixes the iOS scroll-to-top bug mentioned in issue #185.
Notes:
* Scroll-to-top is a built-in function of iOS Safari that didn't work because the
page content was inside absolutely-positioned, scrollable divs.
* The fix is to stop using absolute positioning on `.page-wrapper` and
`.page`, so that the content uses static positioning and flows
naturally down the page.
* Consequently, `.sidebar` and `.nav-chapter` now have to use `position:
fixed` in order to be positioned relative to the viewport.
* This fix also enables Safari's built-in behavior of automatically
hiding the top and bottom toolbars when scrolling down the page.
> On iOS, allow scrolling to the top of the page by tapping the top of the screen

- book-example/src/lib/lib.md
- src/bin/mdbook.rs
- src/book/mod.rs
- src/lib.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/playpen.rs
- src/utils/fs.rs
- tests/config.rs
- removing need to explicitly use `Path::new` all over the place
- removed warnings from doctests (normally invisible unless `cargo test -- --nocapture`)
- no doctests are norun/ignore now
- updated docs both in book-example and in docs not to refer to nonexisting API's
This is mostly due to my fear of introducing any regressions / warnings to the code when I try to contribute something.
> Minor cleanup

- src/bin/mdbook.rs
First commit does the actual work if implementing iron AfterMiddleware which transforms all errors into simple 404 response which quiets iron's logging.
The second is a minimal refactor moving all `serve` related imports into a separate module (all the changes are indentation and moved imports.) I am willing to drop the second commit.
fixes: https://github.com/azerupi/mdBook/issues/183
fixes: https://github.com/azerupi/mdBook/issues/233
Also I see that `serve` and `watch` command line args are added to clap unconditionally even if features are disabled. Do you mind If I fix this too?
> error spewing on iron 404 errors

- src/book/mod.rs
- src/config/htmlconfig.rs
- src/theme/mod.rs
- tests/jsonconfig.rs
- tests/tomlconfig.rs
if one is not specified in book.toml
fixes https://github.com/azerupi/mdBook/issues/313
> Fixes missing the default "theme" dir location

- src/renderer/html_handlebars/hbs_renderer.rs
In my "plugins" branch I'm wanting to experiment with different ways of doing plugins (for pre-processing, post-processing, different backends, etc) and in the process I needed to refactor the `HTMLHandlebars` renderer a little bit. If you reckon they'll be useful, feel free to merge the changes into master :)
All I did was pull bits and pieces of the `HTMLHandlebars::render()` method out into their own helper functions so it's easier to wrap your head around.
> Refactor hbs renderer

- src/book/mod.rs
- src/config/htmlconfig.rs
- src/config/tomlconfig.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
- tests/config.rs
- tests/tomlconfig.rs
to enable add following to book.toml
```toml
[output.html]
mathjax-support = true
```
fixes https://github.com/azerupi/mdBook/issues/347
> Make MathJax support optional

- src/bin/mdbook.rs
- src/book/mod.rs
- src/config/jsonconfig.rs
- src/config/tomlconfig.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/playpen.rs
- src/renderer/html_handlebars/helpers/toc.rs
- tests/jsonconfig.rs
- tests/tomlconfig.rs
I've run clippy over the code and corrected all of its warnings.
Transition from [`ok_or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or) to [`ok_or_else`](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or_else) might be non obvious but the first one calls the "or" branch unconditionally (suggested only if Err value is already available) while the second one evaluates it lazily.
> Correct clippy complaints

- src/bin/build.rs
- src/bin/init.rs
- src/bin/serve.rs
- src/bin/watch.rs
- src/book/mod.rs
- src/config/bookconfig.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/mod.rs
- tests/config.rs
- tests/jsonconfig.rs
- tests/tomlconfig.rs
`HtmlConfig` was both guaranteed to exist within `BookConfig`
and `expect`ed in few places.
This simplifies the API a little by representing the fact that
`HtmlConfig` is curently mandatory for proper mdbook binary operation.
Please feel free to drop this PR if it does not match the project vision (it did not take a lot of effort anyway ;) ).
> Make HtmlConfig is no longer optional

- src/lib.rs
See https://github.com/azerupi/mdBook/pull/361#discussion_r124440165
Before:
```
[*]: Testing file: "/Users/messense/Projects/PyO3/guide/src/./conversions.md"
An error occured:
A subprocess failed
```
After:
```
[*]: Testing file: "/Users/messense/Projects/PyO3/guide/src/./conversions.md"
An error occured:
Rustdoc returned an error:
running 2 tests
test /Users/messense/Projects/PyO3/guide/src/./conversions.md - Type_Conversions (line 15) ... FAILED
test /Users/messense/Projects/PyO3/guide/src/./conversions.md - Type_Conversions (line 15) ... FAILED
failures:
---- /Users/messense/Projects/PyO3/guide/src/./conversions.md - Type_Conversions (line 15) stdout ----
error[E0463]: can't find crate for `pyo3`
--> <anon>:1:1
|
1 | extern crate pyo3;
| ^^^^^^^^^^^^^^^^^^ can't find crate
error: …
```
> Print stdout when `mdbook test` failed

- appveyor.yml
It looks like the "stable" release from static.rust-lang.org is stale, so appveyor is using 1.16 as the "stable" channel. This breaks a couple dependencies because they rely on features which were stabilised in 1.17 (struct field shorthands).
I've updated the `appveyor.yml` to install Rust using rustup.
This was originally encountered in #371 but has been extracted into its own PR so it can be merged immediately.
> Updated appveyor.yml to use rustup for installing Rust

- src/bin/mdbook.rs
Sets the `INFO` as the default logging level shown to stdout unless `RUST_LOG` env var is set.
fixes https://github.com/azerupi/mdBook/issues/358
TLNR:
---
- we can merge this PR (no colors and verbose output)
- if we can live with colored output working only on unix'y systems then adding it will take ~10lines with ansi_term
- if we want colors but can live without support for RUST_LOG we can use [simplelog](https://github.com/drakulix/simplelog.rs)
- we might leave the logging as is and add "cargo like" split logging based on [termcolor](https://github.com/BurntSushi/ripgrep/tree/master/termcolor) or [term](https://github.com/Stebalien/term) for the mdBook binary commands and error output) 
Discussion:
---
I'm not really happy with the effects of this PR. The output starts to be overly …
> Increased default logging level to info unless RUST_LOG is set

- src/bin/test.rs
- src/book/mod.rs
Add `-L`/`--library-path` argument and pass it into `rustdoc` should be sufficient.
Closes #339
> Add library path argument for `mdbook test`

- ci/install.sh
travis started to fail for beta channel.
This is most likely due to old version on rustup on travis-ci
> fix travis ci for beta channel

- README.md
This should be the last piece to close #327 and crosses one of the items of #368
> Add a note about version pinning in the README

- src/renderer/html_handlebars/hbs_renderer.rs
Since b7aa78c3c0c739b8166b6e21927ae522ade80f7b, the file name `print.html` was hard coded into `HtmlHandlebars.post_process`, hence anchors in chapters were all in the form `http://web site/print.html#paragraph title`
This PR fixes it
> Fixed wrong filename when post processing html

- src/theme/book.js
also add 15s communication timeout
fixes https://github.com/azerupi/mdBook/issues/392
> handle play.rust-lang.org communication errors in playpens

- Cargo.toml
- src/book/mod.rs
- src/lib.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- now `mdbook test` does full link expansion to temp file prior to running
- also *very* minor reformat and cleanup of `HtmlHandlebars::render_item`
fixes https://github.com/azerupi/mdBook/issues/391
IMHO the render_item should have a major overhaul. It might be good to start pulling some more of @Michael-F-Bryan 's book representation refactors.
> Fixed `mdbook test` for {{#playpen file.rs}}

- src/utils/mod.rs
fixes https://github.com/azerupi/mdBook/issues/397
> fixed missing playpen css class when codeblock properties had whitespace

- book-example/book.toml
- book-example/src/README.md
- book-example/src/format/config.md
- book-example/src/format/mathjax.md
This PR updates some of the documentation for the 0.1.0 release.
This currently includes updates to 
- MathJax 
- `additional-js`.
#368
> Update documentation for 0.1.0

- Cargo.toml
The toml crate removed its serde dependency in 0.3, but in 0.4, it
went away. Cargo didn't warn on this, but now it does. As such, we
need a release so that rust's build doesn't warn constantly.
> Fix toml problem and release 0.0.23

- src/book/mod.rs
To only ignore the output destination (default: `book`) and no other
file/directory with the same name under the mdbook root, we should
prefix the gitignore rule with a leading slash (default: `/book`).
> [book] Prevent over-matching in gitignore rule

- appveyor.yml
- build.rs
fixes https://github.com/azerupi/mdBook/issues/342
@azerupi I finally had little time to tinker with win 10 box and fixed the long standing bug with `cargo build --features=regenerate-css`.
also added css regeneration build to appveyor.
> fixed `cargo build --features=regenerate-css` on win 10 / nightly

- src/theme/book.css
- src/theme/book.js
- src/theme/stylus/general.styl
fixes https://github.com/azerupi/mdBook/issues/396
- list of available crates is dynamically loaded from play.rust-lang.org
- play button is enabled only if crates used in snippet are available on playground
- ACE editor's play button is dynamically updated on each text change
- `no_run` is honored by always disabling the play button
- minor cleanups/refactors
This might not be ready for prime time as currently the play button is just hidden if both on `no_run` and when using crates unavailable on play.rust-lang.org. I would like to eventually just disable the play button with some visual cue (dim/color change) and tooltip describing the state (I guess that It'll wait for https://github.com/azerupi/mdBook/issues/388 ;)).
But I wanted to push the WIP for review as soon as possible as I'll …
> Dynamic play button based on `no_run` property and used crates availability 

- src/bin/watch.rs
related to https://github.com/azerupi/mdBook/issues/383
This PR might not solve the #383 completely, I do not have kate installed (nor willing to pull halve of kde to test it ;) but it solves an annoying double/triple build on each file edit with vim on my system.
> Do not trigger spurious watch events on Write and Remove

- Cargo.toml
- src/bin/watch.rs
IIUC, the existing exclude rule has meant to do what it will do in the
future (gitignore-like matching, not glob-only matching). This fix makes
the rule to do what it was expected to do, and is forward-compatible,
therefore fixing the warning messages.
> [Cargo.toml] Fix package.exclude warnings

- src/renderer/html_handlebars/hbs_renderer.rs
makes `ignore`'d playpens runnable
fixes https://github.com/azerupi/mdBook/issues/434
this might require some refactoring as our `ignore` handling is not cleanest at the moment
> added `mdbook-runnable` infostring support

- src/theme/book.js
This PR switches to using https://play.rust-lang.org/execute for the execution of rust code. It seems like the older evaluate.json format will not (understandably) support newer features. This now allows adding support to run as a lib crate or run with test configuration.
> Call playground with /execute

- src/bin/watch.rs
- src/renderer/html_handlebars/hbs_renderer.rs
In response to #458.
I did not fix two of clippy's warnings:
```
warning: returning the result of a let binding from a block. Consider returning the expression directly.
--> src/renderer/html_handlebars/hbs_renderer.rs:137:9
|
137 |         rendered
|         ^^^^^^^^
|
= note: #[warn(let_and_return)] on by default
note: this expression can be directly returned
--> src/renderer/html_handlebars/hbs_renderer.rs:135:24
|
135 |         let rendered = add_playpen_pre(&rendered, playpen_config);
|                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#let_and_return
```
I think the code is more readable as it is currently than clippy's suggestion. Should I add …
> Fix some clippy warnings

- src/theme/index.hbs
It's standard practice to put CSS in the `<head>` and any JavaScript imports go at the bottom of the body section. I've shuffled around the template to place custom JS at the end of the document.
> Custom JS belongs at the bottom

- src/theme/index.hbs
This makes sure google analytics isn't triggered when you are inspecting the document on your local computer. This will only ever really happen during development, so it doesn't make sense to pollute google analytics whenever you are working on the book.
> Conditional Google Analytics

- src/theme/book.js
- src/theme/index.hbs
fixes #388
added titles to play/copy/reset, expand/collapse and sidebar/theme buttons
> add tooltip to icons

- src/theme/book.css
- src/theme/stylus/theme-popup.styl
This prevents the theme popup from pushing around the text below it.
> Use absolute positioning for theme popup

- src/renderer/html_handlebars/helpers/navigation.rs
This is my attempt at a piece of #458.
- Code duplication between `previous()` and `next()` have been removed.
- Finding a chapter and rendering it have been split to separate functions.
There are probably tons of potential improvements, but it still feels a lot cleaner than before :blush:.
> Refactor navigation helpers

- src/book/mod.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/header.hbs
- src/theme/index.hbs
- src/theme/mod.rs
Addresses #453.
Giving this an initial stab.
I've tested it and it works: you need to point the theme at the location of your theme folder with the modified `header.hbs`, otherwise the default one is blank.
This still doesn't address the problem of additional classes/CSS, though...
Let me know what you think!
> Adding a header partial integration #453

- src/book/mod.rs
- tests/init.rs
> So, this is now causing the nomicon to fail building: https://travis-ci.org/rust-lang-nursery/nomicon/builds/313641706?utm_source=email&utm_medium=notification
>
> is book.toml required now?
It looks like I accidentally made `book.toml` required in #457 instead of falling back to the default `Config` if it doesn't exist. This fixes that issue.
([comment])
[comment]: https://github.com/rust-lang-nursery/mdBook/pull/457#issuecomment-350354816
> Added a quick fix so if the config isn't found we use a default

- src/theme/book.css
- src/theme/index.hbs
- src/theme/stylus/nav-icons.styl
- src/theme/stylus/page.styl
- src/theme/stylus/theme-popup.styl
- src/theme/stylus/variables.styl
The original state:
The fixed one:
> Fix misplaced "previous" icon

- src/bin/serve.rs
- src/bin/watch.rs
As of #491, rebuilding the same `MDBook` with `mdbook watch` and `mdbook serve` won't reload the book. This is because `MDBook::load()` caches the book in memory and future calls to `build()` won't invalidate that cache.
> Made `mdbook watch` and `mdbook serve` rebuild the book again

- src/theme/book.js
> Fix copy to clipboard is available only for rust snippets

- src/config.rs
Avoids issues where we enable `editable` but forget to specify `editor` (eg, https://github.com/rust-lang/rust-by-example/issues/963). 
Since we already include Ace editor, seems like we can just treat it as the default.
> Implement playpen defaults

- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/stylus/general.styl
- src/theme/stylus/nav-icons.styl
- src/theme/stylus/page.styl
- src/theme/stylus/sidebar.styl
- src/theme/stylus/theme-popup.styl
- src/theme/stylus/variables.styl
At lower screen widths, when the sidebar is visible or transitioning to/from visible, the page wrapper will attempt to fit within the remaining screen width. On mobile devices, this leads to undesirable line wrapping and overflow. This change sets the width of the page wrapper to be equivalent to the screen width when the screen width is less than the sidebar width plus the maximum content width (1080px), simply causing the sidebar to push the page wrapper off-screen when it is visible.
Before and after:
I also changed some behavior regarding the sidebar's state when the page is loaded. If the screen width is less than 1080px, it will be hidden (so it doesn't load with the content pushed off-screen). Otherwise, it uses the stored value, defaulting to visible if there isn't one.
> Improve experience on smaller screens

- .travis.yml
- ci/before_deploy.sh
- ci/github_pages.sh
- ci/install.sh
- ci/script.sh
The last several releases haven't uploaded binaries. I've updated `.travis.yml` to use japaric/trust to configure travis, plus created a new Personal Access Token so releases should hopefully work again.
Testing on the `beta` channel was previously deactivated because there was a compiler issue (see #490 and #492). It should be working again so I've re-enabled `beta` testing.
Because I've added a bunch more targets the CI build times may be adversely affected... I'll see how it goes, but may end up removing a couple targets if it becomes a problem.
---
I'm not sure what we're going to do about Appveyor. It's been broken ever since we moved mdbook to the nursery, meaning we're not currently testing or generating release binaries for windows. The easiest way to deal with it would be to tell …
> Update travis CI

- Cargo.toml
- ci/github_pages.sh
It looks like staticfile `0.5` isn't compatible with iron `0.6` because the `0.6` version of `iron::Handler` isn't implemented for `staticfile::Static` (0.5). To work around this I'm rolling the versions back one.
I've also fixed an issue in the `github_pages.sh` script where `--quiet` isn't a valid argument to `git add`.
> Roll back iron version in Cargo.toml

- src/bin/mdbook.rs
- src/bin/serve.rs
- src/bin/watch.rs
The `trigger_on_change()` was previously only executing once because we were "iterating" over the result of `rx.recv()` (a `Result<Event>`), instead of the iterator, [`rx.iter()`]. 
```diff
println!("\nListening for changes...\n");
-    for event in rx.recv() {
+    for event in rx.iter() {
match event {
Create(path) | Write(path) | Remove(path) | Rename(_, path) => {
```
This also fixes an issue where the livereload wasn't being re-set on consecutive builds in `mdbook serve`.
[`rx.iter()`]: https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.iter
> Fixed a regression introduced by previous refactoring of `mdbook watch`

- README.md
This adds a link to the `master` docs. It also makes a couple formatting changes to (hopefully) make reading in a text editor easier.
- Constrain to 80 columns
- Use footnote-style links instead of copy/pasting the URL inline - inline adds loads of noise and there were 3 or 4 copies of the `[User Guide]` link
> Reformatted the README and added a link to the `master` docs

- Cargo.toml
- src/lib.rs
- src/preprocess/links.rs
- src/utils/mod.rs
- src/utils/string.rs
The macro `{{include some_file}}` accepts now optional line number arguments, s.t. the specified line range is included. The following forms are supported:
* `{{include some_file::}}` is equivalent to `{{include some_file}}`
* `{{include some_file:from:}}` includes lines [from, infinity)
* `{{include some_file::to}}` includes lines [0, to]
* `{{include some_file:from:to}}` includes lines [from, to]
This is useful when including files containing full source code.
> Implement partial include of source files

- src/lib.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
Fix #258 by emmiting an error whenever an mdBook contains a `print.md` file in its root.
> Prohibit 'print.md' files

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/toc.rs
Allow user to disable section label in the html.
User may have custom rules for naming their sections in 'SUMMARY.md', e.g. "Chapter 0", "Chapter 1.1". By default, it would show up as "1. Chapter 0", and "2.1 Chapter 1.1". In this case, we may provide an option to hide the auto generated labels.
Just saw #504 for similar goal. The change here is a bit lightweighted, which controls html output only.
> Add option to disable section label in html

- Cargo.toml
- book-example/src/format/config.md
- src/book/mod.rs
- src/config.rs
- src/lib.rs
This lets you override config options by setting the appropriate environment variables. This is essentially just a wrapper around the `Config::set()` method, with the original "index" being provided by the environment variable's key (after a couple transforms).
closes #540, closes #291.
> Override configuration using environment variables

- Cargo.toml
- src/lib.rs
- src/renderer/mod.rs
- tests/alternate_backends.rs
Previously I was writing the `RenderContext` to a temporary file and then hooking it up to the subprocess' `stdin`, but for some reason this didn't work as planned because the child process wasn't receiving anything. This reverts that earlier idea and just writes to `stdin` directly.
> Write RenderContext to the subprocess' stdin again

- src/renderer/html_handlebars/helpers/toc.rs
- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/stylus/menu.styl
- src/theme/stylus/nav-icons.styl
- src/theme/stylus/page.styl
- src/theme/stylus/sidebar.styl
- src/theme/stylus/theme-popup.styl
- src/theme/stylus/themes/base.styl
Most commits have a body explaining the reasoning behind the changes.
> Improve accessibility

- src/theme/book.js
- src/theme/index.hbs
Makes the browser chrome match the selected theme (to avoid having a bright white toolbar when you chose a dark theme - also looks nice). Currently only supported in Chrome for Android (left is before, right is with this patch).
> Meta theme color

- .travis.yml
- src/renderer/mod.rs
For the past couple days it looks like all OSX jobs have been "waiting to be queued" indefinitely. I'm going to disable the CI jobs temporarily so GitHub doesn't erroneously show PRs as failing (because travis kills the job after 12 or so hours of waiting).
> Temporarily ignore OSX jobs on travis

- book-example/book.toml
- book-example/src/SUMMARY.md
- book-example/src/format/theme/editor.md
- book-example/src/misc/contributors.md
> Documenting the editor #521

- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/playpen_editor/editor.js
- src/theme/stylus/themes/base.styl
~~This is based on #535 for two reasons:~~
- ~~I assumed that #535 is likely to be (eventually) merged, so I can rebase this later against `master` in that case~~
- ~~Make it easier for reviewers to test both of them at the same time~~
~~Depending on which browsers we need to support (couldn't find them listed), we might need the following polyfills~~:
- ~~[Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Browser_compatibility) (no IE)~~
- ~~[String.trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#Browser_compatibility) (no IE 8)~~
- ~~[Element.closest](https://caniuse.com/#feat=element-closest) (no IE)~~
- ~~[Promise](https://caniuse.com/#feat=promises) (no IE)~~
- …
> Remove jQuery

- Cargo.toml
- src/book/summary.rs
This removes the need for a `[patch]` in `Cargo.toml`. We originally needed it because I was using `PartialEq` (implemented in google/pulldown-cmark#118) in the summary parser and because they haven't (yet) made another release we were pulling directly from `master`.
I've added in a couple `*_eq()` replacements, with `FIXME` comments so we know to remove them at a later date.
This means we can now make another release!
> Stop pulling pulldown-cmark from master

- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/stylus/general.styl
- src/theme/stylus/menu.styl
- src/theme/stylus/themes/base.styl
Questions:
- should we add a faint border at the bottom of the menu (to separate it from the content)?
- should we implement auto-hiding when scrolling down?
Closes #545.
> feat(theme/stylus/menu): Make sticky

- src/renderer/mod.rs
- tests/alternate_backends.rs
This currently breaks appveyor builds because we're assuming the `tee` command will be available when testing alternate backends and the `CmdRenderer`.
(fixes #557)
> Added a windows-specific `tee` equivalent

- src/theme/book.js
Advantages:
- Easier to reason about
- Can easily disable some modules when debugging
- Shared dependencies are explicit (playpen_text)
- Enables some fancier things later one (e.g. run `codeSnippets` slightly later, to avoid blocking the page)
I'm aware that `codeSnippets` should be split into the highlighter and the editor, but I'm not sure I understand exactly how they interact so I've left it as it is for now.
~Also replaced some occurences of `let` with `var` (for consistency).~
Closes #559.
> refactor(theme/book): Split into modules

- .gitignore
- src/book/book.rs
- src/preprocess/links.rs
- tests/dummy_book/mod.rs
- tests/dummy_book/src/SUMMARY.md
- tests/dummy_book/src/first/includes.md
- tests/rendered_output.rs
Fixes an issue raised in #558.
> Including a Rust file seems broken - https://rust-lang-nursery.github.io/mdBook/format/rust.html. Looks like it was introduced by #532.
Turns out we forgot to recursively apply replace_all() in #532, instead we just iterated over the chapters in the top level without doing any recursion. 
As well as fixing the bug mentioned, I've also made the `sections` field private so we don't accidentally get these sorts of bugs again.
> Recursively apply replace_all() when running the links preprocessor

- src/theme/index.hbs
~This still doesn't explain #573.~ Added a commit to fix it.
We could solve this in a few ways:
- maintain the convention (in 4/5 places) that values are stored in `localStorage` wrapped in quotes
- introduce theme validation in two separate places (`index.html` and `book.js`)
- unwrap items in `localStorage` in one place
For this PR I went with the last option.
> fix(theme/index): Use localStorage, not store

- README.md
cargo install --git https://github.com/rust-lang-nursery/mdBook.git
leads to error: multiple packages with binaries found: mdbook, mdbook-wordcount
Fix: append name of binary (`mdbook`).
> fix(doc): make installation from git work again

- src/theme/book.css
- src/theme/book.js
- src/theme/stylus/menu.styl
Safari scrolls on body, not on the html tag. It also needs sticky to be prefixed.
> fix(theme): Sticky header support in Safari

- Cargo.toml
- book-example/src/for_developers/preprocessors.md
- src/renderer/mod.rs
- tests/alternate_backends.rs
At the moment if a backend is missing (i.e. it fails to start), we blow up and stop the entire rendering process. This is a problem when people add a particular renderer to their `book.toml` but then someone else trying to build the book doesn't have that backend installed.
Instead of throwing an error and exiting we now emit a warning and continue on to the next renderer.
> Missing backends shouldn't be fatal

- src/theme/book.js
["Passive event listeners are a new feature in the DOM spec that enable developers to opt-in to better scroll performance by eliminating the need for scrolling to block on touch and wheel event listeners."](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)
> fix(theme/book): Use passive listeners for touchstart, touchmove

- Cargo.toml
- book-example/src/for_developers/mdbook-wordcount/Cargo.toml
When doing the `0.1.0` release a couple days back i forgot to tell `cargo-release` to prepend the tag with `v` (i.e. `v0.1.0`) and as a result CI didn't know it was meant to build binaries and push them to github releases. This just updates a couple fields in `Cargo.toml` so we don't have that issue again.
I've also removed `mdbook-wordcount` from the workspace so hopefully it should stop getting error messages like this when `mdbook-wordcount` isn't updated in lockstep with `mdbook`.
```
no matching package named `mdbook` found (required by `mdbook-wordcount`)
location searched: file:///home/michael/Documents/forks/mdBook
version required: = 0.1.0
```
> Updated Cargo.toml metadata to make releases easier

- src/book/book.rs
- src/renderer/mod.rs
Alternate backends need to be able to create a `RenderContext` (e.g. for a "standalone" mode or testing) and add chapters to a `Book`.
> Expose functionality for creating core types

- .travis.yml
This reverts #549 so we are running mac builds in CI again. Needed for #558.
> Reverted #549

- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/stylus/themes/base.styl
Unfortunately, it only works in WebKit browsers for the moment. There is a [new spec](https://www.w3.org/wiki/Css-scrollbars) being written which will hopefully gain more traction.
> feat(src/theme): Scrollbar theme

- src/renderer/html_handlebars/hbs_renderer.rs
@Havvy, this should fix #585. It seems we were just blindly copying from the source location to the destination and not checking the destination directory exists.
> Made sure we create the themes directory

- src/theme/book.css
- src/theme/stylus/themes/ayu.styl
- src/theme/stylus/themes/base.styl
- src/theme/stylus/themes/coal.styl
- src/theme/stylus/themes/light.styl
- src/theme/stylus/themes/navy.styl
- src/theme/stylus/themes/rust.styl
The current scrollbar colour for the light theme is a little jarring and doesn't quite feel like it fits the rest of the theme. This just pulls the scrollbar colour out into its own variable which defaults to the `$sidebar-fg`, overriding it to `#ccc` for the light theme.
---
Before:
After:
> Updated the light theme to have a lighter scrollbar

- src/theme/book.js
- src/theme/index.hbs
Tested this on macOS with VoiceOver, and it does not pick up the title as the text of the button. Kind of makes sense, since `title` and `aria-label` are not the same. This will make sure that the buttons and links are labeled properly.
> fix(theme): Use aria-label alongside title

- src/renderer/html_handlebars/hbs_renderer.rs
Before, when someone like the Reference set their extra css as
"theme/reference.css" in their book.toml, this path would be treated as
relative to the invocation of mdbook, and not respect the input path. This
PR modifies these relative paths to do so.
Fixes the build of https://github.com/rust-lang/rust/pull/47753 which
blocks updating rustc to mdbook 0.1
It'd be nice to get a release cut with this fix so we can ship that PR!
> Handle input path with regards to custom css

- src/theme/book.css
- src/theme/stylus/general.styl
Footnotes are inlined and made slightly smaller. Also, the first non-consecutive footnote has a bigger margin to the previous element. Fixes #210.
Rendered example:
> Inline footnotes

- .gitignore
- Cargo.lock
The guidelines say that applications should check in the Cargo.lock file, and I need a Cargo.lock file to be in-repo for including mdbook into nixpkgs.
> Include Cargo.lock

- src/theme/book.css
- src/theme/stylus/sidebar.styl
> A position fixed left navigation bar does not want to hand off scrolling to the document because a scroll gesture performed on the navigation bar is almost never meant to scroll the document. In this case, the author can use contain on the sidebar to prevent scrolling from being chained to the parent document element.
https://wicg.github.io/overscroll-behavior/#motivating-examples
> Contain scrolling to the sidebar

- src/theme/book.css
- src/theme/stylus/page.styl
When clicking on anchors, they don't go under the top navbar now.
> Improve css so anchor don't go under sidebar

- src/book/book.rs
This exposes a `Book`'s `sections` field so other people can traverse a book recursively without the ugly contortions we had in #629 (no offense intended @Byron!).
> Exposed the sections inside a book

- src/bin/init.rs
I was getting panics while trying to run `mdbook init` and located the issue being that I don't store my global git config in `~/.gitconfig` so I changed this function to call `git config` instead.
`git config` will automatically find the correct config file using it's preferred method (https://git-scm.com/docs/git-config#FILES)
> Use `git config` to get author name in `mdbook init`

- Cargo.lock
- Cargo.toml
- src/book/book.rs
- src/book/mod.rs
- src/lib.rs
- src/theme/mod.rs
- src/utils/fs.rs
- tests/alternate_backends.rs
- tests/dummy_book/mod.rs
- tests/init.rs
- tests/rendered_output.rs
The former has been deprecated in favor of the latter
> Replace tempdir by tempfile

- src/theme/searcher/searcher.js
Heyo 👋 
I was playing with the interactive code editor in Rust By Example: https://rustbyexample.com/primitives/tuples.html when I noticed that typing `s` would bring up search and prevent me from coding with the letter s.
So, I added a check that exits the search event handler if the event originated in a `<textarea />`. I could have checked for class `ace_text-input` but that might have made the code more brittle if someone would happen to change the class for styling purposes.
> Prevent search from triggering when editing code

- src/theme/book.css
- src/theme/book.js
- src/theme/index.hbs
- src/theme/playpen_editor/editor.js
- src/theme/searcher/searcher.js
- src/theme/stylus/menu.styl
- src/theme/stylus/page.styl
- src/theme/stylus/searchbar.styl
- src/theme/stylus/sidebar.styl
- src/theme/stylus/themes/base.styl
- src/theme/stylus/variables.styl
Fixes #647
See the commit messages.
> Fix several theme issues

- src/theme/mod.rs
- src/theme/searcher/searcher.js
It's good practice to not assume the gender of the reader or a hypothetical developer.  The simple fix is to replace instances of `his` with `their` and `him` with `them` or `the user`.
I did a simple search with `ripgrep` so I may have missed some instances, but  `his` only appears twice as far as I could tell, so I replaced both instances with `their`.
> Replace his with their in reference to reader

- src/theme/book.css
- src/theme/stylus/searchbar.styl
When the sidebar is open and viewing full screen, the *empty* search box overlaps with page content.
Making the `searchbox-outer` display as a `block` element *seems* to fix the issue.
> Fixes the search box overlapping with content when first shown

- book-example/src/format/mathjax.md
There is a "hard to google" issue with some advanced math commands that uses double backslashes. I added a note in the documentation so that it is clear how to solve it.
> Add a note in MathJax documentation

- src/theme/book.css
- src/theme/index.hbs
- src/theme/stylus/print.styl
Since #648, the content doesn't use `left`/`padding-left` to make room for the sidebar, instead using `transform`/`margin-left`. The print CSS wasn't updated for this change, so if the sidebar was visible it would push content to the right when printing.
> Improve print output

- book-example/src/format/config.md
Update documentation for #685.
If the explanation is not informative nor expressive, please let me know and help to improve it.
> Update documentation for build.preprocess config

- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
Fixes #695 
Another option would be to accept both `/theme` and `/src/theme`, since some may have begun relying on the undocumented behavior.
> Fix default theme dir selection

- src/preprocess/links.rs
- tests/dummy_book/src/SUMMARY.md
- tests/dummy_book/src/first/recursive.md
- tests/rendered_output.rs
- tests/searchindex_fixture.json
Sends the content inserted through the links processor.
fixes #678
> Recursively apply preprocessor

- book-example/src/SUMMARY.md
- book-example/src/continuous-integration.md
This adds instructions for building and testing books in CI on every PR and push, as well as instructions for how to automatically deploy to gh-pages on successful CI runs on `master`.
Fixes #714
r? @steveklabnik
> user guide: Add instructions for running `mdbook` in CI

- book-example/src/cli/init.md
- book-example/src/for_developers/README.md
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/theme/book.js
- src/theme/index.hbs
- src/theme/searcher/searcher.js
- src/utils/mod.rs
- tests/rendered_output.rs
So this PR is a breaking change.  This converts everything to a relative URL, and also resolves internal links, solving https://github.com/rust-lang-nursery/mdBook/issues/408.
This does two things:
Currently the html output relies heavily on the `<base href`  for links.  This PR basically removes this from the template, and converts all links to relative, adding in the appropriate `path_to_root` variable.
Removing this has the following benefits:
* Images work on non-root URLs I.e, `http://example.com/book/`.
* A lot of workarounds can be stripped out: anchors and the index page come to mind.
* It enables the ability to convert internal links as per below
This is the second part of the change, and does break the internal structure of some books, but fixes …
> Use relative links and translate internal references

- Cargo.lock
- Cargo.toml
This removes one of the remaining dependencies upon pre-1.0 regex.
> Update to elasticlunr 2.3.

- src/theme/book.js
Fixes #640. Well, it doesn't check that a playpen includes an `extern crate`, but this should remove >80% of the unnecessary requests.
> Only fetch crates list on pages with playpens

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/search.rs
- src/theme/searcher/searcher.js
- tests/rendered_output.rs
- tests/searchindex_fixture.json
> Optimize search index

- src/theme/book.css
- src/theme/stylus/sidebar.styl
Fixes #729.
The original intent was to have ellipsis on long titles, but I don't think that works well for subsections given the narrow width of our sidebar. Allowing titles to wrap doesn't look too bad:
> Allow sidebar section titles to wrap

- src/theme/book.css
- src/theme/stylus/menu.styl
- src/theme/stylus/variables.styl
Before:
After:
I think an ideal solution would move these controls into the sidebar on narrow viewports, but this is an easy improvement for now.
> Reduce the margins on header icons on narrow devices

- src/renderer/html_handlebars/hbs_renderer.rs
This class will supress the "play" button in the html backend (which you can also do with the "ignore" class), but it will still let the code be tested via `mdbook test` (which is not possible with the "ignore" class).
This is useful for code examples that don't really do much (and so the user doesn't gain much from running them), but as an author you still want to test them to guard against syntax errors and typos and the like.
Notes:  this new class is not documented (see #602), and also this uses the term "playpen", which is prevalent in the mdbook source code, but is not the preferred name (see #674)
> Add a "noplaypen" class for rust code samples.

- src/renderer/html_handlebars/hbs_renderer.rs
> Fix relative paths in index.html

- book-example/src/cli/build.md
- book-example/src/cli/clean.md
- book-example/src/cli/init.md
- book-example/src/cli/serve.md
- book-example/src/cli/test.md
- book-example/src/cli/watch.md
- book-example/src/format/mdbook.md
- book-example/src/format/theme/index-hbs.md
- src/cmd/build.rs
- src/cmd/clean.rs
- src/cmd/init.rs
- src/cmd/serve.rs
- src/cmd/test.rs
- src/cmd/watch.rs
- src/main.rs
Mostly improves wording and formatting. Includes breaking changes to two subcommands:
- **serve**: some arguments have been renamed to make more sense
- **test**: the `library-path` argument now requires a comma-delimiter so that ` -- ` isn't required to give a `dir` argument
> Improve command-line argument parsing

- src/theme/css/variables.css
`darken` and `lighten` functions only live in CSS preprocessors. They should be replaced with actual colors 😃.
> Fix table and quote related color

- src/theme/index.hbs
Expressions in an `#each` block need to begin with `../` to reference values in the main context.
Closes #774.
> Fix paths to additional CSS and JavaScript files

- examples/de-emphasize.rs
- src/book/mod.rs
- src/config.rs
- src/preprocess/index.rs
- src/preprocess/links.rs
- src/preprocess/mod.rs
- tests/build_process.rs
- tests/testing.rs
This adds the ability to configure a Preprocessor and specify which renderers it gets run for.
It effectively changes the build step to be something like:
```rust
for renderer in &self.renderers {
let mut book = self.book.clone();
for preprocessor in &self.preprocessors() {
if should_run(preprocessor, renderer.name()) {
book = preprocessor.run(book)?;
}
}
renderer.render(book)?;
}
```
Where the `should_run()` function inspects the `book.toml` to first ensure we're allowed to run this preprocessor with a specific renderer, falling back to a new `Preprocessor::supports_renderer()` method if the user doesn't say anything. This setup means the user always has the final say, via their `book.toml`.
We'll need to update the `book.toml` format to have a `build.use-default-preprocessors` flag now …
> Configurable preprocessor

- book-example/src/for_developers/preprocessors.md
- book-example/src/format/config.md
@Michael-F-Bryan  This is the documentation you require for the preprocessor change.
The link - `[preprocessor-docs]` is forward looking 
* that is a little harder - we need a preprocessor for that :-D
> Updated the documentation for new preprocessor format

- CONTRIBUTING.md
This PR is some extra text for the `CONTRIBUTING.md` guide.
It will resolve the one of two items on #270.
The other item, 
I believe is already satisfied when you read the section in `CONTRIBUTING.md` [Issues to Work On](https://github.com/rust-lang-nursery/mdBook/blob/master/CONTRIBUTING.md#issues-to-work-on)
as it explains the various areas that can be contributed to.
> Resolves #270. details for Clippy and Rustmft usage

- book-example/src/for_developers/README.md
Old link resulted in 404.  This PR make the link consistent with README.md in the book-example/src directory.
> Fix broken link to API pages

- src/book/summary.rs
> Ensure section numbers are correctly incremented after a horizontal separator

- book-example/src/continuous-integration.md
I debugged 10 commits to figure out why the following failed
```
- cd docs && mdbook build
- cargo doc && cp -r target/doc docs/book/api
```
It should be
```
- mdbook build docs
- cargo doc && cp -r target/doc docs/book/api
```
> avoid using `cd` in example travis-ci script

- book-example/src/for_developers/preprocessors.md
- examples/de-emphasize.rs
- examples/nop-preprocessor.rs
- src/book/mod.rs
- src/lib.rs
- src/preprocess/cmd.rs
- src/preprocess/links.rs
- src/preprocess/mod.rs
- src/renderer/mod.rs
- tests/custom_preprocessors.rs
This lets anyone provide their own custom preprocessor by shelling out to the provided command.
CC: #762, @badboy
> WIP: Custom Preprocessors

- src/config.rs
It is quite confusing that you should assign `true`, when the answer to the documentation comment is actually *"no"*.
> Improve documentation comments

- src/utils/mod.rs
In HTML5 standard, there is no restriction on what forms an ID attribute. The only reason to append a alphabet in the front of original characters is for compatibility. 
As far as I know, some popular content generating services, including GitHub, GitBook and GitLab, accept a heading with non-alphabetic initial as a valid ID attribute. Maybe we can conform with the standards without appending an unexpected arbitrary character on ID. This feature will make writing much more ergonomic for non-English users.
Reference: https://www.w3.org/TR/html52/dom.html#element-attrdef-global-id
> Allow non alphabetic initial in heading anchor

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/mod.rs
- src/renderer/html_handlebars/helpers/theme.rs
- src/theme/book.js
- src/theme/index.hbs
Opening a PR to initiate discussion.
Everything is there and working, but there are a few things I dislike/am unsure of.
1. Calling this option `default-theme` is confusing to the user. The options are presented as 'themes' to the visitor in the theme popup, but from a user's perspective the theme is the whole theme inside `src\theme`. Maybe this should be `default-style` or `default-theme-style`? Maybe I just need to explain the option better in the documentation?
2. I created a new handlebars helper to append ` (default)` to the selected default theme in the theme popup. Originally I had done this in the [javascript that sets the theme on page load](https://github.com/rust-lang-nursery/mdBook/blob/396426662de5ff6a9f12b8892ef89eba17b3bba2/src/theme/index.hbs#L57-L61), but it seemed a bit …
> Default theme option

- src/renderer/mod.rs
The original link is no longer working.
> Fix invalid url in renderer documentation

- book-example/src/cli/README.md
https://www.rust-lang.org/downloads.html is the outdated link.
> Update broken link at the user guide.

- src/cmd/serve.rs
The livereload url was using an unknown property "websocket-address" instead of "websocket-hostname", hence it was always fallback onto the hostname (which can be different).
> Fix websocket hostname usage

- .travis.yml
The deploy scripts require TARGET env var to be set, but it wasn't set anywhere, causing it to fail: https://travis-ci.com/rust-lang-nursery/mdBook/builds/97850452.
This also reduces the number of mac builders, since they aren't necessary, and capacity is limited.
The api key will likely need to be updated, too, since the transition to travis.com.
Appveyor also seems to be broken, but I suspect it is also a key issue.
> Fix deploy on Travis.

- src/utils/mod.rs
- tests/rendered_output.rs
There's still a deprecation warning for `Error::source` that [comes from error-chain](https://github.com/rust-lang-nursery/error-chain/pull/255), but this fixes warnings originating in mdBook's code, at least.
> Fix deprecation warnings for trim left/right matches

- src/main.rs
I thought it was beautiful looking at the help of the fd command
> Add colored help

- src/renderer/html_handlebars/hbs_renderer.rs
Previously, additional JavaScript files inside a directory were
correctly copied (with their parent created), but the link to it was
stripped of that parent.
There's no need for that (and it was not done for CSS)
> Don't strip relative path of additional javascript files

- src/theme/book.js
- src/theme/css/chrome.css
- src/theme/css/general.css
- src/theme/index.hbs
> Add sidebar resize

- src/book/book.rs
- src/book/mod.rs
This is useful for situations where you'd like to supplement or replace the existing Summary parsing with
custom filesystem traversal code or other similar changes.
In this context, a Summary is almost a "build rules" input for the book, so that an embedder can use their own layout while still benefiting from the actual file reading/parsing/etc provided by mdbook.
> Expose API for building a book with a custom Summary.

- book-example/src/continuous-integration.md
I had some trouble with the way that mdbook cleans the target directory, this documents how I worked around that. I'll try and come up with a patch for clean, that leaves `.git` in tact.
> add docs for publishing to github pages manually

- src/theme/css/chrome.css
Linked code span colors were fixed in #289, but the fix was lost in #315 when inline code colors were added.  The issue (I believe) is that the specificity of `:not(pre) > .hljs` is greater than `a > .hljs`.  I added a new rule which applies the inline color, but excludes `a` tags.
Fixes #537
This is has been reported in several other places: https://github.com/rust-lang/book/issues/1115, https://github.com/rust-lang/cargo/issues/6862
Theme | Example
------ | ----------
Light | <img width="426" alt="image" src="https://user-images.githubusercontent.com/43198/57096981-57e07700-6ccb-11e9-9c8e-43bb6ccbc3d8.png">
Rust | <img width="427" alt="image" src="https://user-images.githubusercontent.com/43198/57097004-6b8bdd80-6ccb-11e9-8f63-e1153ad5edac.png">
Coal | <img width="431" alt="image" …
> Fix color of `code spans` that are links.

- src/book/mod.rs
- tests/build_process.rs
- tests/custom_preprocessors.rs
> fixes typo in code

- src/renderer/html_handlebars/hbs_renderer.rs
The "next" link on `index.html` wasn't working because the navigation code was checking for `index.md` style links, but this was defining the page as `index.html`.  I didn't check, but I'm guessing this has been broken since mdbook switched to `.md` style links in 0.2.
Fixes #874.
> Fix "next" navigation on index.html.

- src/renderer/html_handlebars/search.rs
- tests/rendered_output.rs
This fixes it so that keyboard navigation should work when loading a book from a `file://` url.
When loading the search index, if it fails due to a CORS error (such as when loading json from `file://`), it will load the `searchindex.js` version instead [here](https://github.com/rust-lang-nursery/mdBook/blob/7ab939f8f29a7e0cebcf1e573f6c393b185ffa89/src/theme/searcher/searcher.js#L468-L473). However, this was written to replace the `window.search` object which loses the [`hasFocus`](https://github.com/rust-lang-nursery/mdBook/blob/7ab939f8f29a7e0cebcf1e573f6c393b185ffa89/src/theme/searcher/searcher.js#L476) method which caused the [keyboard handler](https://github.com/rust-lang-nursery/mdBook/blob/7ab939f8f29a7e0cebcf1e573f6c393b185ffa89/src/theme/book.js#L536) to fail because `hasFocus` …
> Fix keyboard chapter navigation for `file` urls.

- src/theme/css/chrome.css
This resolves weird rendering behavior in Chrome and Safari on macOS.
---
> Change overflow-x to initial

- src/utils/mod.rs
- tests/dummy_book/src/second/nested.md
- tests/rendered_output.rs
- tests/searchindex_fixture.json
- Rewrite relative links that point to non-markdown files like images (fixes #789).
- Rewrite relative links that go outside of the book. Several Rust books use
links like `../../std/ops/trait.Index.html` and these need to be rewritten,
too.
> Fix more print.html links.

- book-example/src/continuous-integration.md
```diff
- (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
-  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
+  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook)
- cargo install-update -a
```
Because otherwise people will ^C^V and `cargo install-update -a` will have to install mdbook again but with a newer version
> Update mdbook 0.1 -> 0.2 in docs for CI

- .travis.yml
- appveyor.yml
This should fix deploying release artifacts and gh-pages for the documentation.
Secrets should now be configured in the UI for travis and appveyor.
This also removes some of the appveyor jobs, since they aren't really
necessary, and there are limited jobs on rust-lang-libs.
> Fix automatic deploy.

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/css/general.css
- tests/rendered_output.rs
Fixes #896
now: 
> ![Jun-03-2019 15-48-34](https://user-images.githubusercontent.com/31783570/58781553-2f73d180-8617-11e9-997b-c32126634299.gif)
with this change:
> ![Jun-03-2019 15-48-58](https://user-images.githubusercontent.com/31783570/58781558-339fef00-8617-11e9-9c73-cb1f4f7b4698.gif)
> Header elements wrap links

- src/theme/ayu-highlight.css
- src/theme/highlight.css
- src/theme/tomorrow-night.css
This adds the rules to highlight diff lines with highlight.js.
Closes #927
> Update css to support diff syntax highlighting.

- src/renderer/html_handlebars/search.rs
- src/utils/mod.rs
- tests/dummy_book/src/SUMMARY.md
- tests/dummy_book/src/first/markdown.md
- tests/rendered_output.rs
- tests/searchindex_fixture.json
Add support for ~~strikethrough~~ and GitHub-style tasklists.
Fixes #700.
> Support strikethrough and tasklists.

- src/book/mod.rs
- tests/dummy_book/mod.rs
- tests/dummy_book/src/first/nested-test.rs
- tests/dummy_book/src/first/nested.md
- tests/searchindex_fixture.json
Rather than writing the unpreprocessed content to the file for rustdoc to test with.
Fixes #855.
I was trying to figure out whether the current behavior was intentional or not, and if I might be breaking anything with this change, but I think the fix I have here is what was intended-- my first hint was [this comment](https://github.com/rust-lang-nursery/mdBook/blob/c068703028d19fb6c5a4690e904ae6f2bd74292f/src/book/mod.rs#L248) that described what I had hoped was happening but that wasn't what was actually happening.
As of [this commit](https://github.com/rust-lang-nursery/mdBook/commit/ddf31dcc086ffc45defebfd30aa0de8b318f7348), it seems like the behavior I was hoping for was happening and was intended ("now `mdbook test` does full link expansion to temp file prior to running" in the …
> Write preprocessed content to file before testing with rustdoc

- .travis.yml
- README.md
I did some research by running the tests in travis with different Rust versions, and the first Rust version to successfully build mdbook commit 69a08ef390750d3cdbcdf807f505e559eb6418c6 (v0.3.0) is 1.34 because pulldown-cmark 0.5.2 uses try_from.
Here are the two builds where I was testing different versions:
- https://travis-ci.com/integer32llc/mdBook/builds/116221517
- https://travis-ci.com/integer32llc/mdBook/builds/116287470
I also added 1.34 to the Travis build matrix so that we'll know sooner when a change bumps the minimum.
Our community surveys have shown the vast majority of Rust users are on the latest stable, so I think supporting one stable back is plenty.
> Update specified minimum Rust version and test it in travis

- src/preprocess/links.rs
- src/utils/fs.rs
- tests/dummy_book/mod.rs
- tests/rendered_output.rs
It was stabilized in 1.26, which is fine [because the current required Rust version is 1.34](https://github.com/rust-lang-nursery/mdBook/pull/960).
> Switch to the standard library's fs::read_to_string

- src/utils/mod.rs
- src/utils/string.rs
Found this TODO; `RangeBounds` was stabilized in 1.28, so this is fine [because the current required Rust version is 1.34](https://github.com/rust-lang-nursery/mdBook/pull/960).
> Use stdlib RangeBounds

- .travis.yml
This changes it so that Travis will squash the gh-pages branch each time a new release is done. The git repo is quite large (~100MB), and the hope is that this will significantly shrink it.  I don't think there is any real reason to keep the history, since it is generated from the source, and the history for that still exists.
> Don't keep gh-pages history.

- book-example/book.toml
- book-example/src/format/config.md
- book-example/src/format/theme/index-hbs.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
Currently the language attribute of the book, which is used like `<html lang={{ language }}>`, is hardcoded as fixed value `en`.
I want to use mdBook in Japanese, so make it configurable.
With these changes, we will be able to set the language of the book like:
`book.toml`
```toml
[book]
title = "the title of the book"
authors = ["rnitta"]
src = "src"
language = "ja"
```
The default value of the language is still `en`, and no changes of `book.toml` is required if you want to set language `en` as same as usual.
> Change language attribute of the book to configurable 

- Cargo.lock
- Cargo.toml
This bumps the ammonia dependency to fix a memory leak and a warning log message (https://github.com/rust-ammonia/ammonia/pull/119).  This would happen if `<script>` or `<style>` tags were found in the book.
> Fix memory leak and warning

- src/preprocess/links.rs
I was trying to read some code and kept getting confused because the variable/field names were different than what was in them. I couldn't handle the dissonance in my head, so I renamed them :)
> Small cleanups of variable/field names

- Cargo.lock
- tests/dummy_book/src/SUMMARY.md
- tests/dummy_book/src/first/unicode.md
- tests/rendered_output.rs
- tests/searchindex_fixture.json
Update elasticlunr dependency, fixes #971.
Also adds a test for some unicode oddities.
> Bump elasticlunr.

- book-example/src/format/mdbook.md
- src/preprocess/links.rs
- src/utils/mod.rs
- src/utils/string.rs
For issue https://github.com/rust-lang-nursery/mdBook/issues/811.
I apologize for the late pull request.
I'm not super happy with
https://github.com/rust-lang-nursery/mdBook/pull/851/files#diff-d6ae283361f866777987f4630e148843R138
and
https://github.com/rust-lang-nursery/mdBook/pull/851/files#diff-182fe74cafd75eb44defddf4511f3591R70
Please, tell me what you think about the anchored syntax. I'll update the user guide after.
In current implementation, first anchor must match regex "ANCHOR:\s*[\w\d_-]+" and similarly the ending anchor must match "ANCHOR_END:\s*[\w\d_-]+". In included file:
```
/* ANCHOR: all */
// ANCHOR: component
struct Paddle {
hello: f32,
}
// ANCHOR_END: component
////////// ANCHOR: system
impl System for MySystem { ... }
////////// ANCHOR_END: system
/* ANCHOR_END: all …
```
> Add include by anchor in preprocessor (partial include)

- src/theme/css/chrome.css
This was recently standardized and is currently implemented in Firefox Nightly.
> fix(css/chrome): Use standard property for scrollbar

- book-example/src/for_developers/backends.md
Changing `cargo install` to `cargo install --path .` prevents the following error:
**error:** Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.
> Add `--path .` to cargo install commands.

- book-example/src/for_developers/backends.md
- src/book/mod.rs
- src/renderer/html_handlebars/hbs_renderer.rs
This is something that came up in my rewrite of `mdbook-linkcheck` (https://github.com/Michael-F-Bryan/mdbook-linkcheck/pull/11). I'd implemented a cache so we don't execute lots of slow web requests too frequently, and found that the cache file didn't exist every time the `mdbook-linkcheck` backend was invoked.
We probably want to let backends cache previous results. This PR removes the call to `utils::fs::remove_dir_content(&build_dir)` in `MDBook::build()` and makes sure the the HTML renderer manually cleans its destination directory.
I've also updated the user-docs to mention this.
> Allow backends to cache previous results

- src/preprocess/links.rs
Hi, I have a new feature I'm working on that I could really use for the book (https://github.com/rust-lang-nursery/mdBook/issues/618), but these refactorings make it easier. I decided to submit these first separately from the new feature, to get feedback before basing the new feature on this.
There are 2 big chunks of refactorings in this PR, and I'm happy to split them into 2 PRs if anyone wants:
- The first commit extracts a data structure to hold the different kind of ranges, so that different kinds of file including mechanisms can use the same data structure. This reduces some kinds of repetition, but adds a bit more boilerplate.
- The rest of the commits improve the `parse_include_path` function: I think I've gotten test coverage around all the branches, and I think I've improved the …
> Refactoring of some functionality in links.rs

- src/theme/css/chrome.css
Before: https://rust-lang-nursery.github.io/mdBook/format/config.html 
After: https://wofwca.github.io/mdBook/format/config.html
* Set on-hover background-color. This should prevent accidental clicks as the buttons were not very noticeable.
* Stretch them to full height
Works ok on all themes.
Related: #993 
Will conflict with #989
> ui: Improve next/prev chapter links' style

- src/theme/css/general.css
This PR fixes #823 by applying the default padding for table cells (`padding: 3px 20px;`) to header cells.
> Fix #823: Apply default padding to table headers

- tests/testing.rs
I break this test often as I'm working on mdBook, and its output isn't very forthcoming with an explanation about why it failed.
With this change, when this test fails, it'll print out the error message that `mdbook` prints when `mdbook test` fails. TESTS ALL THE WAY DOWN!!
Output before this change if this test fails (I broke `include` on purpose to illustrate a failure):
```
$ cargo test --test testing
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running target/debug/deps/testing-c42aba08d8f4704b
running 2 tests
test mdbook_can_correctly_test_a_passing_book ... FAILED
test mdbook_detects_book_with_failing_tests ... ok
failures:
---- mdbook_can_correctly_test_a_passing_book stdout ----
thread 'mdbook_can_correctly_test_a_passing_book' panicked at 'assertion failed: …
```
> When this test fails, print out why to assist in debugging

- src/preprocess/links.rs
In the same vein as #998, this is another refactoring that will also make the new feature for #618 easier.
I'm a little less sure about this refactoring, mostly because of the names I think. The code after this change feels more verbose as far as number of characters needed to type, but I do like how it has consolidated the concepts and functionality. Would love feedback!
> Another refactoring in links.rs

- README.md
- book-example/src/format/config.md
- src/book/mod.rs
- src/renderer/markdown_renderer.rs
- src/renderer/mod.rs
Use case: when trying to `mdbook test` a file that has many `include`
directives, and a test fails, the line numbers in the `rustdoc` output
don't match the line numbers in the original markdown file.
Turning on the markdown renderer implemented here lets you see what is
being passed to `rustdoc` by saving the markdown after the preprocessors
have run.
This renderer could be helpful for debugging many preprocessors, but
it's probably not useful in the general case, so it's turned off by
default.
> Implement a markdown renderer

- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
Fixes #1032 
Log deserialization errors in `Config::html_config()`, instead of ignoring them.
After implementing this, the log appeared three times, caused by multiple calls to `html_config()`. Therefore, I de-duplicated that code.
Using this `book.toml`:
```toml
[output.html]
default-theme = "navy"
curly-quotes = "true"
```
The build log displays the error:
```
[~/src/mdBook]% cargo run -- build ./book-example
Finished dev [unoptimized + debuginfo] target(s) in 0.07s
Running `target/debug/mdbook build ./book-example`
2019-09-22 21:19:14 [INFO] (mdbook::book): Book building has started
2019-09-22 21:19:14 [INFO] (mdbook::book): Running the html backend
2019-09-22 21:19:14 [ERROR] (mdbook::utils): Error: Parsing configuration [output.html]
2019-09-22 21:19:14 [ERROR] (mdbook::utils): …
```
> Log deserialization errors for [html.config]

- book-example/book.toml
- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
- src/theme/playpen_editor/editor.js
- Added line numbers to config struct
- Added playpen_line_numbers field to hbs renderer.
- Added section to set `window.playpen_line_numbers = true` in page template
- Use line number global variable to show line numbers when required.
- Updated docs
Fixes #1028
Fixes [Line Numbers for Code Editor #1193](https://github.com/rust-lang/rust-by-example/issues/1193)
> Added line numbers to editable sections of code.

- src/renderer/html_handlebars/hbs_renderer.rs
#1033 and #1035 conflicted with one another.
bors, where are you when we need you!?
> Fix merge conflict.

- .gitignore
- Cargo.lock
- Cargo.toml
- src/cmd/watch.rs
- src/utils/mod.rs
The watch command will now ignore files based on .gitignore. This can be useful for when your editor creates cache or swap files.
I saw that others were having the same issue I'm having, namely that mdBook is frantically rebuilding files with every keystroke, because the editor keeps saving it in a cache file. This allows you to add those files to .gitignore. In my case, adding a line with "*.kate-swp" fixed the problem completely.
> Added support for gitignore files.

- book-example/src/format/config.md
- src/config.rs
The comment and document say that `Search::user_boolean_and` defaults to `true`, but in fact, it is `false` by default.
https://github.com/rust-lang-nursery/mdBook/blob/a6f317e352855fe058af82d18cae5541c6b356d3/src/config.rs#L536
It seems that changing default behavior is not good, so I changed the related comment and the related doc.
> Fix Search::use_boolean_and documents

- src/cmd/watch.rs
The way it would join the paths could in some cases throw away the last part of the folder hierarchy before attaching the filename. Using `.join()` instead of `.with_file_name()` solves the issue.
> I fixed a small gitignore bug

- src/theme/book.js
- src/theme/index.hbs
This fixes https://github.com/rust-lang-nursery/mdBook/issues/1029
> Fix #1029 sidebar not auto-scrolling

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
This PR makes mdBook automatically use a dark theme if [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) is set to 'dark'.
> Automatically use a dark theme according to 'prefers-color-scheme'

- src/cmd/clean.rs
Fixes #1046 
Please let me know if I am doing something wrong here.
> Fix (command:clean): removes error message 'dir not found' if 'clean' is run multiple times

- .travis.yml
- README.md
- book-example/src/format/config.md
- book-example/src/format/mdbook.md
- src/preprocess/links.rs
- src/utils/mod.rs
- src/utils/string.rs
- tests/dummy_book/mod.rs
- tests/dummy_book/src/first/nested-test-with-anchors.rs
- tests/dummy_book/src/first/nested.md
- tests/dummy_book/src/first/partially-included-test-with-anchors.rs
- tests/dummy_book/src/first/partially-included-test.rs
- tests/rendered_output.rs
- tests/searchindex_fixture.json
Fixes #618 
This would make work on The Book to extract code listings into external, complete, testable examples easier.
I'm going to mostly let the documentation speak for itself; if it doesn't completely explain this feature, I'd like to fix it!
I'm also totally open to a different name for this feature 🤷‍♀
> Implement a `rustdoc_include` preprocessor

- src/config.rs
#1033 introduced a minor issue if `[output.html]` was not defined, it would log an error.  This happens with the default `mdbook init`.
This updates the API to use an Option and ignore missing keys.
```
2019-10-05 11:49:00 [ERROR] (mdbook::utils): Error: Parsing configuration [output.html]
2019-10-05 11:49:00 [ERROR] (mdbook::utils): 	Caused By: Key not found, "output.html"
```
> Fix error message for missing output.html.

- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
Actual fix for "next" link on index.html.
The previous fix (#916) was not sufficient, I'm not sure what happened.  `Target::find` would never match "index.md" because that page does not exist in the chapters list.
Fixes #874.
> Fix "next" navigation on index.html (take 2).

- src/theme/css/chrome.css
I tested this by regenerating the `book-example` docs and they picked up the new CSS and the wrapping and triple-click selection worked as expected. Fixes: #821
> Fix inline code display css

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
- src/theme/css/general.css
This saves a lot of useless client-side computation and makes the output look nicer when no client-side JS is available.
> Move hiding of boring lines into static content

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
- src/theme/css/general.css
This breaks the build because of rustfmt failing. Reverting it so we can fix it properly
> Revert "Move hiding of boring lines into static content"

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
- src/theme/css/general.css
- tests/rendered_output.rs
Was reverted because of formatting in #1064
> Reapply: Move hiding of boring lines into static content (#846)

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/theme/book.js
- src/theme/css/chrome.css
- tests/rendered_output.rs
Implementation of foldable table of contents.
Related issues #25 #187 
By comparing values of `chapter.section`, one can determine whether current path is a subpath. For example `1.2.3.` is a subpath of `1.2.`, so we can expand the whole ancestor section at once.
- **fold.enable:** Enable section-folding. When off, all folds are open.
Defaults to `false`.
- **fold.evel:** The higher the more folded regions are open. When level is 0, all
folds are closed. Defaults to `0`.
**No.** `output.html.fold.enable` defaults to `false`, so no any changes before enabling it.
<details>
<summary>Open to see more behaviors</summary>
</details>
> [Feature] expandable sidebar sections (ToC collapse)

- src/theme/book.js
In the default theme, there is sticky header.
The header will be hidden when the page is scrolled down. like:
This behavior make a problem with momentum scroll.
With momentum scroll, `document.scrollingElement.scrollTop` can be negative number, so scrolling up above the upper limit of a page makes such logs below:
```
[Log] document.scrollingElement.scrollTop:0 (book.js, line 593)
[Log] document.scrollingElement.scrollTop:-1 (book.js, line 593)
[Log] document.scrollingElement.scrollTop:-2 (book.js, line 593)
[Log] document.scrollingElement.scrollTop:-4 (book.js, line 593)
[Log] document.scrollingElement.scrollTop:-10 (book.js, line 593)
[Log] document.scrollingElement.scrollTop:-12 (book.js, line 593)
[Log] document.scrollingElement.scrollTop:-11 (book.js, line 593)
[Log] …
```
> Fix: Sticky header disappears by momentum scroll

- src/theme/book.js
- src/theme/css/variables.css
- src/theme/index.hbs
This primarily changes two things:
1. The default theme isn't stored as the selected theme to `localStorage` anymore. This is mainly useful for people with dynamic dark modes (i.e. only at night) because the dark mode preference is now recomputed properly on each reload as long as they didn't select a theme.
2. I added some CSS to the default themes that enable a dark mode in `no-js` mode on `prefers-color-scheme: dark`.
> Better automatic dark mode

- src/renderer/html_handlebars/helpers/navigation.rs
- tests/dummy_book/src/SUMMARY.md
- tests/rendered_output.rs
Fix "next chapter" detection in index.html when the next chapter is a spacer.
If the item in SUMMARY.md immediately after the first chapter is a spacer (`---`), then it was failing because that is not a real chapter.
Closes #1074
> Fix "next chapter" spacer handling.

- src/theme/css/chrome.css
- src/theme/css/general.css
- src/theme/css/variables.css
This addresses #1040 "Menu bar covers section header on anchor links".
I haven't attempted to make the new margin not apply in cases where the top menu bar won't be visible.
I've tested it on desktop Firefox and Chromium.
The second commit adds a CSS variable for the menu-bar height, to make it less likely that the scroll-margin-top value will become outdated if someone changes the design.
> Add CSS `scroll-margin-top` to headings which contain link targets.

- CHANGELOG.md
- CONTRIBUTING.md
- Cargo.toml
- README.md
- book-example/src/README.md
- book-example/src/cli/README.md
- book-example/src/for_developers/backends.md
- book-example/src/for_developers/preprocessors.md
- book-example/src/format/config.md
- book-example/src/format/theme/index-hbs.md
- book-example/src/format/theme/syntax-highlighting.md
- src/book/mod.rs
- src/book/summary.rs
- src/cmd/watch.rs
- src/config.rs
- src/lib.rs
- src/main.rs
- src/renderer/mod.rs
- src/theme/book.js
- src/utils/fs.rs
> rust-lang-nursery -> rust-lang

- src/renderer/html_handlebars/hbs_renderer.rs
Using `.to_lowercase()` on the theme matching to avoid needing exact capitalization in the `book.toml`. Fixes #1078
> Lowercase matching the theme name

- book-example/src/format/theme/syntax-highlighting.md
Doing what it says results in:
```
2019-11-04 16:13:15 [WARN] (mdbook::renderer::html_handlebars::hbs_renderer): Previous versions of mdBook erroneously accepted `./src/theme` as an automatic theme directory
2019-11-04 16:13:15 [WARN] (mdbook::renderer::html_handlebars::hbs_renderer): Please move your theme files to `./theme` for them to continue being used
```
> Change erroneous syntax highlighting definition

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
#1065 introduced a regression where lines in a playpen starting with `#` but nothing after that are now not hidden anymore. This PR fixes that regression and also adds a test case for this behavior.
> Fix hiding of empty boring lines

- book-example/book.toml
- book-example/src/format/config.md
- src/book/mod.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
This PR adds a config option to support Rust edition 2018 in playpens. Fixes #812.
> Add support for Rust edition 2018 in playpens

- book-example/book.toml
- book-example/src/format/config.md
- src/book/mod.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
Reverting this because it broke the build due to some merge changes
Reverts rust-lang/mdBook#1086
> Revert "Add support for Rust edition 2018 in playpens"

- src/cmd/serve.rs
- src/theme/index.hbs
When using `mdbook serve` with large files, it's tedious to have to scroll back to the bottom of the page on each reload triggered by the websocket.
The problem stems from [`location.reload(true)`](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Location/reload), which I've changed to `location.reload()`.
However we still want to always load a fresh version of the page. To fix this I've added the header `Cache-Control: no-store, max-age=0` in the server response.
> Prevent scrolling to the top of the page on websocket reload

- src/book/mod.rs
I think it's pretty common for 3rd party backends to expose some sort of `--standalone` flag so you could (for example) run `mdbook-linkcheck --standalone user-guide` to load the book and execute just that renderer.
Exposing the `MDBook::execute_build_process()` means we can replace [this](https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/ceae3b56afc0822a2c9d321c76a297366855930d/src/bin/mdbook-linkcheck.rs#L11-L24) manual construction of a `RenderContext` and invoking the rendering system:
```rust
// get a `RenderContext`, either from stdin (because we're used as a plugin)
// or by instrumenting MDBook directly (in standalone mode).
let ctx: RenderContext = if args.standalone {
let md = MDBook::load(dunce::canonicalize(&args.root)?)
.map_err(SyncFailure::new)?;
let destination = …
```
> Exposed the MDBook::execute_build_process() method to 3rd parties

- book-example/src/cli/init.md
> Fix typo in init.md

- src/theme/ayu-highlight.css
Was previously highlighting `#[derive(Clone)]` like it was a comment. This updates the css to match the grouping of other themes.
For an example see https://rust-lang.github.io/async-book/02_execution/04_executor.html. Note the `#[derive(Clone)]` highlighting color in line 7 of the following screenshots
For reference, here is the regular theme:
And here is the ayu theme today:
And here is the ayu theme after the change proposed in this PR:
> fix: ayu theme meta highlighting

- src/renderer/html_handlebars/hbs_renderer.rs
Html page title for every chapter in the book is created by the following code:
```rust
let title: String;
{
let book_title = ctx
.data
.get("book_title")
.and_then(serde_json::Value::as_str)
.unwrap_or("");
title = ch.name.clone() + " - " + book_title;
}
```
If the `book.toml` file is missing, and `book_title` parameter is empty, there's an awkward ` - ` string hanging at the end of each chapter's title.
This PR adds a `match` case to handle that kind of situation.
> Add a case for an empty `book_title` parameter

- src/theme/css/chrome.css
A multiline element (`<p>`, `<li>`, a block of text etc.) has inner space (space between its lines). That space should be smaller than that element's outer margin (distance to another element).
> Corrects inner/outer space in sidebar <li>s

- src/utils/fs.rs
This prevents recursive copy-loops when the destination directory
is contained in the source directory.
Now it bails out with a descriptive error message.
> Assure `copy_files_except_ext(..)` won't copy directories into itself

- Cargo.lock
- Cargo.toml
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/theme.rs
- src/renderer/html_handlebars/helpers/toc.rs
3.0 provides better render performance and I recommend the community to upgrade.
> Update handlebars to 3.0

- src/book/summary.rs
This PR fixes https://github.com/rust-lang/mdBook/issues/1096.
If `SUMMARY` contains comment like below:
```markdown
- [First](./first.md)
- [Second](./second.md)
```
`- [Second]` generate `Event::Start(Tag::List(..))`, but `items` is empty because it is not nested.
The empty can be ignored.
> Fix SUMMARY's parse_numbered with comment

- README.md
I noticed that the CI badge was failing and it seems to be caused by the fact that it reflects the latest build including PRs. This change filters the events to only "push events on the master branch" so the badge stays green even if a PR fails.
> Change CI badge to only push events

- src/book/book.rs
- src/book/summary.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
While porting a [book of mine](https://github.com/mcarton/rust-derivative/tree/master/doc) from GitBook to mdBook, I noticed that anchors are not supported in the SUMMARY file:
For example, given the following summary:
```markdown
- [Foo](Foo.md)
- [Subfoo 1](Foo.md#anchor-1)
- [Subfoo 2](Foo.md#anchor-2)
- [Bar](Bar.md)
```
The following wrong things are going to happen when running `mdbook build`:
- Files `doc/Foo#anchor-1.md` and `doc/Foo#anchor-2.md` are going to be created.
- The navigation panel will only ever highlight "Subfoo 2" whether you click on "Foo", "Subfoo 1" or "Subfoo 2".
- The navigation arrows don't work: the left arrow can't go back, the right arrow points to the last sub-section.
- All 3 links in the `Foo` section point to `Foo.html`, which is empty.
> Support anchors in SUMMARY

- src/theme/book.js
- src/theme/css/general.css
This changes it so that code spans in headers are not highlighted as code, and don't change the font size.
> Don't highlight code spans in headers.

- src/theme/book.js
- src/theme/index.hbs
This is a re-submission of #1068. It changes the side bar so that the current page is in the vertical center instead of the top of the window.  From the previous PR, I removed the onload event handler since it caused some jumping, and it doesn't seem to be necessary.
> Scroll sidebar to middle instead of top.

- src/theme/book.js
When opening the theme selector, it is supposed to set focus on the label of the current theme. However, it was raising an exception because it was using an old (incorrect) way of determining the current theme.
Closes #1151
> Fix theme selector focus.

- src/renderer/html_handlebars/hbs_renderer.rs
At present, code listings without a main function will be wrapped in one and annotated with an allow lint check attribute provided by the following [code][]:
```rust
format!(
"\n# #![allow(unused_variables)]\n{}#fn main() {{\n{}#}}",
attrs, code
)
```
A broader lint check attribute such as `#![allow(unused)]` seems like it might better fit the apparent intent of this code.
Addresses: https://github.com/rust-lang/mdBook/issues/1192
[code]: https://github.com/rust-lang/mdBook/blob/769cc0a7c14fe133fc5eb223f435473730d0086e/src/renderer/html_handlebars/hbs_renderer.rs#L635-L638
> Broaden scope of suppressed warnings for listings without a main fn

- book-example/src/cli/serve.md
- book-example/src/cli/watch.md
This PR is adding documentation of `.gitignore` file use for `watch` and `serve` command exclude patterns when checking for modified files.
It is a follow-up to #1160 and incorporates answer from @ehuss and my observation that global `.gitignore` files are not used.
I confirmed that by checking the code, but feel free to let me know if I've overlooked something.
> Mention that .gitignore is used for watch excludes (#1160)

- book-example/book.toml
- book-example/src/format/config.md
- src/book/mod.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
On #1100.
Made new top-level configuration `[rust]` and moved edition config under it.
cc: @kpp @ehuss
>  Make new [rust] section to config and  place edition under it 

- book-example/src/for_developers/backends.md
- book-example/src/format/config.md
- src/renderer/mod.rs
- tests/alternative_backends.rs
> Fixed zero exit code when plugin not found

- src/preprocess/links.rs
* A simple fix to support `+` in links paths.
* A test for special characters _mdBook_ does support.
This partially solves #1098.
> #1098 Links preprocessor: support pluses

- src/config.rs
[Config::update_from_env](https://github.com/rust-lang/mdBook/blob/master/src/config.rs#L134) says:
```rust
/// > This means, if you so desired, you could override all book metadata
/// > when building the book with something like
/// >
/// > ```text
/// > $ export MDBOOK_BOOK="{'title': 'My Awesome Book', authors: ['Michael-F-Bryan']}"
/// > $ mdbook build
/// > ```
```
This is wrong in two ways:
1. We can't overwrite `book.toml` with `MDBOOK_BOOK`
2. The example value of `MDBOOK_BOOK` is a wrong JSON string (missing/wrong quotes)
So I fixed them so that the example works. But I didn't add any automated test.
> Enable `MDBOOK_BOOK`  to overwrite `book.toml`

- book-example/src/format/theme/README.md
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/head.hbs
- src/theme/index.hbs
- src/theme/mod.rs
Allow to define custom attributes within the HTML <head> tag thanks to a `head.hbs` template file.
A typical use case is the addition of mobile capabilities for PWA deployment for example to render the doc in fullscreen once added to the home screen (Android or iOS):
```html
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="mobile-web-app-capable" content="yes">
```
> HTML head customisation with `head.hbs`

- book-example/src/SUMMARY.md
- book-example/src/format/summary.md
- src/book/book.rs
- src/book/mod.rs
- src/book/summary.rs
- src/preprocess/index.rs
- src/preprocess/links.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/search.rs
- src/renderer/markdown_renderer.rs
According to discussion in PR #1109 I have implemented the "draft chapters" by making the path an option. While it works, it feels a lot dirtier with all the `if let`.
Maybe this version can be improved to remove some of this 'hack' feeling?
I will leave both PRs open so that they can be compared and I leave it to your appreciation which version you want to go with :slightly_smiling_face:
> Bring back draft chapters

- src/theme/book.js
This sets some limits so that the sidebar position cannot be dragged outside of the window.
Closes #1224
> Do not allow the sidebar to be dragged outside the window.

- book-example/src/format/summary.md
- src/book/book.rs
- src/book/mod.rs
- src/book/summary.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/theme/css/general.css
Implements support for breaking the list of chapters in `SUMMARY.md` into parts. This is useful for really long books that (e.g. rustc-dev-guide).
Some notable things:
- I think this makes breaking changes to some public APIs of the `mdbook` crate.
- I did some refactoring on the `SUMMARY.md` parser that I think cleans things up a bit. In particular, I gave the parser the ability to lookahead 1 token, which got rid of some edge cases and prevents every combinator from having to figure out if they are missing their first token. The new convention is that if your combinator discovers it has gone too far, it puts back the last token it read.
Here is a sample of what it looks like:
> implement support for book parts

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/mod.rs
- src/theme/redirect.hbs
- tests/rendered_output.rs
This is a fairly straightforward implementation based on the comments from #430.
Fixes #430, CC #1235.
---
Some potential future work would be allowing the user to configure redirects inline with a `[output.html.redirect]` table in `book.toml` or reading from a `key = value` file discovered by having some sort of `redirect = "redirects.txt"` under the `[output.html]` table. 
This is easy enough to implement in a backwards-compatible way (backwards-compatible for end users, it would require a library change) by swapping the `HashMap<String, String>` for some `RedirectsMap` enum that is either a `HashMap` or ` PathBuf`, and giving the `RedirectsMap` a `load_redirects() -> Result<impl Iterator<Item = (String, String)>, Error>` method.
I've decided to skip that for now, seeing as it's not …
> Implement URL redirecting

- book-example/src/format/config.md
- book-example/src/format/theme/README.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
> Change default preferred-dark-theme to `navy`.

- src/config.rs
- tests/init.rs
#1163 inadvertently added an empty `[rust]` table when running `mdbook init`.
> Fix init creating empty `[rust]` table.

- src/theme/css/general.css
By adding `!important` to `display: none` in `.hidden`, it will prevent Font Awesome's `.fa` class from overriding the `display` property. This fixes #1247
> Fix issue where Font Awesome overrides `.hidden`'s `display: none`

- book-example/book.toml
- book-example/src/404.md
- book-example/src/format/config.md
- src/cmd/serve.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
- src/utils/fs.rs
Prototype spike for a 404 page (cf #539).
This PR generates a 404.html file with sidebar navigation and search intact, to better handle broken or stale links.
Additionally, the builtin server serves this file on 404 errors.
Comments and feedback appreciated!
> Generate 404.html page (#539)

- src/cmd/serve.rs
- src/cmd/watch.rs
- src/renderer/html_handlebars/hbs_renderer.rs
The `--dest-dir` flag was not working correctly for `serve` and `watch`.  `watch` was ignoring it completely.  `serve` was only using it during the first build, then ignoring it afterwards.
Closes #1226
> Fix dest-dir command-line flag.

- Cargo.lock
- Cargo.toml
This allows to prune some of the old transitive dependencies from the
dep tree. In particular, this gets rid of <1.0 syn and related crates.
cc #1211 #1076
> Update select dependency to 0.5

- src/renderer/html_handlebars/helpers/toc.rs
If a summary included section titles, then the automatic scrolling for the sidebar was broken (it was always scrolled to the top of the sidebar).
> Fix sidebar scrolling with part titles.

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/mod.rs
If the user has overridden one favicon format (SVG or PNG), don't copy the default for the other.
Books may override PNG, but not have a convenient SVG version that they want to use.
> Don't copy default favicon if at least one is overridden.

- ci/install-rust.sh
For some reason, on Windows, `rustup update` fails with `/c/Rust/.cargo/bin/rustup: Device or resource busy`. Just skip rustup self-updates for now.
> Fix CI due to new rustup.

- CHANGELOG.md
I think it's worth mentioning in the changelog since it's one of breaking changes even if it was actually unused.
> Mention removed features in the changelog

- src/theme/book.js
In a recent discussion in the amethyst docs discord channel,
it was suggested that using an "eye" icon might make the show hidden
lines feature of mdbook's code sample rendering more discoverable.
I myself overlooked the arrows that are in use now for longer than I'd like to admit.
Fixes #663 at least in part.
Some rendered output from the example book follows:
---
> Change "show hidden lines" icon to "eye" instead of "expand."

- src/book/summary.rs
Summary items that had their name split into two lines ended up with the
last word of one line and the first word of the next line glued
together, since a space wasn't added.
Fixes #1218
> summary: turn SoftBreak events into spaces.

- book-example/src/for_developers/backends.md
- src/renderer/mod.rs
If an uninstalled backend (command not found) isn't marked optional,
warn about it, since it causes mdbook commands to error out.
Fixes #1283
> Mention that uninstalled backend isn't marked optional.

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
A mistake in #1266, I neglected to also update the `<link>` generation
to elide the link if one of the favicon images is not included.
> Fix favicon when only one is overridden.

- src/book/summary.rs
Related issues: #527 #1287 
As stated in [CommonMark Spec](https://spec.commonmark.org/0.28/#link-destination):
> A link destination consists of either
>
> *  a sequence of zero or more characters between an opening `<` and a closing `>` that contains no spaces, line breaks, or unescaped `<` or `>` characters, or
>
> * a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)
and [according to this](https://github.com/Microsoft/vscode/issues/24763) and MDN spec …
> allow space in SUMMARY.md's link destination

- book-example/src/README.md
I could only find the information about which interpretation of markdown was used in the changelog and in some github issues.
I thought it would make sense to make it explicit in the documentation.
> Adds information about markdown flavor in the documentation.

- src/book/mod.rs
I found that iterating on `mdbook` test is fairly slow as any failure in any file halts the process
This prints the error with `error~`, marks a failure, and then moves on
I tested that the return code is 0 on a passing book (i had a working local version of the cargo book) and that its non-0 on a non-passing book (`dummy_book` in `tests` is good for this)
> collect all test failures before failing

- book-example/src/format/config.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
This PR adds a `cname` configuration to \[output.html\] which is rendered into a CNAME file in the root of the generated site as required by GitHub Pages (see [*Managing a custom domain for your GitHub Pages site*](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)).
```toml
[output.html]
cname = "serde.rs"
```
The CNAME file is how GitHub knows which repo's site to serve when someone visits your domain. DNS records only point from domain (serde.rs) to domain (serde-rs.github.io), so the additional information is required to know that serde-rs.github.io/serde (i.e. the Pages site for github.com/serde-rs/serde) is the right repo to serve for that domain.
> Support emitting CNAME file for publishing at a custom domain

- src/renderer/html_handlebars/hbs_renderer.rs
See https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.
Before:
```console
/path/to$  cat book/.nojekyll
This file makes sure that Github Pages doesn't process mdBook's output./path/to$  ▎
```
After:
```console
/path/to$  cat book/.nojekyll
This file makes sure that Github Pages doesn't process mdBook's output.
/path/to$  ▎
```
> End .nojekyll file with newline

- src/renderer/html_handlebars/helpers/toc.rs
Fixes #1308.
However, I'm not necessarily experienced enough with HTML/CSS to know if this is an acceptable solution or if it qualifies as a hack. Or maybe the `<div>` should be given a class? Happy to change this as needed.
> Fix missing space before draft chapter titles

- src/theme/fonts/fonts.css
Fixes #1304.
This prevents an issue with Firefox 80 on macOS that prevents syntax
highlighting from working.
> Prefer bundled version of Source Code Pro

- ci/make-release.sh
There is a bug with BSD tar on macOS where the first 8MB of the file are sometimes all NUL bytes. See https://github.com/actions/cache/issues/403 and https://github.com/rust-lang/cargo/issues/8603 for some more information. An alternative solution here is to install GNU tar, but flushing the disk cache seems to work, too.
> Fix macOS CI deploy.

- src/utils/fs.rs
Currently, the `copy_files` function doesn't support symlink files due to
its use of `DirEntry::metadata` - To avoid this issue, this patch
resolves the file path first before checking for metadata.
Fixes #1157
Fixes #1209
> Resolve full file paths when copying files

- book-example/src/format/config.md
- src/book/init.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
This PR adds a new config option which allows you to disable all "print" support.
```toml
[output.html.print]
enable = false
```
Resolves #1177
> Add config option to disable print html, css, and icon

- src/renderer/html_handlebars/hbs_renderer.rs
I accidentally missed that the logic was reversed in #1169.
> Fix print icon.

- guide/src/SUMMARY.md
- guide/src/format/mdbook.md
- guide/src/format/theme/syntax-highlighting.md
Generated using the technique described in https://github.com/rust-lang/mdBook/issues/1275#issuecomment-655903967.
> List supported Highlight.js languages in guide

- ci/install-hub.sh
The old method of using `::set-env` and `::add-path` have been deprecated, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
> Update deprecated GitHub Actions commands.

- src/book/book.rs
> Handled UTF-8 BOM

- src/preprocess/links.rs
Taken from https://rust-lang.github.io/mdBook/format/mdbook.html#inserting-runnable-rust-files:
```markdown
Here is what a rendered code snippet looks like:
{{#playground example.rs}}
```
<br>
<br>
> Fix stray spacing after #playground code

- src/renderer/html_handlebars/helpers/toc.rs
The previous behavior was inconsistent with the rendering of \<title\> through handlebars, making it impossible to render a matching chapter name in both places.
SUMMARY.md | rendered title | rendered sidebar
---|---|---
`[Vec<T>](vec.md)` | `<title>Vec</title>` ❌ | `<a ...>Vec</a>` ❌
`[Vec&lt;T&gt;](vec.md)` | `<title>Vec&lt;T&gt;</title>` ✔️ | `<a ...>Vec<T></a>` ❌
`[Vec&amp;lt;T&amp;gt;](vec.md)` | `<title>Vec&amp;lt;T&amp;gt;</title>` ❌ | `<a ...>Vec&lt;T&gt;</a>` ✔️
SUMMARY.md | rendered title | rendered sidebar
---|---|---
`[Vec<T>](vec.md)` | `<title>Vec</title>` ❌ | `<a ...>Vec</a>` ❌
`[Vec&lt;T&gt;](vec.md)` | `<title>Vec&lt;T&gt;</title>` ✔️ | `<a ...>Vec&lt;T&gt;</a>` ✔️
`[Vec&amp;lt;T&amp;gt;](vec.md)` | `<title>Vec&amp;lt;T&amp;gt;</title>` ❌ | `<a …
> Escape `<` and `>` in rendered toc to match handlebars' escaping in <title>

- src/config.rs
- tests/init.rs
Without this change it's impossible to setup build parameters through API like that:
```rust
use mdbook::MDBook;
use mdbook::config::Config;
let root_dir = "/path/to/book/root";
let mut cfg = Config::default();
cfg.book.title = Some("My Book".to_string());
cfg.book.authors.push("Michael-F-Bryan".to_string());
cfg.build.build_dir = PathBuf::from("output"); <---------------- we can set it, but it won't be serialized
MDBook::init(root_dir)
.create_gitignore(true)
.with_config(cfg)
.build()
.expect("Book generation failed");
```
> allow to serialize the "build" section

- guide/src/continuous-integration.md
- guide/src/misc/contributors.md
This branch updates the [mdBook](https://rust-lang.github.io/mdBook/index.html) guidance on [Continuous Integration](https://rust-lang.github.io/mdBook/continuous-integration.html) to comply with travis-ci's upcoming use of [dpl v2](https://docs.travis-ci.com/user/deployment-v2).
It also updates it so that it guides the reader on GitHub Pages deployments via the `gh-pages` branch, which is the approach taken with the GitHub repo (I think).
Lastly, it removes the `sudo: false` command as per travis-ci recommendations in this [blog](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
Let me know what you think! 🙂 
I couldn't get the current instructions to work when setting this up for my [training-git](https://github.com/avisionh/training-git) repo, thus I made …
> Docs: CI guide update

- README.md
I developed a preprocessor (see [here](https://github.com/lzanini/mdbook-katex)) pre-rendering LaTex equations to HTML, which I think would be helpful for books with lots of equations. See #651 and #1105.
> Add Katex preprocessor to 3rd Party Plugins

- src/utils/fs.rs
With this pull request, in the case of the example in #1396, the error message will look like this:
```
2020-12-14 15:31:55 [INFO] (mdbook::book): Book building has started
2020-12-14 15:31:55 [INFO] (mdbook::book): Running the html backend
2020-12-14 15:31:55 [ERROR] (mdbook::utils): Error: Rendering failed
2020-12-14 15:31:55 [ERROR] (mdbook::utils):    Caused By: Failed to read "/home/u7693/Workspace/book/src/not-found"
2020-12-14 15:31:55 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```
Fixes #1396
> Show path in the error message (#1396)

- src/book/book.rs
This patch adds more contextual information regarding the file name which failed due an underlying issue.
Before the changes
````
2020-12-05 20:06:01 [ERROR] (mdbook::utils): Error: Unable to create missing chapters
2020-12-05 20:06:01 [ERROR] (mdbook::utils):    Caused By: Permission denied (os error 13)
````
After the changes
```
2020-12-05 20:12:08 [ERROR] (mdbook::utils): Error: Unable to create missing chapters
2020-12-05 20:12:08 [ERROR] (mdbook::utils):    Caused By: Unable to create missing file: /Users/vicky/tmp/issue_testing/sample/src/./chapter_3.md
2020-12-05 20:12:08 [ERROR] (mdbook::utils):    Caused By: Permission denied (os error 13)
```
> Missing chapters Error Reporting: Add file name

- guide/src/format/theme/index-hbs.md
Looking into the code, we can confirm that the implementation is `{{ chapter_title }} - {{ book_title }}` and not `{{ book_title }} - {{ chapter_title }}` as written in the guide:
https://github.com/rust-lang/mdBook/blob/4c951d530d7cf225fcca18d6e9146b28bf8dcf10/src/renderer/html_handlebars/hbs_renderer.rs#L69
> [guide/format/theme/index-hbs] `chapter_title` and `book_title` are inverted

- README.md
With the current description of the command, I was expecting to get a directory named with the project name, but the files were created in the current directory.
I think a more precise description would help first-time users.
> [README] Add optional directory parameter for the init command

- src/book/book.rs
Provides better feedback if user executes in a different folder than what is expected by mdbook
After the changes `mdbook build`
```
2020-12-19 14:27:35 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/Users/vicky/rust/source_codes/mdbook_testing/src/src" directory
2020-12-19 14:27:35 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```
Previously: `mdbook build`
```
2020-12-19 14:28:46 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md
2020-12-19 14:28:46 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```
> Provide useful feedback if user executes command in different folder

- src/renderer/html_handlebars/hbs_renderer.rs
Fix #1404
Now, it works on my build in local.
> fix: readerer get theme dir path bug

- src/renderer/html_handlebars/search.rs
- tests/rendered_output.rs
- tests/searchindex_fixture.json
Currently the search result breadcrumbs only contain the chapter's parents, and not the chapter name itself.
This PR adds the chapter name to the breadcrumbs for improved searchability.
> Add chapter name to search result breadcrumbs

- src/theme/searcher/searcher.js
When clicking on a search result, the page will highlight the search terms.  Pressing escape will remove the highlight.  However, the `?highlight=...` would remain in the URL.  This can be annoying if you want to copy and paste the URL to use elsewhere.  This changes it so that hitting escape will also remove the `?highlight=...` from the URL when hitting escape.
> Remove mark from URL on escape.

- guide/src/continuous-integration.md
> Guide: Add instructions for publishing via GitLab Pages

- src/book/init.rs
- src/cmd/init.rs
- tests/init.rs
A long time ago (#491, #696), the location of themes was changed from `src/theme` to `theme`.  However, `mdbook init --theme` was never updated to place the theme in the new location.  This updates the init command to place the `theme` directory in the root.
This also includes a few minor fixes:
* If the css directory exists, don't fail.
* Don't print the overwrite warning if it isn't actually going to overwrite anything.
Closes #1412
> Change `init --theme` to place theme in root.

- Cargo.lock
- Cargo.toml
This pull request updates the version in [Cargo.toml](https://github.com/rust-lang/mdBook/blob/a76557a678aeded8344acba2f929edb5b5ac8f3e/Cargo.toml#L3) from 0.4.4 to 0.4.5, so that it matches to the one published to crate.io.
**Problem Description**
v0.4.5 has been published to crates.io, but Cargo.toml in this repository left unchanged as 0.4.4.
```console
$ git clone git@github.com:rust-lang-ja/mdBook.git
$ cd mdBook/
$ git show  
commit 09e7bb76dc1d1f565a0678a9f8d3caa0164631cb (HEAD -> master, origin/master, origin/HEAD)
Author: ...
Date:   Tue Jan 5 10:31:16 2021 -0800
$ cargo run -- --version
...
mdbook v0.4.4    # <== Wrong version. Should be v0.4.5
$ rg 'version =' Cargo.toml | head -1
version = "0.4.4"
```
The one published to crate.io has the correct version.
```console
$ curl -L …
```
> Fix a wrong version 0.4.4 in Cargo.toml (Should be 0.4.5)

- src/book/book.rs
- src/book/init.rs
- src/book/mod.rs
- src/config.rs
- src/lib.rs
- src/renderer/mod.rs
Also fixes some punctuation and changes some wording.
> Add intra-docs links to docs

- src/renderer/mod.rs
- tests/alternative_backends.rs
Custom renderers that explicitly set the `command` to a relative path was using the wrong base path.  On Windows, it was relative to the current directory, and on Unix it was relative to the renderer output directory (see https://github.com/rust-lang/rust/issues/37868 for this unfortunate behavior). Neither are correct, they should be relative to the book root.  This changes it so that it is relative to the book root, and has a legacy warning for the old behavior of relative to the output directory.  This uses absolute paths to avoid problems with `current_dir()`.
> Fix relative paths for renderer commands.

- src/theme/searcher/searcher.js
If you click on a search result after entering multiple words, the target page will not have any highlighting.  The marking code was not unescaping the highlight words, thus the split on space doesn't work.
> Fix search highlighting with multiple words.

- Cargo.lock
- Cargo.toml
This upgrades the [shlex](https://docs.rs/shlex) dependency from version 0.1 to 1. The breaking change in shlex 1 is a fix for [a correctness bug](https://github.com/comex/rust-shlex/issues/6). I haven't looked closely at how shlex is used in mdbook so it should probably be made sure that this doesn't break anything that relied on the incorrect behavior.
> Upgrade to shlex 1

- src/theme/css/chrome.css
- src/theme/css/variables.css
- src/theme/highlight.css
This PR aims to address #1442, and is a refinement of PR #1353 based on feedback there, and also on the WebAIM mailing list, in the replies to this post:
https://webaim.org/discussion/mail_message?id=45812
Principle differences from earlier revisions posted in #1353 are:
- The new colour scheme is now applied directly to the default `light` theme (instead of a separate and new `contrast` theme).
- The scroll bars are now slightly lower contrast (to make them less visually distracting/imposing, while still complying with WCAG v2.1).
- A subtle change to the syntax highlight text colours, to perform better on devices which have their "blue light filter" activated.
- The size of the title text (rendered at the top-centre of each page) is now 20% larger (this *doesn't* make the title bar …
> Enhance text contrast of `light` theme to improve accessibility.

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/css/general.css
- tests/rendered_output.rs
This fixes some issues with how `#` fragment scrolling works, and how headers are highlighted:
* h5 and h6 now show a chevron to the side.
* All `:target` elements now scroll into view with a top margin so that they aren't covered by the menu bar. This affected anything that wasn't h1-h4 (like h5, h6, footnotes, custom anchors, etc.).  I didn't see an obvious reason to restrict this to just header tags, so it now selects all `:target` elements.
Note that the margin scrolling does not work on Safari, but has been fixed in Technology Preview 117 (which I think is Safari 14.2).  This required moving the `id` from the `<a>` tag to the header tag, which I think should be fine (Safari didn't seem to like id's on `<a>` tags).
Fixes #1198
Fixes #1357
> Fix some issues with fragment scrolling and linking.

- guide/src/format/example.rs
- guide/src/format/mdbook.md
The examples with hidden lines have been updated to have the correct indent now.
> Update examples with hidden lines

- guide/src/format/mdbook.md
- src/book/mod.rs
- src/preprocess/links.rs
- src/preprocess/mod.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/mod.rs
This PR makes it possible for a chapter to have a page \<title\> that is different from its entry in the TOC.
I have my own usage for this, but here is an example from https://doc.rust-lang.org/1.47.0/book/appendix-01-keywords.html:
---
---
It's reasonable for the appendices to be lettered A, B, C in the sidebar, but "A - Keywords" does not serve as a good webpage title. They'd likely want either "Keywords" as the title, or "Appendix A: Keywords" matching the h1 of the page. At the same time they likely *wouldn't* want "Appendix A: Keywords" in the sidebar due to very limited horizontal space.
*SUMMARY.md:*
```markdown
...
- [Appendix](appendix-00.md)
- [A - Keywords](appendix-01-keywords.md)
```
*appendix-01-keywords.md:*
```markdown
{{#title Keywords}}
```
> Add page title override: {{#title My Title}}

- src/book/summary.rs
This pull request changes mdBook 0.4.x to skip any HTML node (such as HTML comment) in `SUMMARY.md`.
Here is an example [`SUMMARY.md`](https://raw.githubusercontent.com/rust-lang-ja/book-ja/3cdfb484693765c4386ad1a227f741e66a7b924b/src/SUMMARY.md) from [rust-lang-ja/book-ja](https://github.com/rust-lang-ja/book-ja) repository. This repository is for a Japanese translation of "The Rust Programming Language" book.
```markdown
1: 
4: # Rustプログラミング言語
5:
6: 
11: [The Rust Programming Language 日本語版](title-page.md)
12: [まえがき](foreword.md)
13: [導入](ch00-00-introduction.md)
14:
15: 
18: ## 事始め
19: 
20: 
26: - [事始め](ch01-00-getting-started.md)
27:     - [インストール](ch01-01-installation.md)
...
```
(We are keeping the original English texts in HTML comments to track future updates in the original) …
> Skip HTML nodes in SUMMARY.md

- guide/src/cli/serve.md
The guide's `serve.md` contains out of date command line option docs. This PR brings it inline with the current state of the command.
Fixes #1524.
> Update serve documentation in the guide

- guide/src/format/config.md
> Fix a small typo

- guide/src/format/summary.md
Mostly structural and language updates to the guide's `summary.md` chapter: 
* Simplified and clarified language here and there
* Fixed a few minor typos
* Made all possible elements a part of the numbered list
* Added examples for elements that didn't have one 
* Include the guide's `SUMMARY.md` at the end as a complete example
> Guide updates: summary.md

- src/preprocess/cmd.rs
Error messages before and after the changes
2021-05-05 18:48:39 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'nn', src/main.rs:53:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-05-05 18:48:39 [ERROR] (mdbook::utils): Error: The preprocessor exited unsuccessfully
2021-05-05 18:50:53 [INFO] (mdbook::book): Book building has started
2021-05-05 18:50:53 [ERROR] (mdbook::utils): Error: Unable to parse the preprocessed book
2021-05-05 18:50:53 [ERROR] (mdbook::utils):    Caused By: expected value at line 1 column 1
2021-05-08 12:44:54 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'ddd', src/main.rs:50:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-05-08 12:44:54 …
> Add useful messages when command line preprocessor fails

- src/theme/css/general.css
Since videos are essentially animated images, this same max width makes sense for both.
> Apply max width to video as well as images

- src/config.rs
Prior to this change, any type errors parsing the `book`, `rust` or `build` sections of the `book.toml` would be silently ignored and the default for the given section would be used instead. 
This change adds an explicit check when parsing the above sections, and if an error is encountered, the error is reported rather than using the default configuration. For example, if the value of `language` in `[book]` is a list rather than a string:
```toml
[book]
language = ["en", "pt-br"]
```
The result will be something like: 
```bash
❯ mdbook build                         
2021-05-19 10:16:43 [ERROR] (mdbook::utils): Error: Invalid configuration file
2021-05-19 10:16:43 [ERROR] (mdbook::utils):    Caused By: invalid type: sequence, expected a string for key `language`
```
Fixes #1522.
> Report book.toml parse error when invalid fields are found

- guide/src/cli/build.md
- guide/src/cli/serve.md
- guide/src/cli/watch.md
> Mention missing file creation in build/watch/serve's docs

- src/cmd/serve.rs
`mdbook serve` starts the warp server in a thread and then continues on to watch for changes. However, if the thread panics, for example, because the address is already in use, `mdbook` doesn't exit. 
This change will explicitly call `std::process::exit(1)` from the thread if `warp::serve` panics.
Fixes #1545.
> Use std::panic::set_hook to exit serve thread if serving fails

- src/cmd/watch.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
Fixes all instances of `warning: writing `&PathBuf` instead of `&Path` involves a new object where a slice will do`
> clippy: PathBuf to Path fixes.

- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
The "Suggest an edit" URL used `src` as the top level path to the file to edit regardless of whether the book.toml `src` config was set resulting in an incorrect link to the file. This change uses the actual configured `src` to build the path instead.
Fixes #1543.
> Use the configured book src directory for the edit url template path

- guide/src/format/summary.md
The markdown list markers in a list in the `SUMMARY.md` must be of the same type to avoid creating a new list, which results in the remaining list items not being rendered. This should arguably produce an error or be handled in some other way, but in lieu of that, here is some documentation. 
This clarifies the issue seen in #1517.
> Documentation clarification on markdown list markers

- src/book/book.rs
This reverts commit c1b2bec7d7a56909f695f103d316453dab68798e due to a breaking change. 
Fixes #1571. 
See #1557.
> Revert "book: use non_exhaustive attribute for struct Book"

- guide/src/format/mdbook.md
In the bash version, `y` have value 6, while rust version it has value 7
> Fix inconsistent between bash version and rust version of the sample

- guide/src/format/configuration/general.md
- src/book/mod.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
Updates to include the upcoming 2021 edition. 
Fixes #1593.
> Rust Edition 2021 Support

- src/main.rs
Usual usage is something like 
```bash
mdbook completions bash > /path/to/completion/file/mdbook
```
where the shell is configured to load completions from that location.
Another possibility is to have the `completions` subcommand hidden by default, since it won't be as commonly used as the others/
> Add ability to generate shell completions via clap

- guide/src/continuous-integration.md
Inputting paths are not necessary and will break ci, we can just leave paths out. We also changed 'master' to main since anyone reading this is probably going to be making mains
> MyPaths are not required and fail

- guide/src/cli/init.md
- src/cmd/init.rs
Adds two new flags to `mdbook init`; `--title` and `--gitignore`.
These flags optionally replace the two currently interactive prompts so that a book can be initialized without any prompts if desired. 
See #1556.
> Add --title option and --gitignore flag to mdbook init

- src/theme/book.js
Don't highlight `inline code` blocks in headers with output.html. playpen(playgroud).editable=true
Fixes #1580
> Don't highlight `inline code` blocks in headers with output.html. playpen(playgroud).editable=true

- README.md
- guide/src/for_developers/backends.md
This PR adds links to a new backend that I'm working on: [mdbook-man](https://github.com/vv9k/mdbook-man). It generates manual pages from the book that can later be viewed with tools like `man`.
> Add information about a new backend `mdbook-man`

- guide/src/for_developers/preprocessors.md
This is the starting point at an attempt to make the documentation more clearer to those who would like to implement a preprocessor but are stuck on how to.
I am sure this change is far from perfect, so I'd love to have advice on how it could be structured better.
Additionally, I was wondering whether the code shown should be moved in a file of it's own.
This should fix #1462 and resolve #975 
Thanks.
> Improving documentation on implementation of preprocessors.

- Cargo.lock
- Cargo.toml
- tests/cli.rs
- tests/cli/build.rs
- tests/cli/mod.rs
- tests/cli/test.rs
- tests/cli_tests.rs
> Add CLI tests

- Cargo.lock
- Cargo.toml
- guide/src/format/configuration/preprocessors.md
- src/book/mod.rs
> Allow specifying preprocessor order

- guide/src/continuous-integration.md
Replace 'only' with 'rules'.
'only' is not actively developed anymore with GitLab (see https://docs.gitlab.com/ee/ci/yaml/#only--except)
+ Minor formatting changes.
> Documentation: CI: GitLab Pages Example

- src/utils/mod.rs
Fixes https://github.com/rust-lang/mdBook/issues/1053
This strips HTML tags before generating anchor IDs.
> Strip HTML tags from anchor IDs

- src/theme/css/general.css
closes #1684
Text gets bigger on landscape orientation.
Text keeps same size with portrait orientation.
- https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust#basic_disabling_usage
- https://trac.webkit.org/changeset/261940/webkit
> Prevent iOS Safari from enlarging text in landscape orientation

- guide/src/format/configuration/renderers.md
- src/book/mod.rs
This puts a deprecation notice for the `output.html.google-analytics` field, with the intent to remove it in the 0.5 release. The current code has been outdated for a while, and doesn't provide very much flexibility.  I also prefer not to endorse any particular service, instead letting the user pick whichever they want.  Placing the code in the `<head>` tag is the recommended approach, and the `head.hbs` extension provides a means to do so.
Closes #1635
> Deprecate google-analytics

- Cargo.lock
- Cargo.toml
There no need to pull arg parsing crate
> don't use additional features for pulldown-cmark

- Cargo.lock
- Cargo.toml
The API involved in the example is the following, none of which has changed between 0.11 and 1.0.
https://github.com/rust-lang/mdBook/blob/336640633b1741de644e971a1a2cd8b30c595368/examples/nop-preprocessor.rs#L6
https://github.com/rust-lang/mdBook/blob/336640633b1741de644e971a1a2cd8b30c595368/examples/nop-preprocessor.rs#L37-L40
> Update semver dev-dependency in nop-preprocessor example to 1.0

- guide/src/format/configuration/renderers.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
As discussed in #1190, the option to disable page-breaks between chapters is useful for some specific use-cases. I use mdBook for printable cheat sheets, and therefore want to keep the printable version as compact as possible.
> Make page-break configurable

- guide/src/for_developers/preprocessors.md
> style: add missing word

- guide/src/format/configuration/renderers.md
- guide/src/format/mdbook.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
This PR is for #747.
This adds a flag to the config that toggles the run button on codeblocks.
In `book.toml` you can write like below to disable all run buttons on codeblocks.
```toml
[output.html.playground]
runnable = false
```
> Config to toggle the run button on codeblocks

- src/book/summary.rs
Resolves #1743
The issue can be found while looking and summary parsing output:
```markdown
#
- [First](./first.md)
- [Nested](./nested.md)
- [Second](./second.md)
```
```
RUST_LOG=mdbook::book::summary=TRACE cargo run -- build
```
```
2022-02-11 11:52:10 [TRACE] (mdbook::book::summary): Next event: Some(Start(Heading(H1, None, [])))
2022-02-11 11:52:10 [DEBUG] (mdbook::book::summary): Found a h1 in the SUMMARY
2022-02-11 11:52:10 [TRACE] (mdbook::book::summary): Next event: Some(End(Heading(H1, None, [])))
2022-02-11 11:52:10 [DEBUG] (mdbook::book::summary): Parsing prefix items
2022-02-11 11:52:10 [TRACE] (mdbook::book::summary): Next event: Some(Start(List(None)))
2022-02-11 11:52:10 [TRACE] (mdbook::book::summary): Back: Start(List(None))
2022-02-11 11:52:10 [TRACE] …
```
> Fix `SummaryParser::parse_title()` consuming events (#1743)

- src/cmd/serve.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/index.hbs
livereload uses host&port of current page; livereload works with a HTTPS site
Closes #1698
> livereload uses host, port and HTTP(S) protocol of current page

- src/renderer/html_handlebars/hbs_renderer.rs
This adds `Page not found` title to the 404 page.
Closes #1692
> Add proper title to 404 page

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- examples/nop-preprocessor.rs
- guide/src/guide/installation.md
- src/cmd/build.rs
- src/cmd/clean.rs
- src/cmd/init.rs
- src/cmd/serve.rs
- src/cmd/test.rs
- src/cmd/watch.rs
- src/main.rs
This includes resolving the deprecation warnings, one warning per commit.  This was a fairly straightforward conversion, sticking to simpler parts of clap.  `App::arg_from_usage` was probably the most involved.  The replacement, `arg!()`, doesn't seem to support kebab-case in value names.
I tested by
- Adding the `App::debug_assert()` test
- Inspecting before/after of `--help` for each subcommand
I'm assuming there is some end-to-end tests to at least catch egregious cases.
Differences I noticed (all cosmetic)
- Colored help is now on all subcommands (`ColoredHelp` was set only on the parent before rather than with `global_setting`, now its the default)
- Combining of the Flags and Options sections (`UnifiedHelpMessage` is now the only behavior)
- Some spacing is slightly different so …
> Port mdBook to clap3

- src/config.rs
If the `[output.html.print]` config was used to set the enable flag, the config would fail to load due to the new page-break option which wasn't correctly set with a default.  This fixes it so that the config can load correctly.
Fixes #1774
> Fix html print config default.

- tests/cli/build.rs
- tests/cli/cmd.rs
- tests/cli/mod.rs
- tests/cli/test.rs
nixpkgs build system sets `RUST_LOG=` (empty value) by default.
This switches `mdBook` into warnings+ mode (instead of info+).
This causes the following tests to fail:
$ RUST_LOG= cargo test --test cli_tests
...
cli::test::mdbook_cli_can_correctly_test_a_passing_book
cli::test::mdbook_cli_detects_book_with_failing_tests
cli::build::mdbook_cli_dummy_book_generates_index_html
The change drops RUST_LOG= entry.
> tests/cli: ignore user's RUST_LOG= environment variable in tests

- guide/src/guide/creating.md
Hi, first-time contributor here 👋 
I noticed that there was a typo within the [Publishing A Book](https://rust-lang.github.io/mdBook/guide/creating.html#publishing-a-book) section of the mdBook User Guide and decided that it would be an easy fix! This commit fixes the typo `mbdook` to `mdbook`
Hope that this is okay!
> User Guide: Fix typo 'mbdook' to 'mdbook'

- src/book/book.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/utils/mod.rs
- tests/dummy_book/summary-formatting/SUMMARY.md
- tests/rendered_output.rs
Links in SUMMARY.md can have trouble rendering correctly if they include any sort of markdown elements. A particular example this tries to fix is escaping of asterisks like `[\*foo\*]`. Previously, the summary parser would strip out all the markdown formatting, and then the TOC renderer would then try to re-render the now stripped chapter name.  With escaped asterisks, the escaping is removed, leaving italics to be rendered.
It looks like long ago it was intended this was to handle `code` blocks in summary names. However, that hasn't worked for a long time.
There was some discussion in #70 about how this should work, and whether or not code blocks should be rendered. Properly rendering the link name with things like `code` blocks is a difficult problem, so I'm punting on that for now. The …
> Don't try to render summary links as markdown.

- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
This PR fixes #1756.
With the following config,
```toml
#book.toml
[output.html]
theme = "./xxx"
```
if `./xxx` directory does not exist, an error message will be logged:
```log
#log
2022-04-25 02:19:12 [INFO] (mdbook::book): Book building has started
2022-04-25 02:19:12 [INFO] (mdbook::book): Running the html backend
2022-04-25 02:19:12 [ERROR] (mdbook::config): theme dir "./xxx" does not exist
2022-04-25 02:19:12 [INFO] (mdbook::cmd::serve): Serving on: http://localhost:3000
2022-04-25 02:19:12 [INFO] (warp::server): Server::run; addr=127.0.0.1:3000
2022-04-25 02:19:12 [INFO] (warp::server): listening on http://127.0.0.1:3000 
2022-04-25 02:19:12 [ERROR] (mdbook::config): theme dir "./xxx" does not exist
2022-04-25 02:19:12 [INFO] (mdbook::cmd::watch): Listening for changes...
```
> bail! in render() if specified theme directory does not exist

- src/renderer/html_handlebars/hbs_renderer.rs
This reduces total allocated bytes (tracked by DHAT) for `mdbook build`. For example, for [`rustbook`](https://github.com/rust-lang/book) from ~663mb to ~548mb
> init regexes via lazy_static

- Cargo.lock
- Cargo.toml
I plan to release elasticlunr-rs 3.0.0 soon. None of the API changes affect mdBook.
Just checking that CI passes for now.
> Update to elasticlunr-rs 3.0.0

- src/renderer/html_handlebars/search.rs
- tests/dummy_book/src/first/no-headers.md
- tests/rendered_output.rs
- tests/searchindex_fixture.json
Reverts rust-lang/mdBook#1809
This seems to have somehow broken the CI even though the CI passed on the pr, time to investigate
> Revert "Omit words longer than 80 characters from the search index"

- Cargo.lock
- Cargo.toml
This updates `warp` to the latest release, which happens to fix #1797 by making HEAD requests automatically part of `warp::fs::dir` routes:
With warp 0.3.1:
```
$ curl --head localhost:3000/index.html
HTTP/1.1 404 Not Found
content-length: 14598
content-type: text/html
accept-ranges: bytes
last-modified: Mon, 20 Jun 2022 18:53:48 GMT
date: Mon, 20 Jun 2022 18:53:52 GMT
```
With warp 0.3.2:
```
$ curl --head localhost:3000/index.html
HTTP/1.1 200 OK
content-length: 17487
content-type: text/html
accept-ranges: bytes
last-modified: Mon, 20 Jun 2022 18:56:24 GMT
date: Mon, 20 Jun 2022 18:56:28 GMT
```
See https://github.com/seanmonstar/warp/blob/master/CHANGELOG.md#v032-november-9-2021
> Update warp to 0.3.2

- src/theme/css/general.css
- src/utils/mod.rs
This PR fixes long inline code doing an x overflow.
There's another x-overflow on this page, where the table with the heading  "punycode + encoding" also overflows slightly. I have fixed this one as well.
Spotted on
https://rust-lang.github.io/rfcs/2603-rust-symbol-name-mangling-v0.html
> Fix some x overflows

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/ayu-highlight.css
- src/theme/css/chrome.css
- src/theme/css/general.css
- src/theme/highlight.css
- src/theme/tomorrow-night.css
This changes it so that code buttons will appear on hover (similar to how many other sites like GitHub do it). This also has various tweaks to the overall spacing to give some more breathing room.
For implicit main, it no longer adds a blank line at top.
Closes #1322
Closes #1433
> Make code buttons appear on hover (or tap on mobile)

- src/renderer/html_handlebars/search.rs
- tests/dummy_book/src/first/no-headers.md
- tests/rendered_output.rs
- tests/searchindex_fixture.json
This is an updated version of PR #1809, fixed to work with `elasticlunr-rs` v3.
It fixes #1735 .
> Omit words longer than 80 characters from the search index

- src/book/mod.rs
- src/cmd/init.rs
- src/config.rs
- src/lib.rs
- src/preprocess/links.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/renderer/html_handlebars/search.rs
- src/utils/string.rs
Also remove `#[allow(clippy::*)]`s where possible
> Fix Clippy lints

- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/toc.rs
- tests/dummy_book/index_html_test/SUMMARY.md
- tests/dummy_book/index_html_test/chapter_1.md
- tests/rendered_output.rs
- Fixes #1814 by only marking the first non-draft chapter as the "index" page, and adds a test for that
- Makes the link to the first chapter active in the "index" page, improving consistency (and making the aforementioned test pass without hacks)
Additionally, I would've liked to document that "index page" functionality, but I couldn't find any place for it in the documentation.
> Fix up "index page" functionality

- src/cmd/build.rs
- src/cmd/serve.rs
- src/cmd/watch.rs
- src/main.rs
This fixes an issue where `mdbook serve --open` may land on a 404 page if the file name is changed. This is easily reproduced by running `mdbook serve --open guide` on mdBook itself, which will open `http://localhost:3000/README.html`, which 404's thanks to the `index` preproc.
Since mdBook seems to always generate an `index.html` page for the first chapter anyway, it seems that "trimming the fat" is also more correct.
> Always open index page with `serve --open`

- Cargo.lock
I skipped one of the publishing steps.
Fixes #1839
> Fix Cargo.lock for version bump.

- src/book/book.rs
- src/preprocess/mod.rs
- src/renderer/mod.rs
As stated in #1835, I deleted every non_exhaustive members and added the `#[non_exhaustive]` attribute.  
There are two more structs that may benefit from this: the Chapter struct and the Theme struct. The remaining structs have either a private member either all public members and doesn't deserve the attribute (to my opinion).
I could have put this attribute to enums as well, but this and adding attribute to the two structs above would be a breaking change. [The page reference for non_exhaustive attribute](https://doc.rust-lang.org/reference/attributes/type_system.html). So I let this up to review.
> remove __non_exhaustive members, add non_exhaustive attribute instead

- src/book/book.rs
- src/preprocess/mod.rs
- src/renderer/mod.rs
Reverts rust-lang/mdBook#1848
Fixing a breaking change looks like #1571
> Revert "remove __non_exhaustive members, add non_exhaustive attribute instead"

- guide/src/format/configuration/general.md
It looks like this was the only place author was used in the user guide.
Closes #1804
> authors -> author in user guide

- src/theme/css/chrome.css
In #1806, extra padding was added to code blocks, but this adds the padding to headings as well. I think this was only meant to affect code blocks in the main content. If spacing was intended in the headings, a margin would probably be better. This PR just limits the scope of the change from #1806.
With this PR:
> Fix code padding in headings

- src/renderer/html_handlebars/helpers/navigation.rs
Surprisingly, this fixes the error filed at #1860!
This seems suspicious, perhaps indicative of a bug in Rust's non-lexical
lifetime handling on nightly?
The lifetimes in the `handlebars::Renderable::render` method signature
are quite complicated, and its unclear to me whether or not Rust is
catching some new safety edge-case that wasn't previously handled
correctly...
Possibly related to `drop` order, which I *think* is related to the
order of binding statements?
> Workaround rust nightly borrowcheck error (#1860)

- src/renderer/html_handlebars/hbs_renderer.rs
Before, a code block would always end with a final newline. The newline was added unconditionally by `hide_lines`.
When the code block is syntax highlighted by highlight.js, this is not a problem, no empty line is added for a final trailing `\n` character. However, when the code block is editable and thus handled by the ACE editor, a trailing newline _is_ significant. I believe this issue is most closely described by https://github.com/ajaxorg/ace/issues/2083 in the upstream repository.
The effect of the way ACE handles newlines is that a code block like
<pre>
Some code
</pre>
will create an editor with _two_ lines, not just one.
By trimming trailing whitespace, we ensure that we don’t accidentally create more lines in the ACE editor than necessary.
> Avoid empty last line in editable code blocks

- guide/src/format/configuration/renderers.md
I made the mistake of using root relative links: `/assets/some-file.jpg` instead of using document relative links: `assets/some-file.jpg`. This works fine when using `mdbook serve`, but after deploying my pages, the images broke down. A warning notice in the docs might prevent others from making the same mistake.
> Explain how to use `site-url` with asset URLs

- src/theme/index.hbs
I saw it when working https://github.com/rust-lang/rust/pull/101166: the default value of the `type` attribute of `<script>` is `text/javascript`, so no need to set it manually.
> Remove unneeded `type` attribute for `<script>`

- .github/workflows/main.yml
- Cargo.toml
- src/book/book.rs
- src/book/init.rs
- src/book/mod.rs
- src/book/summary.rs
- src/config.rs
- src/lib.rs
- src/preprocess/cmd.rs
- src/preprocess/index.rs
- src/preprocess/links.rs
- src/preprocess/mod.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/theme.rs
- src/renderer/html_handlebars/search.rs
- src/renderer/markdown_renderer.rs
- src/renderer/mod.rs
- src/theme/mod.rs
- src/utils/fs.rs
- src/utils/mod.rs
- src/utils/string.rs
This allows us to clean up and simplify the code.
The changes were originally written by @Dylan-DPC in #1831. This PR fixes a few build errors in that PR, thanks to the helpful comments made by @ISSOtm. I've also rebased the changes onto the latest `master`.
> Require Rust 2021 edition

- src/cmd/serve.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/toc.rs
I found a few places where `Option::and_then` could be simplified (in my opinion) with `?` or with `match`.
> Simplify the use of `Option::and_then`

- .github/workflows/main.yml
- Cargo.toml
- examples/nop-preprocessor.rs
This PR adds test code to the nop-preprocessor example.
If you have better test data or test methods, I would appreciate your suggestions.
The purpose of this PR is showing preprocessor developers what the interface (input) data looks like and how to test the preprocessing results.  Currently, the documentation states that JSON data consisting of a two-element array `[context, book]` is passed from the mdbook, but developers need to actually dump the input themselves to get the actual input data.
Since this PR hard-codes an example of current interface data, it is necessary to keep up with the changes if the interface JSON format changes in the future.
This may not be the best solution to compatibility testing (#1574), but it may be part of it.
> Add test code to show preprocessor developers what the interface data looks like

- src/theme/css/general.css
- src/theme/css/variables.css
- test_book/src/individual/mixed.md
Allows for special styles to call them out since they're different than normal text and different than code. They can make use of styles they inherit for font style and weight.
Notes on changes:
- Added new CSS variables for reused elements
- The font-* rules are separate for each aspect so that they can inherit bold/italic/etc
- I picked the color vars based on what looks good, not necessarily based on logical name reuse
Closes https://github.com/rust-lang/mdBook/issues/1813
And here's how it looks in a list with bold styles applied:
> Add styles for <kbd> elements

- .github/workflows/deploy.yml
- ci/install-rust.sh
- ci/make-release.sh
Added functionality to `.github/workflows/deploy.yml` and associated scripts to deploy pre-built binaries for `x86_64-unknown-linux-musl` and `aarch64-unknown-linux-musl`.
The `x86_64-unknown-linux-musl` executable is statically linked, so it will work with older versions of glibc or the Alpine Linux container environment.
I also added the `aarch64-unknown-linux-musl` executable because I want mdBook to run in aarch64 Linux environments (using rust-lld as the linker makes cross-compilation easier).
This fixes #1779
> Deploy {x86_64,aarch64}-unknown-linux-musl binary

- guide/src/format/configuration/general.md
- src/cmd/watch.rs
- src/config.rs
- tests/init.rs
When using mdBook preprocessors like [mdbook-quiz](https://github.com/willcrichton/mdbook-quiz), the book depends on files outside the source directory, such as TOML files describing quizzes. It would be very convenient as an author for the book to automatically rebuild when these files change. However, the `watch` and `serve` commands (via `trigger_on_change`) only watch a fixed set of directories.
Probably the ideal solution would be for preprocessors to register files to be watched, similar to how extensible build systems like [esbuild](https://esbuild.github.io/plugins/#on-resolve-results) manage plugins. However, this would be a big change with a lot of work. A much cheaper solution is to allow mdbook CLI users to pass desired directories-to-watch on the command line.
Therefore this …
> Add support for watching additional directories

- src/theme/index.hbs
- src/theme/redirect.hbs
Four minor changes to the templates to improve HTML5 conformance. Here is the commit log
```
State canonical URL using <link> not <meta>.
The Google SEO docs describe using the link element to specify the canonical
page in a redirect. They don't mention anything about <meta>.
----
Fix formatting of content attr in <meta http-equiv=refresh>
According to the HTML specification[1], there needs to be a space after the
semicolon and the URL must be unquoted.
[1]: https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-refresh
----
Don't generate obsolete charset attrs in <script>.
According to the HTML specification[1], the charset attribute is obsolete in
script elements.
[1]: https://html.spec.whatwg.org/multipage/obsolete.html#HTMLScriptElement-partial
----
Don't generate …
```
> Better HTML5 conformance

- Cargo.toml
Currently, the documentation link is specified in `Cargo.toml` as:
```
documentation = "http://rust-lang.github.io/mdBook/index.html"
```
which propagates to [crates.io](https://crates.io/crates/mdbook), and if users click on the docs link there they get the non-TLS version. Not likely to cause major issues, but still best practice to use the HTTPS version since it's there
> Update docs link in Cargo.toml to HTTPS version

- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
- src/theme/css/chrome.css
- src/theme/index.hbs
This updates the theme picker to show the currently selected theme.  It removes the "default" display, which wasn't really accurate with regards to preferred-dark themes. This also fixes a rendering bug with the rounded corners.
Before:
After:
> Show the currently selected theme

- src/theme/book.js
Removes `Array` class ref as it's needed and was a mistake 
Closes #1945
> fix: random `Array` ref in `src/theme/book.js`

- Cargo.lock
- Cargo.toml
- src/cmd/watch.rs
Update assert_cmd from 1.0.8 to 2.0.7 https://github.com/assert-rs/assert_cmd/blob/master/CHANGELOG.md#207---2022-12-02
Update env_logger from 0.9.3 to 0.10.0 https://github.com/rust-cli/env_logger/blob/main/CHANGELOG.md#0100---2022-11-24
Update select from 0.5.0 to 0.6.0 https://github.com/utkarshkukreti/select.rs/compare/0.5.0...0.6.0
Update topological-sort from 0.1.0 to 0.2.2 https://github.com/gifnksm/topological-sort-rs/compare/v0.1.0...v0.2.2
Update notify from 4.0.17 to 5.0.0 https://github.com/notify-rs/notify/blob/main/UPGRADING_V4_TO_V5.md https://github.com/notify-rs/notify/blob/main/CHANGELOG.md#notify-500-2022-08-28
> Update dependencies with semver major changes

- Cargo.lock
- Cargo.toml
- examples/nop-preprocessor.rs
- src/book/mod.rs
- src/cmd/build.rs
- src/cmd/clean.rs
- src/cmd/command_prelude.rs
- src/cmd/init.rs
- src/cmd/mod.rs
- src/cmd/serve.rs
- src/cmd/test.rs
- src/cmd/watch.rs
- src/main.rs
This updates clap and clap_complete from version 3 to version 4.
> Upgrade clap

- .github/workflows/deploy.yml
- .github/workflows/main.yml
This switches from 22.04 to 20.04 in order to keep the precompiled binaries compatible with older versions of linux due to glibc version errors.
Fixes #1954
> Switch to older ubuntu image

- src/cmd/test.rs
This fixes the situation of `mdbook test -L deps path-to-book`. clap3 seemed to used to ignore `multiple_values` if there was an optional positional argument (but only if one argument passed to `-L`). clap4 was instead ignoring the positional `path-to-book` argument. This fixes it by removing the "multiple values" altogether. I can't find a situation in clap3 where space-separated values actually worked. 
In my testing, the following cases are the same with clap3 and with this PR:
Allowed:
```
mdbook test -L deps
mdbook test -L deps1,deps2
mdbook test -L deps1 -L deps2
mdbook test -L deps path-to-book
mdbook test path-to-book -L deps
```
Not allowed
```
mdbook test -L deps1 deps2 path-to-book
mdbook test docs -L deps1 deps2
mdbook test -L deps1 deps2 -d output
mdbook test -L deps1 deps2 …
```
> Fix test with multiple library paths

- guide/src/format/configuration/environment-variables.md
This fixes the example to use correct JSON syntax.
Fixes #1966
> Fix MDBOOK_BOOK environment variable example

- src/theme/css/chrome.css
This PR thins scrollbars in Chrome and Safari to make them less assertive.
This is part of #1483, but may not completely close the issue since this does not hide the scrollbars when unused.
I will appreciate your feedback!
Many thanks.
> Use default scrollbars on webkit browsers

- Cargo.lock
- Cargo.toml
Now mdbook depend to time 0.1.44 which has CVE-2020-26235.
By adjusting feature, the dependency can be removed.
> Remove dependency to time 0.1.44

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/question.yml
The `version` command does not exist, but clap defines a default flag `--version` or `-V`.
> Fix incorrect version command

- src/theme/css/chrome.css
- src/theme/index.hbs
The browsers on mobile devices ignore the `overflow-x: hidden` within the body tag if `<meta name="viewport">` tag is present. The fix is to add a container inside the body tag that contains everything the body would normally contain. This should solve issues #1667 and #1734.
> fix overflow-x on mobile

- Cargo.lock
Updating anyhow v1.0.66 -> v1.0.69
Updating assert_cmd v2.0.7 -> v2.0.8
Updating handlebars v4.3.5 -> v4.3.6
Updating notify v5.0.0 -> v5.1.0
Updating once_cell v1.16.0 -> v1.17.0
Removing bstr v0.2.17
Removing lazy_static v1.4.0
Updating opener v0.5.0 -> v0.5.2
Updating regex v1.7.0 -> v1.7.1
Updating predicates v2.1.4 -> v2.1.5
Updating semver v1.0.14 -> v1.0.16
Updating serde v1.0.150 -> v1.0.152
Updating serde_derive v1.0.150 -> v1.0.152
Updating serde_json v1.0.89 -> v1.0.93
> Update some direct dependencies

- guide/src/format/configuration/renderers.md
- guide/src/format/theme/README.md
- src/book/init.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/mod.rs
- tests/init.rs
- tests/rendered_output.rs
This changes it so that fonts are part of the theme. This allows the user to override and customize the fonts.
The `output.html.copy-fonts` option is deprecated, and will be removed in a future release. If customizing the fonts, you should define a `theme/fonts/fonts.css` file with whatever settings you want, and include any fonts in the `theme/fonts` directory.
Note that FontAwesome is not part of the custom fonts. I will likely try to find some alternate solution (such as #1330) for loading (and customizing) that.
Closes #1967
> Make fonts part of the theme.

- src/utils/fs.rs
The log statement is empty and simply fills up the logs when you run `mdbook` with `RUST_LOG=debug`.
> Remove spammy `debug!` log from `path_to_root`

- Cargo.lock
- Cargo.toml
- src/book/init.rs
Reverts rust-lang/mdBook#2009
This was a breaking change because toml is in the public API.
> Revert "bump 'toml' dependency"

- .github/workflows/main.yml
This can help ensure that `Cargo.lock` does not get out of sync.
> Make sure CI runs with --locked

- src/theme/index.hbs
The code here leads me to believe that the intention is for the sidebar to be default visible on large screens (where `clientWidth` > 1080) and hidden otherwise.
However, as previously written, if the `localStorage.getItem` call fails (for example, if the user agent is not accepting cookies), then we fall back to `sidebar = sidebar || 'visible';` — but `sidebar` is already set to `hidden`, so the `|| 'visible'` never happens.
This results in the sidebar hiding itself on every navigation through an mdBook, meaning if you're just switching between sections trying to find something that you keep needing to re-open the sidebar.
> Default the sidebar to visible in large screens

- src/theme/css/chrome.css
I'm sorry for my mistake, this should fix #2028. 
As it turns out, any ancestor of a sticky element that has `overflow: hidden`  becomes the scrolling container for the sticky element. Changing the `overflow` value from `hidden` to `clip` should fix it, since both are basically the same in this scenario and `clip` doesn't have this behavior. 
It's important to note that `overflow: clip` is a little bit new, but the [support](https://caniuse.com/mdn-css_properties_overflow-x_clip) is really good.
Let me know if I overlooked something else.
> Change overflow-x hidden to clip

- src/book/mod.rs
While adding support for [translations to Comprehensive Rust 🦀][1], I noticed that `mdbook test` doesn’t execute preprocessors the same way as `mdbook build`.
This PR makes the two commands use the same code to find and execute preprocessors.
[1]: https://github.com/google/comprehensive-rust/pull/130
> Run preprocessors in `mdbook test`

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- guide/src/guide/installation.md
- src/cmd/watch.rs
The gitignore crate is no longer maintained and has some issues. This switches to `ignore` which should be more reliable and maintained.
I started work on a test for this, but `notify` was giving me some trouble on macOS. I might return to it later. For now, I have done some manual testing.
> Switch from gitignore to ignore

- guide/src/cli/init.md
- src/cmd/init.rs
- tests/cli/init.rs
- tests/cli/mod.rs
This PR fixes #1556 by changing/fixing the behaviour of `mdbook init --force`.
The intent of `--force` is to skip the prompts. This is not how it currently behaves:
```
$ mdbook init --force
Do you want a .gitignore to be created? (y/n)
What title would you like to give the book? 
2023-04-02 23:17:48 [INFO] (mdbook::book::init): Creating a new book with stub content
All done, no errors...
```
* Skip the .gitignore prompt when `--force` is set
* Skip the title prompt when `--force` is set
* Add docs to the guide for `--force`
* I'm new to Rust and the repo. 🦀 
* I've found it hard to add a failing test that detects the CLI prompts. I did not find an example testing interactions with the CLI in the repo. The test I've added is actually a false positive that does not fail on `master` today. …
> fix(cli): init --force skips confirmation prompts

- src/renderer/html_handlebars/hbs_renderer.rs
- tests/rendered_output.rs
I'm new to mdbook. This is my experience when I failed to configure it.
```bash
$ mdbook init --theme
$ mdbook serve
...
2023-04-28 12:47:53 [WARN] (mdbook::renderer::html_handlebars::hbs_renderer): output.html.copy_fonts is deprecated.
Set  and ensure the fonts you want are in the `theme/fonts/` directory.
...
```
After that, I added `copy_fonts=false` to the book.toml, but this warning is not resolved since it seems that an attribute name convension in book.toml is different.
So, I suggest showing this warning.
```
2023-04-28 12:39:46 [WARN] (mdbook::renderer::html_handlebars::hbs_renderer): output.html.copy_fonts is deprecated.
Set copy-fonts=false in book.toml and ensure the fonts you want are in the `theme/fonts/` directory.
```
> Fix handling of copy-fonts=true when fonts.css is overridden

- src/book/book.rs
- src/book/init.rs
- src/book/mod.rs
- src/cmd/build.rs
- src/cmd/clean.rs
- src/cmd/init.rs
- src/cmd/serve.rs
- src/cmd/test.rs
- src/cmd/watch.rs
- src/config.rs
- src/preprocess/links.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/markdown_renderer.rs
- src/utils/fs.rs
- tests/alternative_backends.rs
- tests/dummy_book/mod.rs
- tests/rendered_output.rs
This applies a few clippy fixes which seem to help clean things up in my opinion.
> Apply some clippy fixes

- Cargo.lock
This updates some indirect dependencies.
Updating block-buffer v0.10.3 -> v0.10.4
Updating bumpalo v3.11.1 -> v3.12.2
Updating bytes v1.3.0 -> v1.4.0
Updating cc v1.0.77 -> v1.0.79
Removing codespan-reporting v0.11.1
Updating core-foundation-sys v0.8.3 -> v0.8.4
Updating cpufeatures v0.2.5 -> v0.2.7
Updating crossbeam-channel v0.5.6 -> v0.5.8
Updating crossbeam-utils v0.8.14 -> v0.8.15
Removing cxx v1.0.83
Removing cxx-build v1.0.83
Removing cxxbridge-flags v1.0.83
Removing cxxbridge-macro v1.0.83
Updating either v1.8.0 -> v1.8.1
Adding errno v0.3.1
Updating fastrand v1.8.0 -> v1.9.0
Updating filetime v0.2.19 -> v0.2.21
Updating futures-channel v0.3.25 -> v0.3.28
Updating futures-core v0.3.25 -> v0.3.28
Updating futures-macro v0.3.25 -> v0.3.28
Updating futures-sink v0.3.25 -> v0.3.28 …
> Update some indirect dependencies

- Cargo.toml
This sets the minimum versions in `Cargo.toml` to match the versions in `Cargo.lock`. We don't test with minimal versions in CI, and I don't particularly want to add that at this time. This introduces a hazard where mdbook may start depending on a new feature in a semver-compatible update of a dependency. If a user runs `cargo update -p mdbook` in their project, they won't get the new version of the dependency unless we also set the minimum in `Cargo.toml`.
> Set minimum versions in Cargo.toml

- Cargo.lock
- Cargo.toml
This includes a few small markdown rendering fixes.
Changes: https://github.com/raphlinus/pulldown-cmark/releases/tag/v0.9.3
> Update pulldown-cmark to 0.9.3

- guide/book.toml
- guide/src/format/configuration/renderers.md
- guide/src/format/mdbook.md
- guide/src/format/theme/syntax-highlighting.md
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/theme/book.js
This is based on the work in #1339 by @thecodewarrior adapting the [proposal](https://github.com/rust-lang/mdBook/pull/1339#issuecomment-727292265) by @dtolnay.
This is a copy of #1761, with some small changes applied (I could not push changes to that PR).
Closes #1502
- Moved the hidelines settings from `output.html.playground` to `output.html.code`, because it has nothing to do with the rust playground, but applies to all code blocks.
```toml
[output.html.code.hidelines]
python = "~"
```
~~~
```python
~hidden()
nothidden():
~    hidden()
~hidden()
nothidden()
```
~~~
~~~
```python,hidelines=!!!
!!!hidden()
nothidden():
!!!    hidden()
!!!hidden()
nothidden()
```
~~~
---
(Since the changes (especially the examples in the mdbook) are based on your work @thecodewarrior I would like to add …
> Support hidden lines in languages other than Rust

- src/theme/book.js
- src/theme/index.hbs
Partially addresses #443
Previously when navigating between pages using the sidebar, the border of the menu bar would briefly appear before being hidden by JavaScript. This change fixes this flash by hiding the border initially and then letting JavaScript decide whether or not it should be shown.
> Avoid menu border flash during page navigation

- src/theme/book.js
- src/theme/index.hbs
Previously, sidebar scroll was set in an external script which caused a flicker as the sidebar is initially rendered without any scroll before being scrolled to the desired location.
Switching to an inline script right after the HTML tags for the sidebar seems to avoid the flicker in most cases. In addition, logic is added to avoid scrolling jumps when navigating via links within the sidebar.
Partially addresses #443
> Fix flicker when setting sidebar scroll position

- src/theme/book.js
Fixes #2117.
document.`body`.backgroundColor is always transparent (rgba(0, 0, 0, 0))
while
document.`documentElement`.backgroundColor gives the correct value.
> Fix theme-color meta tag not syncing with the theme

- Cargo.lock
- Cargo.toml
clap 4.2.7 → 4.3.12
clap_builder 4.2.7 → 4.3.12
clap_complete 4.2.3 → 4.3.2
clap_lex 0.4.1 → 0.5.0
CHANGELOG: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#4312---2023-07-14
> Update to clap 4.3.12

- Cargo.lock
- Cargo.toml
opener 0.5.2 → 0.6.1
CHANGELOG: https://github.com/Seeker14491/opener/blob/master/CHANGELOG.md#061---2023-04-14
> Update opener to 0.6.1

- Cargo.lock
- Cargo.toml
notify 5.1.0 → 6.0.1
CHANGELOG: https://github.com/notify-rs/notify/blob/main/CHANGELOG.md#notify-601-2023-06-16
> Update notify to 6.0.1

- Cargo.lock
- Cargo.toml
predicates 2.1.5 → 3.0.3
CHANGELOG: https://github.com/assert-rs/predicates-rs/blob/master/CHANGELOG.md#303---2023-04-13
> Update predicates to 3.0.3

- guide/src/format/markdown.md
This link wasn't working on case-sensitive filesystems.
Fixes #2136
> Fix link on case-sensitive filesystems.

- .github/workflows/main.yml
This sets up the workflows to support GitHub merge queues. The primary motivation is to ensure that tests are done against the latest HEAD, which is an issue here because unfortunately PRs tend to be a little old. This will require followup from the infrastructure team to complete.
> Prepare CI workflows to support merge queues.

- .github/workflows/main.yml
This switches the success/fail merge queue check to use a better check. This requires only a single job, should work better, and also supports skipped jobs. This was copied from https://github.com/orgs/community/discussions/46757#discussioncomment-5831752.
> Use a better merge-queue success check.

- src/cmd/watch.rs
Fix paths specified in `extra-watch-dirs` being relative to the current working directory rather than the book root.
Fixes #2113.
> Fix issues with extra-watch-dirs

- src/theme/css/general.css
- src/theme/css/variables.css
This PR resolves issue #2132 by implementing `color-scheme: light | dark;` in CSS to improve the graphical interface of supported browsers based on the selected theme.
> Enhancing themes with `color-scheme: light | dark;` implementation in CSS

- Cargo.lock
- Cargo.toml
- src/book/init.rs
This reverts the update to toml in https://github.com/rust-lang/mdBook/pull/2125. I forgot again that it is exposed in the public API.
> Revert toml update

- Cargo.toml
macOS has been having some issues with triggering repeated builds whenever a file is modified if there are any "extra" files in the source tree. This is an attempt at a solution by using a different change-notification backend on macOS. There is more detail at https://github.com/rust-lang/mdBook/issues/2133#issuecomment-1662533364 and https://github.com/notify-rs/notify/issues/465#issuecomment-1657261035 about why this is happening and different options. There is some risk with this change because I don't know what considerations there might be with the kqueue backend, what kind of compatibility there will be, or if there will be problems with different environments. I'm going to go ahead and move forward with this and see if anyone reports any problems. If there are, then I think …
> Switch macOS notify to kqueue.

- src/theme/css/print.css
Fixes #1933
`#666666` is too dark when printing. `#f6f7f6` is already used to highlight code outside headers, making it a good choice for headers as well: https://github.com/rust-lang/mdBook/blob/ab2cb71c00b1556f83f69c494f176019b8863c20/src/theme/highlight.css#L62
The background in question is also used by mdbook-pdf, where is generates black text on dark gray background. That text can become completely unreadable in some PDF readers when they adjust colors for more comfortable reading experience. https://github.com/HollowMan6/mdbook-pdf/issues/26
It's a simple change, let's make it as better fixes are discussed and developed.
> Don't use distinct background for code in headers when printing

- Cargo.toml
- src/utils/fs.rs
This adds a new workaround for the macOS notify problem where mdbook is receiving repeated change notifications for changes to extra files (see https://github.com/rust-lang/mdBook/issues/2133). The solution is to not use `fclonefileat`, and just manually copy the file. This unfortunately will use more disk space, and probably be a little slower (though it should not be significant). 
An alternate solution would be to do content hashing, and dedupe watcher events where the content doesn't change. However, that seems sufficiently complicated that it doesn't seem particularly worth the effort.
This reverts https://github.com/rust-lang/mdBook/pull/2152 because it fails with "Too many open files" on books with lots of files.
Fixes #2155
Fixes #2133 (again)
> Add workaround for macOS notify problem.

- guide/src/format/mdbook.md
- src/theme/css/general.css
- src/theme/css/variables.css
This is designed to be compatible with rustdoc's version, in https://github.com/rust-lang/rust/pull/106561
> Add `.warning` class for doc author use

- src/theme/css/chrome.css
The `.hljs` class added by highlight.js adds a `display: block` rule which makes `padding` apply correctly (left padding on all lines, not just the first one).
This change ensures that said rule is applied even if highlight.js doesn't run for whatever reason.
Comparison ([source](https://gbdev.io/pandocs/Audio_Registers.html#ff12--nr12-channel-1-volume--envelope)):
> Fix code blocks "indent" without highlight.js

- src/theme/css/chrome.css
- src/theme/css/variables.css
- src/theme/index.hbs
It fixes #2186.
Indicator has the same color as icons, which is theme-dependent. On devices with limited accuracy ( tablets and smartphones most of the time) indicator is hidden.
> Add resize indicator to the sidebar

- Cargo.lock
- Cargo.toml
- src/cmd/watch.rs
Currently the `paths` input of `filter_ignored_files` is absolute while `.matched_path_or_any_parents(path, path.is_dir())` has an assertion which requires path can not have root. This will break down the `mdbook serve`(#2228).
I have tested this issue locally with different path scope and this change ensures we convert the input path into a relative path so that won't break down `mdbook serve`.
https://github.com/rust-lang/mdBook/blob/94e0a44e152d8d7c62620e83e0632160977b1dd5/src/cmd/watch.rs#L89-L99
> Fix `mdbook serve` unexpected panic

- src/renderer/html_handlebars/hbs_renderer.rs
This was causing an unnecessary warning if `&src_dir` was the same as `ctx.root`.
Also, this code had a `TODO` to "remove some time after the 0.1.8 release".
> Remove warning check for theme directory as ./src/theme

- Cargo.lock
- Cargo.toml
- src/renderer/html_handlebars/helpers/navigation.rs
- src/renderer/html_handlebars/helpers/theme.rs
- src/renderer/html_handlebars/helpers/toc.rs
Handlebars-rust author here. This patch updates it to latest 5.0 release.
> feat: upgrade handlebars to 5.0

- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/navigation.rs
On rust reference book this reduces total allocs from 490mb to 215mb,
from
```
==23272== Total:     490,538,699 bytes in 1,760,117 blocks
==23272== At t-gmax: 13,872,954 bytes in 4,655 blocks
==23272== At t-end:  488,516 bytes in 884 blocks
==23272== Reads:     830,509,060 bytes
==23272== Writes:    522,290,614 bytes
```
to
```
==57763== Total:     215,292,393 bytes in 1,161,048 blocks
==57763== At t-gmax: 13,872,954 bytes in 4,655 blocks
==57763== At t-end:  1,210,783 bytes in 1,274 blocks
==57763== Reads:     598,542,892 bytes
==57763== Writes:    229,841,910 bytes
```
when mdbook build with `--no-default-features`
> removes few more allocs

- guide/src/for_developers/backends.md
The closing bracket for the `if` statement is also newly added but the leading `+` to indicate that was forgotten.
> docs: Add missing `+` in diff code block

- guide/src/format/summary.md
This formatting mistake was made in the kanidm book ([pr fix](https://github.com/kanidm/kanidm/pull/2463)), it may be common because markdown authors typically use the h1 header only for the title of the document.
> summary.md: clarify that part titles must be h1 headers

- guide/src/format/markdown.md
The location in pulldown-cmark's repository was changed a couple of days ago in [this commit](https://github.com/raphlinus/pulldown-cmark/commit/a917492af3b82e8283a3ec37b4f438259c7cc5a2#diff-d93f0540e6c0db8d5623c385b2d2c19898746f77b83aca1c49b0251cdf4815be)
> docs: Fix broken link

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- guide/src/guide/installation.md
This updates env_logger from 0.10.1 to 0.11.1
Changelog: https://github.com/rust-cli/env_logger/blob/main/CHANGELOG.md#0111---2024-01-27
This also updates the msrv to 1.71
> Update env_logger to 0.11

- guide/src/format/theme/index-hbs.md
The theme documentation for next and previous used name instead of title.
Per the code (and using it) `title` is the correct value.
https://github.com/rust-lang/mdBook/blob/5a4ac03c0de866c4cf30d41dd0c7ea02d8429a7a/src/renderer/html_handlebars/helpers/navigation.rs#L209
> Fix incorrect theme documentation: Next/Previous should use `title`

- src/book/book.rs
- src/book/mod.rs
- src/book/summary.rs
- src/cmd/test.rs
- src/config.rs
- src/theme/mod.rs
- src/utils/fs.rs
Recent nightlies have started warning about redundant imports. This removes those unnecessary imports.
> Fix redundant imports.

- guide/src/format/configuration/renderers.md
- guide/src/format/markdown.md
- src/book/mod.rs
- src/config.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/utils/mod.rs
This renames the `output.html.curly-quotes` option to `output.html.smart-punctuation` to better reflect what it does.
The old option `curly-quotes` is kept for compatibility, but may be removed in the future.
Closes #1936
> Rename curly-quotes to smart-punctuation.

- test_book/src/SUMMARY.md
- test_book/src/individual/mathjax.md
> Added missing tests for MathJax to the test book

- src/book/book.rs
This separation was introduced in #1506. This helps document what the difference is.
> Clarify Chapter path and source_path.

- src/utils/fs.rs
Above mentioned function copies files (recursively) from a source to a destination directory. For that, file/directory paths have to be created repeatedly. This allocates as directory and file names are concatenated into an owning path structure.
The number of allocations can be reduced by creating file/directory paths only once and borrowing them instead of cloning/recreating them.
In bigger projects, this reduces execution time noticeably. Please note that file system operations are dominant from performance POV.
> Reduce allocations in `fs::copy_files_except_ext`

- src/book/mod.rs
Currently, the output from `rustdoc --test` is not colored because `rustdoc`'s stdout is not a tty. The output of a failed `rustdoc` run is sent to `mdbook`'s stderr via the `error!()` macro. This commit checks if stderr is a tty using the standard `.is_terminal()` and if so, passes `--color always` to `rustdoc`.
The test output from `rustdoc` includes the full path that `rustdoc` was called with. This obfuscates the file with the error. E.g.,
```
---- /var/folders/9v/90bm7kb10fx3_bprxltb3t1r0000gn/T/mdbook-tnGJxp/lab0/index.md - Lab_0__Getting_Started (line 3) stdout ----
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `code`
--> /var/folders/9v/90bm7kb10fx3_bprxltb3t1r0000gn/T/mdbook-tnGJxp/lab0/index.md:4:6
|
3 | this code has a bug
|      ^^^^ expected …
```
> Color test output and shorten chapter paths

- guide/src/format/configuration/preprocessors.md
Reverts rust-lang/mdBook#2373
This is intended due to https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html#provide-your-own-command.
> Revert "Maybe a typo in preprocessors.md"

- src/theme/css/chrome.css
- src/theme/css/general.css
Currently, the CSS stylesheets that are already imported from the parent HTML are also imported from the CSS stylesheets. As far as I can tell, it doesn't cause any major bugs, but it's just messy and causes minor issues (for example, Firefox doesn't fire extra requests to fetch CSS twice, but it loads it twice which makes navigating developer menu harder).
From my not-very-extensive testing, it should also allows us to remove this script: https://github.com/rust-lang/mdBook/blob/b7f46213c7df8f499eca0c82e7b41804cc15e369/src/theme/index.hbs#L80-L91
> fix: remove double imports of css

- src/renderer/html_handlebars/hbs_renderer.rs
I don't know why this `cfg_attr` is here, as I do not think it is needed for anything. Nightly now warns against these unknown configs, so remove it.
> Remove cargo-clippy unknown feature

- Cargo.toml
- guide/src/cli/arg-watcher.md
- guide/src/cli/serve.md
- guide/src/cli/watch.md
- src/cmd/command_prelude.rs
- src/cmd/serve.rs
- src/cmd/watch.rs
- src/cmd/watch/native.rs
- src/cmd/watch/poller.rs
This adds a poll-based file watcher which will poll the filesystem once every second for any file changes. We have had various issues with the operating-system native change notifications on various operating systems and filesystems. This poll watcher should be more reliable, and supports more features (such as detecting addition or removal of root paths, checking additional-css/js, etc.).
This includes a `--watcher` CLI option to give the user the option to go back to the native notifications if they are having issues with the overhead of the poll-based watcher.
I'm not certain if we will continue to support both in the long term. I'm reluctant to keep the native facilities since it adds a fair bit of complexity and maintenance, and I suspect almost nobody will use it. However, I decided …
> Add a poll-based file watcher.

- src/renderer/html_handlebars/helpers/toc.rs
> Fix dividers being folded by sections

- Cargo.lock
- Cargo.toml
- src/renderer/html_handlebars/search.rs
Changelog: https://github.com/pulldown-cmark/pulldown-cmark/releases/tag/v0.11.0
Note that math is not yet supported. However, due to the new Event variant, I decided to include math script in the search index. I don't know if that is the right thing to do, but seems like something we can figure out later if we start using the math feature.
> Update pulldown-cmark to 0.11

- .github/workflows/deploy.yml
- .github/workflows/main.yml
- ci/install-rust.sh
- ci/make-release-asset.sh
This updates the PR checks to:
- Verify x86_64-unknown-linux-musl passes tests
- Verify aarch64-unknown-linux-musl can be built via cross-compilation
- Test x86_64-apple-darwin (under Rosetta2)
There were some problems with the last release due to some changes with libdbus-sys.
> CI: Test more targets.

- src/cmd/command_prelude.rs
When built with `--no-default-features`, it shows a warning because neither watch or serve are enabled.
> Fix dead_code warning for arg_watcher

- Cargo.lock
- Cargo.toml
- src/renderer/html_handlebars/search.rs
This reverts commit https://github.com/rust-lang/mdBook/commit/8884008b4d10381316288badd588227da80f5820, (https://github.com/rust-lang/mdBook/pull/2381) reversing changes made to https://github.com/rust-lang/mdBook/commit/3d6caa504f883f646eb98869eeb63e59b3fa7aa6.
The `pulldown_cmark` types are a public API, which I did not realize.
> Revert update to pulldown-cmark 0.11

- guide/src/guide/installation.md
Updating workflow is not clear for non rust users.
> added update how to

- src/theme/book.js
- src/theme/css/chrome.css
- src/theme/css/variables.css
It looks like this:
All colors are the same. I computed the `filter` values with https://isotropic.co/tool/hex-color-to-css-filter/ (very nice website).
Another change you might have noticed: I increased the size of the buttons. There are two reasons for this change:
1. The new clipboard icon rendered badly with such small dimensions.
2. Since these buttons can be used on mobile devices, making them bigger will make things better for everyone.
> Unify copy to clipboard icon with docs.rs, rustdoc and crates.io

- src/theme/highlight.css
- src/theme/tomorrow-night.css
Add syntax highlighting for `hljs-attr` and `hljs-section` CSS classes, consistent with the Ayu theme.
Fixes https://github.com/rust-lang/mdBook/issues/2447
Before:
After:
Affects syntax highlighting for the following languages: apache, ini, javascript, makefile, markdown, nginx, nix, properties, yaml.
> Enhance syntax highlighting

- src/theme/css/chrome.css
- src/theme/css/variables.css
- src/theme/index.hbs
Little PR to follow the system's light/dark theme when JS is disabled.
> Improve theme support when JS is disabled

- src/theme/book.js
Closes #2461
Check if stored theme is valid in `get_theme()` and defaults to default theme if not valid.
Validation steps:
- `cargo run -- build guide` and serve the book
- In browser devtools, run `localStorage.setItem("mdbook-theme", "foo")` to set an invalid theme `foo`
- Refresh the page, themes should work properly:
-  the default theme should load
- the theme popup functions properly
Manually tested in Google Chrome, MS Edge and Firefox (I don't have access to safari :(
Other:
- `localStorage` won't be updated (i.e. keeps the invalid value) until user manually changes the theme
> fix: themes broken when localStorage has invalid theme id stored

- src/theme/css/general.css
This changes it so that superscript (and in particular footnote tags) do not bump the line spacing of previous lines.
Before:
After:
This is a repost of #2443, thanks @loliceo, and @notriddle for the explanation.
Closes #2437
> Set line-height of superscripts to 0

- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/toc.rs
- src/theme/css/chrome.css
- src/theme/index.hbs
- src/theme/mod.rs
- src/theme/toc.html.hbs
- src/theme/toc.js.hbs
- src/utils/mod.rs
- tests/rendered_output.rs
Before this change, the Rust `unstable-book` is 88MiB. With this change, it becomes 15MiB. Other pages might not be as extreme, but it's expected to help any book like this.
This change is so drastic because, if every chapter has a link to every other chapter, the result is *O*(n<sup>2</sup>) text output.
Related to : https://rust-lang.zulipchat.com/#narrow/stream/266220-t-rustdoc/topic/Tracking.20overall.20size/near/431831262
Preview: http://notriddle.com/rustdoc-html-demo-9/on2-book/index.html
Loading filmscripts (green line is first contentful paint):
[Desktop](https://www.webpagetest.org/result/241007_AiDc0T_8W0/)
[Mobile](https://www.webpagetest.org/result/241007_BiDc7T_8T2/)
> Load the sidebar toc from a shared JS file or iframe

- src/cmd/init.rs
- tests/cli/init.rs
Closes #2485
Moves the line that adds the config to the builder outside of the if statement that checks for the git user name so that the `init` options passed prior to that check don't silently fail when the git user is not configured.
> fix `init --title` option failure when git user is not configured

- src/book/mod.rs
The 2024 edition is now stable on nightly, so the `-Z` flag is no longer necessary.
> Stabilize 2024 flag

- .github/workflows/deploy.yml
we are now 4 generations into apples aarch64 desktop/laptop hardware, so we should definitely be providing builds for aarch64 macos.
We already test aarch64 macos as part of CI checks gating every checkin: https://github.com/rust-lang/mdBook/blob/74b2c79d46df45ab9c196646f98339dd7e0c00c3/.github/workflows/main.yml#L35
> Add aarch64-apple-darwin release target

- .github/workflows/main.yml
- .gitignore
- CONTRIBUTING.md
- Cargo.toml
- tests/gui/runner.rs
- tests/gui/sidebar.goml
As discussed with @ehuss, this PR adds the basics for adding more GUI tests. Just add more `.goml` files in the `tests/gui` folder.
This is the same GUI test framework used in rustdoc and docs.rs.
If you need any explanation on how it works, or if you have any question, please don't hesitate to ask.
> Add base for GUI tests

- .github/workflows/deploy.yml
- .github/workflows/main.yml
ubuntu-20 will be removed in April. See the announcement [here](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-20-image-is-closing-down).
> ci: move ubuntu-20 jobs to ubuntu-22

- src/theme/css/chrome.css
- src/theme/css/variables.css
Fixes https://github.com/rust-lang/mdBook/issues/2528.
For the GUI test, I need to update the framework to allow to select an element inside a frame (opened https://github.com/GuillaumeGomez/browser-UI-test/issues/628 for it).
cc @notriddle
> Fix display of sidebar when JS is disabled

- .github/workflows/main.yml
- tests/gui/runner.rs
- tests/gui/sidebar-nojs.goml
> Add GUI regression test for #2529

- src/theme/book.js
This way, whatever behavior the browser might use for checkboxes will apply to the CSS class, localStorage, and the visible state.
Fixes #2520
> Prevent the real sidebar position from becoming unsynced from the JS

- guide/src/format/mdbook.md
- src/renderer/html_handlebars/hbs_renderer.rs
Requires a space following a `#` for a line to be hidden.
Closes #2526
> fix: make line hiding in Rust code blocks consistent with `rustdoc`

- src/cmd/clean.rs
This is based off of [cargo's][1] clean command. cargo is licensed under MIT or Apache-2.0.
[1]: https://github.com/rust-lang/cargo
> Display what is removed from mdbook clean.

- guide/src/format/configuration/renderers.md
- src/config.rs
- src/renderer/html_handlebars/search.rs
- tests/rendered_output.rs
This config setting provides the ability to disable search indexing on a per-chapter (or sub-path) basis.
This is structured to possibly add additional settings, such as perhaps a score multiplier or other settings.
> Add output.html.search.chapter

- src/book/mod.rs
Before, the output is rather confusing:
```
2025-02-03 10:01:14 [INFO] (mdbook::book): Testing chapter 'Chapter 1': "chapter_1.md"
2025-02-03 10:01:14 [ERROR] (mdbook::utils): Error: No such file or directory (os error 2)
```
after it looks something like:
```
2025-02-03 11:01:42 [INFO] (mdbook::book): Testing chapter 'Chapter 1': "chapter_1.md"
2025-02-03 11:01:42 [ERROR] (mdbook::utils): Error: failed to execute `rustdoc`
2025-02-03 11:01:42 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
```
Fixes #2544
> Add context when `rustdoc` command is not found

- src/theme/css/general.css
previous implementation used `:not(.footnote-definition) + .footnote-definition` and `.footnote-definition + :not(.footnote-definition)`.
the latter selector caused many problems:
- it doesn't select footnote definitions which are last children (this can be easily triggered in a blockquote)
- it changes the margin of the next sibling, rather than the footnote definition itself, which can also *shrink* margin for elements with big margins (this happens to headings)
- because it applies to the next sibling it is also quite hard to override in user styles, since it may apply to any element
this PR replaces the latter selector with `:not(:has(+ .fd))`, which fixes all of the mentioned problems.
see https://github.com/rust-lang/reference/pull/1710/commits/bc02bf95f937b2ea5675cd6eebf54f6ac989945 …
> nicer style rules for margin around footnote defs

- src/theme/book.js
This fixes the code that forwards the edition to the playground so that it sends whatever edition value to the server. The current code was looking for specific values, which didn't work for 2024, and isn't as maintainable as new editions are produced.
Fixes #2556
> Fix playground edition detection

- src/theme/searcher/searcher.js
- tests/gui/search.goml
This fixes a problem where the search was not displaying in sub-directories. The problem was that `searcher.js` only exists in one place, and was loading `searchindex.json` with a relative path. However, when loading from a subdirectory, it needs the appropriate `..` to reach the root of the book.
Fixes https://github.com/rust-lang/mdBook/issues/2585
> Fix search not showing in sub-directories

- tests/custom_preprocessors.rs
testing error message of ask_the_preprocessor_to_blow_up
Apparently the `output.status` is different on windows and the rest of the OSes. That's why we need the `cfg!(windows)`
We could replace `output.status` by `output.status.code().unwrap_or(-1)` or by `output.status.code().unwrap()` thereby making sure the error message is the same on all (currently tested) OSes.
> [test] Check content of error message

- tests/gui/runner.rs
The name of executable was taken as a filter and because of that nothing was selected by default.
Fixing #2601
> Select all the GUI tests if no filter was provided

- src/renderer/html_handlebars/search.rs
- src/theme/searcher/searcher.js
- tests/gui/move-between-pages.goml
- tests/gui/search.goml
- tests/gui/sidebar-nojs.goml
- tests/gui/sidebar.goml
Why bother having the search index in both a JSON and JS file when it always work with the JS file after all. :)
I took over https://github.com/rust-lang/mdBook/pull/2425 to implement this.
cc @notriddle
> Remove JSON search file

- src/book/summary.rs
> Avoid using the same file twice in SUMMARY.md

- .eslintrc.json
- src/theme/book.js
- src/theme/index.hbs
The first commit is pretty uncontroversial. It takes the existing behavior for auto-detecting light/dark mode and improves it so that the page automatically changes when the preferred mode changes without a refresh. This is useful on systems which have a scheduled light/dark mode change, which is a built-in option on many OSes.
The problem is that this functionality can only be accessed if the user has never selected a theme before. To allow restoring the default behavior, we now add an "Auto" theme menu option in the second commit.
Since some people customize their index.hbs we make both changes resilient to that, falling back to the old behavior if the index changes are not applied. Thankfully this is pretty simple to do. (Longer term it'd be nice to remove the need to do this, e.g. for …
> Add "Auto" theme selection which switches between default light and dark theme automatically

- src/config.rs
> warn on invalid fields in the root of book.toml

- .gitattributes
Not having these files marked as binary causes problems for older versions of git (like 1.8.3.1 on CentOS/RHEL 7).
> Mark more font files as binary

- src/front-end/searcher/searcher.js
The SVG `<text>` tag does not seem to like having HTML tags mixed in, and the `<mark>` tag seems to prevent rendering. This adds it to the exclude list so that it doesn't try to mark content inside `<text>`.
> Ignore SVG text elements in search highlighting

- .github/workflows/main.yml
The aarch64-cross-builds and gui tests were not blocking CI from passing, which I don't think was intended.
> Require all test jobs to pass

- src/front-end/searcher/searcher.js
- src/renderer/html_handlebars/search.rs
- tests/rendered_output.rs
Follow-up of https://github.com/rust-lang/mdBook/pull/2552.
`JSON.parse()` is much faster than parsing JS code for JS engines. I missed this case when I removed the original JSON file. This is also how we do in rustdoc. The bigger the search index, the more noticeable it is.
As for the second commit, it fixes this JS error:
@ehuss Just to be sure: does this PR solves your 10+ seconds issue for search load?
> Speed up search index loading

- .github/workflows/main.yml
- Cargo.toml
- examples/remove-emphasis/test.rs
- src/book/mod.rs
- src/book/summary.rs
- src/preprocess/links.rs
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/helpers/resources.rs
- tests/rendered_output.rs
This adds clippy to CI, but with a restricted set of lints.
> Add clippy in CI

- .github/workflows/main.yml
- src/renderer/html_handlebars/hbs_renderer.rs
- src/renderer/html_handlebars/mod.rs
- src/utils/fs.rs
- src/utils/mod.rs
This removes the `allow(missing_docs)` in a few places. This also adds a CI job to ensure that rustdoc is not generating any warnings.
> Clean up some missing docs

- src/utils/mod.rs
- tests/testsuite/markdown.rs
- tests/testsuite/markdown/footnotes/expected/footnotes.html
- tests/testsuite/markdown/footnotes/src/footnotes.md
Rework the footnote rendering logic to handle cases where the same footnote tag is defined multiple times in a document.
When multiple definitions of the same footnote tag are encountered:
- a warning is logged
- only the _first_ definition for the tag is used for rendering
- subsequent definitions for the tag are ignored
Fixes #2649
> Warn on and ignore duplicate footnote definitions

- src/front-end/css/chrome.css
Follow up #2209 and https://github.com/rust-lang/rust/pull/139562
Since rustdoc and the playground both use similar resizing indicators, it only makes sense that mdbook should, too.
Before:
After:
> sidebar: use the same resize grip as rustdoc and playground

- guide/src/guide/reading.md
- src/front-end/searcher/searcher.js
- src/front-end/templates/index.hbs
This PR improves the ergonomics of search by doing the following, and is best reviewed commit by commit:
- Allows for search by `/` as well as `s`.
- Fixes an uncaught exception when pressing `down` when there are no search results.
- Navigates automatically to the first search result when pressing `enter`.
- Uses `<kbd>` to render shortcut keys in the guide.
The commit messages contain more details and motivation.
Closes https://github.com/rust-lang/mdBook/issues/2379
> Improve ergonomics of search

- src/front-end/css/chrome.css
- src/front-end/css/general.css
- src/front-end/css/variables.css
- src/front-end/js/book.js
- src/front-end/searcher/searcher.js
- src/front-end/templates/index.hbs
- src/renderer/html_handlebars/hbs_renderer.rs
Make it display when the user presses `?`.
Implements #2607
> Add pop-up window showing the keyboard shortcuts

- examples/remove-emphasis/mdbook-remove-emphasis/src/main.rs
This fixes the clippy::uninlined_format_args lint which looks like it was moved to "style" in https://github.com/rust-lang/rust-clippy/pull/14160.
> Fix clippy lint for 1.88

- guide/src/format/configuration/general.md
- guide/src/format/mdbook.md
This PR adds documentation on the `edition2024` code block attribute, which is missing.
> Document the `edition2024` code block attribute

- Cargo.lock
- Cargo.toml
This removes a few indirect deps, especially system deps like `dbus` and `pkg-config`.
> Update `opener` to 0.8.1

- src/front-end/templates/index.hbs
- tests/gui/move-between-pages.goml
The reason the ACE editor was failing to load the rust syntax highlighting is because the syntax highlighting was being created *after* the editor was created. If the editor is created first, then ACE tries to load `ace/mode/rust`. Since it isn't already defined, it tried to compute the URL and load it manually. However, since the URLs now have a hash in it (via https://github.com/rust-lang/mdBook/pull/1368), it was unable to load.
The solution here is to make sure `ace/mode/rust` is defined before creating the editors. Then ACE knows that it can just load the module directly instead of trying to fetch it from the server.
Fixes https://github.com/rust-lang/mdBook/issues/2700
> Fix loading of mode-rust.js

- src/front-end/css/chrome.css
- src/front-end/css/variables.css
- src/front-end/searcher/searcher.js
- src/front-end/templates/index.hbs
- tests/gui/search.goml
This PR makes it so that the `searchindex.js` file is only loaded when the user arrives on a page with `?search=` in the URL or if the user opens the search. It means that the book size will be only the text content until the user actually needs to run a search.
cc @notriddle
> Only load searchindex when needed

- src/front-end/css/chrome.css
- src/front-end/js/book.js
- src/front-end/templates/index.hbs
- tests/gui/sidebar.goml
Fixes #2721.
For the GUI test, I need to add a new command to ensure the text is not searchable when collapsed. I opened an issue for that in browser-ui-test: https://github.com/GuillaumeGomez/browser-UI-test/issues/659.
> Hide the sidebar when collapsed to prevent browser search to find text from it

- src/front-end/searcher/searcher.js
Problem reported in
https://github.com/rust-lang/mdBook/pull/2742#discussion_r2190930557
> Work around compat break in old index.hbs templates with new searcher.js

- src/front-end/css/general.css
- src/front-end/js/book.js
This fixes several issues with how the sidebar was behaving:
- Manually resizing the sidebar was incorrectly applying transition animations to the page-wrapper causing awkward movement.
- Clicking the sidebar toggle caused the menu bar to behave differently compared to loading a page with the sidebar visible or hidden.
- page-wrapper animation wasn't working when JS was disabled.
- RTL sidebar animation was broken.
Most of these issues stem from
https://github.com/rust-lang/mdBook/pull/2454 which moved `js` and `sidebar-visible` classes from `<body>` to `<html>`, but failed to update some of the JS and CSS code that was still assuming it was on the body.
https://github.com/rust-lang/mdBook/pull/1641 previously moved `js` from `<html>` to `<body>` with the reasoning
"This will be necessary …
> Fix sidebar animation and other behavior

- Cargo.lock
- Cargo.toml
- src/cmd/serve.rs
This PR is more of a proof of concept and a question - but I figured I'd put it up since I'd already done to work to see if it can be done: I'm curious if you'd be open to a migration to axum (or perhaps something else?).
warp is problematic for Debian, since it has some outdated dependencies that we don't want to keep around just for warp; upstream is dormant (last change was about a year ago). mdbook is the only thing that actually uses warp nowadays in Debian.
(cc @plugwash)
> Replace warp with axum

- src/front-end/templates/index.hbs
- tests/testsuite/rendering.rs
This PR adds the rel="edit" attribute to the "Suggest an edit" edit link.
rel=edit lets a page indicate that the linked resource can be used to edit the page. It is defined at https://microformats.org/wiki/rel-edit. This can then be parsed by tools like the Universal Edit Button and custom bookmarklets to open the edit page corresponding with a website.
> Add rel=edit attribute to "Suggest an edit" link

- release.toml
This hasn't been used in many years.
> Remove release.toml

- Cargo.toml
- crates/mdbook-driver/src/load.rs
- crates/mdbook-html/src/html_handlebars/helpers/mod.rs
- crates/mdbook-html/src/html_handlebars/helpers/navigation.rs
- crates/mdbook-html/src/html_handlebars/helpers/resources.rs
- crates/mdbook-html/src/html_handlebars/helpers/theme.rs
- crates/mdbook-html/src/html_handlebars/helpers/toc.rs
- crates/mdbook-html/src/html_handlebars/search.rs
- crates/mdbook-html/src/html_handlebars/static_files.rs
- examples/nop-preprocessor.rs
- src/main.rs
- tests/testsuite/main.rs
This lint can help make it clearer which items are actually exposed in the public API.
> Enable unreachable_pub

- Cargo.lock
- crates/mdbook-core/src/config.rs
- crates/mdbook-core/src/utils/mod.rs
- crates/mdbook-core/src/utils/toml_ext.rs
- crates/mdbook-driver/Cargo.toml
- crates/mdbook-driver/src/builtin_renderers/mod.rs
- crates/mdbook-driver/src/mdbook.rs
- crates/mdbook-driver/src/mdbook/tests.rs
- examples/nop-preprocessor.rs
- src/cmd/serve.rs
This removes toml as a public dependency. This reduces the exposure of the public API, reduces exposure of internal implementation, and makes it easier to make semver-incompatible changes to toml.
This is accomplished through a variety of changes:
- `get` and `get_mut` are removed.
- `get_deserialized_opt` is renamed to `get`.
- Dropped the AsRef for `get_deserialized_opt` for ergonomics, since using an `&` for a String is not too much to ask, and the other generic arg needs to be specified in a fair number of situations.
- Removed deprecated `get_deserialized`.
- Dropped `TomlExt` from the public API.
- Removed `get_renderer` and `get_preprocessor` since they were trivial wrappers over `get`.
Closes https://github.com/rust-lang/mdBook/issues/2037
> Remove toml as a public dependency

- crates/mdbook-core/src/config.rs
- examples/nop-preprocessor.rs
- tests/testsuite/includes/all_includes/book.toml
As it is seems it has never been in real use.
This is a repost of https://github.com/rust-lang/mdBook/pull/2646
Closes https://github.com/rust-lang/mdBook/issues/2636
> Remove the book.multilingual field

- Cargo.toml
- crates/mdbook-core/src/book.rs
- crates/mdbook-core/src/config.rs
- crates/mdbook-driver/src/builtin_preprocessors/index.rs
- crates/mdbook-driver/src/builtin_preprocessors/links.rs
- crates/mdbook-driver/src/builtin_renderers/markdown_renderer.rs
- crates/mdbook-driver/src/load.rs
- crates/mdbook-driver/src/mdbook.rs
- crates/mdbook-driver/src/mdbook/tests.rs
- crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
- crates/mdbook-html/src/html_handlebars/search.rs
- crates/mdbook-html/src/theme/mod.rs
- crates/mdbook-preprocessor/src/lib.rs
- crates/mdbook-renderer/src/lib.rs
- crates/mdbook-summary/src/lib.rs
- examples/nop-preprocessor.rs
- tests/testsuite/renderer.rs
- tests/testsuite/search.rs
This switches all public types to use non_exhaustive to make it easier to make additions without a semver-breaking change.
> Switch all public types to non_exhaustive

- crates/mdbook-core/src/config.rs
- crates/mdbook-core/src/utils/toml_ext.rs
This removes the old legacy config that allowed certain things at the top level.
The legacy switch was added in https://github.com/rust-lang/mdBook/pull/457
Closes https://github.com/rust-lang/mdBook/issues/2653
> Remove legacy config support

- tests/testsuite/main.rs
- tests/testsuite/search.rs
- tests/testsuite/toc.rs
This adds the `read_to_string` test helper to the test prelude so that it is easier to use.
> Add read_to_string to the prelude

- crates/mdbook-core/src/config.rs
- crates/mdbook-driver/src/mdbook.rs
- crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
- guide/src/format/configuration/renderers.md
This removes the deprecated alias `curly-quotes` for `smart-punctuation`.
> Remove curly-quotes

- crates/mdbook-driver/src/mdbook.rs
This warning was added in https://github.com/rust-lang/mdBook/pull/510 in 2017. I think plenty enough time has passed for projects to update.
> Remove book.json warning

- crates/mdbook-driver/src/builtin_renderers/mod.rs
- tests/testsuite/renderer.rs
This removes the deprecated support for renderer paths that are relative to the destination. Relative renderer command paths now must always be relative to the book root.
> Remove legacy relative renderer command paths

- crates/mdbook-driver/src/builtin_preprocessors/cmd.rs
- crates/mdbook-driver/src/builtin_renderers/mod.rs
- crates/mdbook-driver/src/lib.rs
- crates/mdbook-driver/src/mdbook.rs
- crates/mdbook-driver/src/mdbook/tests.rs
- tests/testsuite/book_test.rs
- tests/testsuite/preprocessor.rs
This changes preprocessors so that:
- Relative paths in the `command` value are relative to the book root.
- The process current directory is the book root.
This makes it so that it isn't dependent on the directory where `mdbook` is executed.
Fixes https://github.com/rust-lang/mdBook/issues/1424
> Change CmdPreprocessor to use paths relative to the book root

- crates/mdbook-driver/src/builtin_preprocessors/cmd.rs
- crates/mdbook-driver/src/builtin_renderers/mod.rs
- crates/mdbook-driver/src/lib.rs
- crates/mdbook-driver/src/mdbook.rs
- crates/mdbook-driver/src/mdbook/tests.rs
- crates/mdbook-preprocessor/src/lib.rs
- examples/nop-preprocessor.rs
- guide/src/format/configuration/preprocessors.md
- tests/testsuite/preprocessor.rs
- tests/testsuite/preprocessor/missing_optional_not_fatal/book.toml
- tests/testsuite/preprocessor/missing_preprocessor/book.toml
- tests/testsuite/renderer.rs
This adds the `optional` field to the preprocessor configuration to mirror the same option for the `output` table. Missing preprocessors are now an error unless the `optional` field is set. This should help with inadvertently building a book when a missing preprocessor that you expect to be installed.
This changes `Preprocessor::supports_renderer` to return a `Result` in order to bubble up the error.
> Add `optional` field for preprocessors

- CONTRIBUTING.md
- guide/src/SUMMARY.md
- guide/src/cli/README.md
- guide/src/continuous-integration.md
- guide/src/for_developers/README.md
- guide/src/for_developers/backends.md
- guide/src/for_developers/preprocessors.md
- guide/src/format/configuration/environment-variables.md
- guide/src/format/configuration/general.md
- guide/src/format/configuration/preprocessors.md
- guide/src/format/configuration/renderers.md
- guide/src/format/markdown.md
- guide/src/format/mathjax.md
- guide/src/format/mdbook.md
- guide/src/format/theme/editor.md
- guide/src/format/theme/index-hbs.md
- guide/src/format/theme/syntax-highlighting.md
- guide/src/guide/README.md
- guide/src/guide/creating.md
- guide/src/guide/reading.md
There was a mix of different capitalization here, so I'm just going to pick the one we use most often.
> Use consistent sentence case for section headers

- crates/mdbook-core/src/config.rs
- tests/testsuite/init.rs
- tests/testsuite/renderer.rs
This changes the serialization so that `book.src` is not serialized if it is the default. This removes the somewhat pointless `src = "src"` which shows up in the default `mdbook init` output. Deserialization should still default to `"src"`.
> Don't serialize the default for `book.src`

- crates/mdbook-markdown/src/lib.rs
- tests/testsuite/markdown/footnotes/expected/footnotes.html
- tests/testsuite/markdown/footnotes/src/footnotes.md
This adds a test for multiple footnotes in a row, which was broken in a previous version of pulldown-cmark.
This also fixes a rendering issue where the footnotes had no space separating them. It does this by adding a space character when it detects multiple footnote events in a row.
Closes https://github.com/rust-lang/mdBook/issues/2687
> Test and add a fix for multiple footnotes in a row

- crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
- crates/mdbook-html/src/html_handlebars/search.rs
- crates/mdbook-html/src/lib.rs
- crates/mdbook-markdown/src/lib.rs
- crates/mdbook-markdown/src/tests.rs
- tests/testsuite/markdown.rs
This adds `MarkdownOptions` for creating the pulldown-cmark parser, and `HtmlRenderOptions` for converting markdown to HTML. These types should help make it easier to extend the rendering options while remaining semver compatible. It should also help with just general ergonomics of using these functions.
> Introduce options struct for markdown rendering

- crates/mdbook-html/front-end/templates/toc.js.hbs
- eslint.config.mjs
- package.json
This updates eslint to lint on the toc.js.hbs file. This file uses a small amount of hbs templating which eslint can't handle. This adds a hacky preprocessor which will strips out the handlebars tags so that the file can be linted.
> Lint HBS JS templates

- Cargo.lock
- Cargo.toml
- tests/testsuite/book_test.rs
This includes a few improvements to the test infrastructure. See each commit for more details.
> Various test improvements

- tests/gui/runner.rs
This adds the ability to pass options to browser-ui-test, which can help with debugging or doing things like snapshot work. It's maybe not the cleanest since it doesn't support space-separated args, but should be good enough.
> Add the ability to pass options to browser-ui-test

- tests/testsuite/book_test.rs
- tests/testsuite/preprocessor.rs
- tests/testsuite/preprocessor/extension_compatibility/book.toml
- tests/testsuite/preprocessor/extension_compatibility/src/SUMMARY.md
- tests/testsuite/preprocessor/extension_compatibility/src/chapter_1.md
- tests/testsuite/preprocessor/extension_compatibility/src/part/chapter.md
- tests/testsuite/preprocessor/extension_compatibility/src/part/sub-chapter.md
- tests/testsuite/preprocessor/extension_compatibility/src/prefix.md
- tests/testsuite/preprocessor/extension_compatibility/src/suffix.md
This adds a test to ensure that the interface for preprocessors and renderers does not change unexpectedly, particularly in a semver compatible release.
Closes https://github.com/rust-lang/mdBook/issues/1574
> Add a test for extension compatibility

- .github/workflows/deploy.yml
- ci/publish-guide.sh
This changes the publishing process so that when publishing the guide and the current version is a pre-release, it will be pushed to a directory called `/pre-release/`.
This also switches from using simpleinfra's SSH-based script to a simple push using normal git commands.
> Support publishing a pre-release version of the guide

- crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
This changes partition_source so that instead of allocating new strings,
it just returns slices into the original string. It probably doesn't
make a big difference perf-wise, but I felt more comfortable with this,
and also felt it was a little easier to understand exactly what it was
doing.
This is generally equivalent except for the possibility of not having a
newline at the end. In practice that doesn't matter because markdown
code blocks always have a newline. However, to be defensive, the caller
will check for this.
> Rewrite partition_source to return slices 

- Cargo.lock
- crates/mdbook-compare/Cargo.toml
- crates/mdbook-compare/README.md
- crates/mdbook-compare/src/main.rs
This is a very simplistic utility to compare the output of different versions of mdbook. This is useful when making changes to compare real-world books to see what changes actually happen.
This is a variation of scripts that I have been using for a few years. This could definitely use some improvements, but this seems like it could be useful as-is.
> Add a basic utility to compare different versions of mdbook

- crates/mdbook-html/src/html/tree.rs
- tests/testsuite/rendering/html_blocks/expected/script-in-block.html
- tests/testsuite/rendering/html_blocks/src/SUMMARY.md
- tests/testsuite/rendering/html_blocks/src/script-in-block.md
This fixes a small mistake where the "raw" status wasn't being reset once exiting the script or style tags. That means any text nodes that followed would be misinterpreted as being raw.
> Fix raw status ending in the HTML tokenizer

- crates/mdbook-html/src/html/print.rs
- crates/mdbook-html/src/html/tree.rs
- crates/mdbook-html/src/utils.rs
- tests/testsuite/rendering/header_links/expected/header_links.html
This fixes a collision with the ID generation where it a previous entry could generate a unique ID like "foo-1", but then a header with the text "Foo 1" would collide with it. This fixes it so that when generating the ID for "Foo 1", it will loop unit it finds an ID that doesn't collide (in this case, `foo-1-1`).
> Fix ID collisions when the numeric suffix gets used

- crates/mdbook-html/front-end/css/variables.css
These various were inadvertently missing from the no-js dark mode.
> Fix missing css vars for no-js dark mode

- crates/mdbook-core/src/config.rs
- crates/mdbook-html/front-end/css/general.css
- crates/mdbook-html/front-end/css/variables.css
- crates/mdbook-html/src/html/admonitions.rs
- crates/mdbook-html/src/html/mod.rs
- crates/mdbook-html/src/html/tree.rs
- crates/mdbook-markdown/src/lib.rs
- guide/src/format/configuration/renderers.md
- guide/src/format/markdown.md
- guide/src/format/mdbook.md
- tests/testsuite/markdown.rs
- tests/testsuite/markdown/admonitions/book.toml
- tests/testsuite/markdown/admonitions/expected/admonitions.html
- tests/testsuite/markdown/admonitions/expected_disabled/admonitions.html
- tests/testsuite/markdown/admonitions/src/SUMMARY.md
- tests/testsuite/markdown/admonitions/src/admonitions.md
This enables the admonitions support from pulldown-cmark. This includes a config option in case it causes problems with existing books.
I would like to make this extensible in the future, though I'm not sure what that would look like. There's also some concerns with how this will affect translations like mdbook-i18n-helpers, which we may need to work out in a different way.
Closes https://github.com/rust-lang/mdBook/issues/2771
> Add support for admonitions

- guide/src/format/markdown.md
I forgot to include this link in the description of definition lists.
> Add link to `output.html.definition-lists`

- crates/mdbook-core/src/utils/mod.rs
- crates/mdbook-driver/src/builtin_preprocessors/links.rs
- crates/mdbook-driver/src/builtin_preprocessors/links/take_lines.rs
These functions are only used by the links preprocessor. I'm moving these functions to put them closer to the code that they are associated with, and to reduce the public API surface.
> Move take_lines functions to mdbook-driver and make private

- .github/workflows/update-dependencies.yml
- ci/update-dependencies.sh
- triagebot.toml
This adds a job to automatically update cargo dependencies once a month. I've added this script instead of using Renovate because I couldn't get Renovate to update versions in `Cargo.toml`. I also wanted to batch transitive dependency updates all in one PR.
> Add job to automatically update dependencies

- triagebot.toml
This adds a comment on a PR when the author rebases to have a link to a better diff.
> Add triagebot range-diff feature

- .cargo/config.toml
- CONTRIBUTING.md
- Cargo.lock
- crates/xtask/Cargo.toml
- crates/xtask/README.md
- crates/xtask/src/main.rs
During development I often need to run a bunch of tests. Instead of having some unwieldy shell command, I have added this xtask to help with running the testing commands.
> Add an xtask to help with running tests
