README.md

You may want to move around where it goes I guess. I'm just thinking it might be nice to have at least this much information in there.

added installation information

---

src/renderer/html_handlebars/hbs_renderer.rs
src/theme/book.css
src/theme/book.js
src/theme/index.hbs
src/theme/mod.rs
src/theme/tomorrow-night.css

This is definitely WIP
Here is my attempt at making a dark theme. I was mainly making a dark grey theme but decided to try a dark blue theme similar to what gitbook uses to see if I liked it better. Both need more tweaking (if you're interested in both). Blue is mostly a clone of grey (I'd have to change it some more to differentiate or consolidate it I suppose). My css is bad though so me trying to consolidate doesn't always work.
Building a doc set ignores the new css file I added (not sure why but I also didn't look). I just copy it into the folder afterwards.
This would also need a button to switch themes. I have no idea how to do that.
Also, I was thinking of trying to make a Rust theme (similar to how the playpen is themed around pale browns) since this is written in Rust and if the …

The start of a dark theme

---

src/bin/mdbook.rs
src/book/mdbook.rs

Fixes #69 
Let me know if this style is off at all, since I'm not very familiar with the codebase!

Implement 'mdbook test'

---

src/theme/book.js
src/theme/index.hbs

Reverts azerupi/mdBook#85
Causing trouble with "Go Back" and "Go Forward" page navigation in Chrome

Revert "Add navigation by keyboard using alt + left/right arrows"

---

.travis.yml
Cargo.toml

I think this should do it.
r? @azerupi

travis: test/release on/for i686-apple-darwin

---

src/bin/mdbook.rs

Add address output to mdbook serve

---

ci/script.sh

closes #138 
I think this should do it

ci: test without default features

---

README.md

Enhancing the first impression people get of your great project. :smile:

Fix some minor typos and text inconsistencies

---

src/bin/mdbook.rs
src/book/bookconfig.rs
src/book/bookitem.rs
src/book/mod.rs
src/parse/summary.rs
src/renderer/html_handlebars/hbs_renderer.rs
src/renderer/html_handlebars/helpers/playpen.rs
src/renderer/html_handlebars/helpers/toc.rs
src/utils/mod.rs

https://github.com/Manishearth/rust-clippy

Address warnings found by rust-clippy.

---

.travis.yml

I don't if this will work or not, since CI has a lot going on; let's see.

Try to fix Travis

---

src/theme/book.js

Fix keyboard navigation to trigger only if no modifier key is pressed

---

src/book/mod.rs

I accidentally introduced this in https://github.com/azerupi/mdBook/pull/254/commits/4525810737b678e00c23f26c218db5426df0d714.

Fix incorrect conditional.

---

.travis.yml

This should work now.
Fixes #158

Remove allow-failure on MUSL

---

CONTRIBUTING.md
README.md

This adds a "how to contribute" guide per #270 
Let me know if you would change or add anything :)

Contributing file

---

build.rs
rustfmt.toml
src/bin/mdbook.rs
src/book/bookconfig.rs
src/book/bookitem.rs
src/book/mod.rs
src/lib.rs
src/parse/summary.rs
src/renderer/html_handlebars/hbs_renderer.rs
src/renderer/html_handlebars/helpers/navigation.rs
src/renderer/html_handlebars/helpers/playpen.rs
src/renderer/html_handlebars/helpers/toc.rs
src/theme/mod.rs
src/utils/fs.rs

Updated the project rustfmt.toml to include `use_try_shorthand = true`.
Run rustfmt on all rust sources.
Resolves: https://github.com/azerupi/mdBook/issues/286

Made changes with rustfmt including `use_try_shorthand`

---

src/theme/book.js

fixes https://github.com/azerupi/mdBook/issues/323
might not be the prettiest solution but it gets the job done.

copying to clipboard no longer copies the compilation results from "play"

---

src/theme/book.css
src/theme/book.js
src/theme/stylus/theme-popup.styl

fixes https://github.com/azerupi/mdBook/issues/330

Hide theme selection popup after interaction

---

src/renderer/html_handlebars/hbs_renderer.rs
src/theme/index.hbs

Fix the print title that was using the title from the last rendered chapter

---

book-example/src/format/mathjax.md

Correct inline mathematics delimiters

---

src/renderer/html_handlebars/hbs_renderer.rs
src/theme/book.css
src/theme/book.js
src/theme/index.hbs
src/theme/stylus/themes/base.styl

Fix the issue with pages named print not at the root

---

src/theme/book.css
src/theme/stylus/general.styl

Fix issue https://github.com/azerupi/mdBook/issues/341

Fix code snippet font size a little smaller in FF

---

src/theme/book.js
src/theme/index.hbs

Fixes https://github.com/azerupi/mdBook/issues/448
Is this the path we want to take? It sucks to choose a different key, but it's an easy fix, and not *that* bad.
What about the `sidebar` key?

Change key for theme to not clobber old books

---

book-example/src/misc/contributors.md

Added myself to the contributors list in the example book.

Updated Contributors

---

src/lib.rs
src/renderer/html_handlebars/hbs_renderer.rs

Discussion in #466. Fixes #399.

Fix last clippy warnings

---

.travis.yml

Fixed the OSX/beta travis builds

---

src/book/mod.rs

Added a warning if people use the book.json config file

---

src/renderer/html_handlebars/hbs_renderer.rs

Added better error messages for missing CSS/JS

---

src/theme/book.js

Implements #274. Not 100% certain about the thresholds or details of the behavior, but it seems intuitive enough to me. Suggestions are appreciated, however.
~~Recommended merging #470 (or similar) first. Otherwise, swiping will also scroll the page on smaller screens due to overflowing content.~~

Basic swipe gesture functionality for opening/closing sidebar

---

src/theme/book.css
src/theme/index.hbs
src/theme/stylus/menu.styl
src/theme/stylus/themes/base.styl

* **hbs**: Use `button[type=button]` for menu icons
* **styl**: Introduce `.icon-button` class to deal with browser default styling for `<button>`
* Move `title` attribute to interactive elements (`button`, `a`)
* Make important controls focusable via keyboard
* Ensure `title` attribute values show up on hover

Use <button> for menu bar

---

ci/github_pages.sh

https://internals.rust-lang.org/t/rustdoc-ice-in-ci-build/6480/2

Added dummy `df` statements to debug the travis failures

---

ci/github_pages.sh

Reverts rust-lang-nursery/mdBook#526

Revert "Added dummy `df` statements to debug the travis failures"

---

ci/github_pages.sh

large writes to stdout error with errno 11 (resource unavailable).

Workaround for travis-ci/travis-ci#4704

---

tests/rendered_output.rs

Quick fix as reported in test warning.

Remove unneeded mut modifier in test

---

src/theme/book.js

fix(theme/book): Disable stylesheets by property, not attribute

---

src/bin/clean.rs
src/bin/mdbook.rs

Hi,
Was working on adding `clean`'.
However, don't know how to correctly return Err in case of error.

add `clean` subcommand

---

src/theme/book.css
src/theme/book.js
src/theme/stylus/menu.styl

Common pattern, especially on mobile devices where the page can be quite long.

Scroll to top when clicking the page title

---

src/theme/book.css
src/theme/stylus/sidebar.styl

[WIP] Reduce sidebar padding on non-touch devices

---

src/theme/book.js
src/theme/index.hbs

Follows the [menu ARIA guideline](https://www.w3.org/TR/wai-aria-practices-1.1/#menu).

Accessibility improvements

---

README.md
book-example/src/SUMMARY.md
book-example/src/cli/build.md
book-example/src/cli/clean.md
book-example/src/cli/serve.md
book-example/src/cli/watch.md

@Michael-F-Bryan, I updated README.md and User Guide to reflect addition of `clean`
subcommand. Do minor spelling fixes too.

Update documentation to reflect addition of `clean` subcommand.

---

src/bin/mdbook.rs

Really simple fix for #617 as was described in the issue. A few formatting changes sorry, let me know if rustfmt wasn't meant to do this...

Changing clap settings

---

src/theme/book.js

fix(theme/book): Workaround focusout bug in macOS and iOS

---

Cargo.lock
Cargo.toml
README.md
src/lib.rs
src/renderer/html_handlebars/helpers/navigation.rs
src/renderer/html_handlebars/helpers/toc.rs

Bumping dependencies and getting ready for the next release.

Pre release

---

src/theme/searcher/searcher.js

Fix search

---

src/theme/index.hbs
src/theme/searcher/searcher.js

This enables "Add a keyword for this search" in the contex menu for the
search field, in Firefox and other browsers.

Put the search bar into an HTML form

---

rustfmt.toml

remove removed rustfmt options

---

book-example/src/continuous-integration.md

OAuth token type doesn't work. Have to change it to PAT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rust-lang-nursery/mdbook/728)

- Fixed token type.

---

src/theme/book.js

pending merge of rust-lang/rust#51803

rustdoc codeblock hash escape

---

src/theme/playpen_editor/editor.js
src/theme/stylus/general.styl

Fix different font sizes in editor and code

---

src/theme/book.js

cc https://github.com/rust-lang/rust/issues/52871

Fix rust playground execute API

---

src/cmd/test.rs

Add directory argument to `mdbook test`

---

Cargo.lock
Cargo.toml
src/renderer/html_handlebars/helpers/navigation.rs
src/renderer/html_handlebars/helpers/toc.rs

Update to handlebars 1.0

---

book-example/src/cli/build.md
book-example/src/cli/clean.md
book-example/src/cli/serve.md
book-example/src/cli/test.md
book-example/src/cli/watch.md
src/cmd/build.rs
src/cmd/clean.rs
src/cmd/serve.rs
src/cmd/test.rs
src/cmd/watch.rs

CC #780. Even if we release 0.3 soon and 'fix' this, we should have a release on the 0.2 branch which documents this behavior.

Document dest-dir relative path behavior

---

examples/de-emphasize.rs
examples/nop-preprocessor.rs
src/book/book.rs
src/book/init.rs
src/book/mod.rs
src/book/summary.rs
src/cmd/init.rs
src/cmd/serve.rs
src/config.rs
src/main.rs
src/preprocess/cmd.rs
src/preprocess/index.rs
src/preprocess/links.rs
src/preprocess/mod.rs
src/renderer/html_handlebars/hbs_renderer.rs
src/renderer/html_handlebars/helpers/mod.rs
src/renderer/html_handlebars/helpers/navigation.rs
src/renderer/html_handlebars/search.rs
src/renderer/mod.rs
src/utils/mod.rs
tests/alternate_backends.rs
tests/custom_preprocessors.rs

Since the CONTRIBUTING.md file suggests running rustfmt and clippy before submitting a pull request this pull request does only that. Since the start state for this pull request changed when running rustfmt and there were some easy to fix clippy warnings. I'm very new to rust so I didn't feel comfortable fixing all clippy warnings.
Question: When I run `cargo test` one test fails on windows but `cargo test`  succeed on the windows subsystem for linux:
```sh
test failing_alternate_backend ... FAILED
test passing_alternate_backend ... ok
test missing_backends_arent_fatal ... ok
test alternate_backend_with_arguments ... ok
failures:
---- failing_alternate_backend stdout ----
thread 'failing_alternate_backend' panicked at 'called `Result::unwrap_err()` on an `Ok` value: ()', …
```

Random acts of kindness

---

book-example/src/cli/serve.md

Correct grammar: remove the redundancy

---

Cargo.toml
src/main.rs

If there is an overlap, I think that it will happen that the number of changes will increase, or forget to change either.

Fix duplication with Cargo.toml

---

src/cmd/serve.rs
src/cmd/watch.rs

Closes #679.
Any and all feedback is appreciated.

Group file changes and rebuild book only once

---

src/theme/playpen_editor/editor.js

Comment in editor.js referenced file called "general.styl", changed that
to "general.css".

Update comment in editor.js

---

src/book/init.rs
src/renderer/html_handlebars/hbs_renderer.rs
src/theme/book.js
src/theme/css/book.css
src/theme/index.hbs
src/theme/mod.rs

The idea is to add a theme that mimics traditional typesetting for books.
Preview:
[Rust Reference](https://rynx.org/sebk/rust-reference)
[Rust Book](https://rynx.org/sebk/rust-book)

new "Book" theme

---

examples/nop-preprocessor.rs
src/book/book.rs
src/book/mod.rs
src/cmd/test.rs
src/config.rs
src/preprocess/index.rs
src/preprocess/links.rs
src/renderer/html_handlebars/hbs_renderer.rs
src/renderer/html_handlebars/helpers/theme.rs
src/renderer/html_handlebars/helpers/toc.rs
src/renderer/html_handlebars/search.rs
src/utils/fs.rs
src/utils/mod.rs
tests/rendered_output.rs

NOTE: Please _squash_ these commits before merging.

Fix most of clippy warnings

---

src/book/book.rs
src/book/mod.rs
src/book/summary.rs
src/lib.rs
src/preprocess/links.rs
src/renderer/html_handlebars/hbs_renderer.rs
src/renderer/html_handlebars/helpers/navigation.rs
src/renderer/html_handlebars/helpers/theme.rs
src/utils/mod.rs

Deny 2018 edition idioms globally

---

src/theme/index.hbs
tests/rendered_output.rs

I hope the tests are correct as they are.
Fixes #772

Don't let robots index the print.html

---

appveyor.yml

Not sure, seems to work on my fork.

Fix appveyor github token.

---

book-example/src/for_developers/backends.md

Implemented the proposed change in wording.

Fix issue #703.

---

book-example/src/for_developers/backends.md
book-example/src/format/config.md
book-example/src/format/theme/index-hbs.md
src/config.rs

Some documentation fixes.

---

src/theme/book.js

The endpoint was recently updated to support the edition param.

Support rust edition in playground.

---

src/book/mod.rs
src/renderer/html_handlebars/helpers/navigation.rs
src/theme/mod.rs
src/theme/playpen_editor/mod.rs
src/theme/searcher/mod.rs
tests/init.rs

Remove 'static lifetime from static vars

---

.travis.yml

Fix broken cache by updating sccache version

---

Cargo.lock
Cargo.toml
src/renderer/html_handlebars/helpers/navigation.rs
src/renderer/html_handlebars/helpers/theme.rs
src/renderer/html_handlebars/helpers/toc.rs

This patch update handlebars to 2.0 and its helper API usage.

(feat) update handlebars to 2.0

---

.travis.yml

Workaround for  #995
cc @ehuss

build(CI): Temporary disable sccache

---

src/utils/mod.rs

A minor change in the recent stable release.

Rustfmt for 1.38.

---

src/theme/css/general.css

If accepted, this will fix #1061

Add `!important` to `code {font-family}` property

---

README.md

Hi!
I've noticed that salsa's CI compiles a bunch of seemingly unnecessary crates, like mio. Looks like they are coming from `cargo install mdbook` step. I guess for CI it makes sense to just recommend to disable watching and serving?

Add --features to CI recipe

---

src/theme/book.js

`sidebar`  after times becomes to string "visible" or "hidden" value.   
and query selector for `sidebarScrollBox` is not `Id` , it's `class`.  
i changed to them to correct value

fix scroll issue

---

src/theme/index.hbs

Support rel=next and rel=previous

---

src/utils/fs.rs

This reverts commit d7a2b29f065fbb10007649aabcc4ddf66b7ca2ff.
Some projects relied on this behavior.  Closes #1180, will merge #1026 instead.

Revert "Assure copy_files_except_ext(..) won't copy directories into itself (#1135)"

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Starting some backwards-incompatible changes.

Start 0.4.0 release.

---

src/theme/searcher/searcher.js

Addresses #1020 with the suggestion from prior PR #1101

fix: don't jump away from form input to search bar

---

src/renderer/html_handlebars/hbs_renderer.rs
src/utils/string.rs
src/utils/toml_ext.rs

clippy: use char instead of str

---

src/book/book.rs

Clippy lint: Remove unnecessary clone

---

guide/src/format/theme/README.md

book.css was replaced in #743, but the docs were never updated.
Closes #1429

Update theme CSS docs.

---

guide/src/format/mdbook.md

docs: Use inline code for regex

---

guide/src/continuous-integration.md

https://github.com/rust-lang/mdBook/issues/1495

Change in gitlab CI

---

guide/src/for_developers/preprocessors.md

Minor grammatical fix and rewording of a sentence in the guide.

Reword incomplete sentence in Preprocessors section in the guide

---

src/theme/index.hbs

I discovered this issue while working on https://github.com/rust-lang/rust/pull/84480.

Remove duplicate "name" attribute on input

---

guide/src/format/summary.md

this shows a richer structure of numbered chapters to better illustrate that it uses nested markdown lists.

more detailed example in summary.md

---

guide/src/format/summary.md

a very pedantic ommitted -> omitted

Fix typo in documentation

---

guide/src/cli/test.md

Clarify the library path documentation

---

src/theme/book.js
src/theme/css/general.css

feat(playground): show "No output" on playgrounds that print nothing

---

CONTRIBUTING.md

There's probably a lot more to add here, but I just wanted to make a few small changes.

Some minor updates to contributing docs.

---

examples/nop-preprocessor.rs

Hi, I was looking into building my own preprocessor and copied the example from the repo. When I ran Clippy, there were 2 changes suggested, which I assume should be changed in the example.

Fix preprocessor example

---

src/theme/book.js

Only switch to themes on buttons that have the `theme` class

---

src/theme/book.js

fix for https://github.com/rust-lang/mdBook/issues/1949

#1949 update for hidden only on clipboard

---

Cargo.lock
Cargo.toml
src/book/init.rs

bumps the 'toml' dependency to the latest version

bump 'toml' dependency

---

.github/workflows/main.yml
guide/src/format/theme/README.md
src/config.rs
src/theme/book.js
src/theme/tomorrow-night.css
test_book/src/individual/image.md
test_book/src/individual/mixed.md

This PR convert some links for `http` to `https` protocol.

Convert links from http to https protocol

---

test_book/src/languages/highlight.md

Update test_book highlight.md

---

guide/src/cli/completions.md

I have trouble to find this information, doesn't cost must to add it here.

Add oh-my-zsh quick exemple to shell completions

---

Cargo.lock
Cargo.toml
src/book/init.rs

toml 0.5.11 → 0.7.6
CHANGELOG: https://github.com/toml-rs/toml/blob/main/crates/toml/CHANGELOG.md#076---2023-07-05

Update toml to 0.7.6

---

src/theme/index.hbs

Add prefetch to next link

---

Cargo.lock
Cargo.toml
src/cmd/watch.rs

upgrade to notify 6.1.1 and watcher-mini 4.1

---

Cargo.lock
Cargo.toml

Dep: fix Tungstenite DoS (RUSTSEC-2023-0065)

---

tests/alternative_backends.rs

This updates the test `backends_receive_render_context_via_stdin` to avoid printing JSON to stdout, and to also work on all platforms.

Clean up test backends_receive_render_context_via_stdin

---

src/theme/searcher/searcher.js

Ready to merge see https://github.com/rust-lang/mdBook/issues/1204#issuecomment-1929162727.
Closes #1204

fix input `s` into a form without triggering search

---

guide/src/format/configuration/preprocessors.md

It seems to me there is a small typo in the file preprocessors.md

Maybe a typo in preprocessors.md

---

src/book/mod.rs
src/book/summary.rs
src/cmd/watch.rs
src/config.rs
src/renderer/html_handlebars/helpers/toc.rs

These are a few fixes that add some minor cleanup.

Apply a few minor clippy fixes

---

src/theme/book.js
src/theme/index.hbs
src/theme/toc.js.hbs
tests/rendered_output.rs

Fixes #2472
https://github.com/user-attachments/assets/b127ecfc-5f08-460b-ad7e-bc4bfc8af427

Fix inadvertently broken folding behavior

---

src/theme/toc.js.hbs

Ignore fragment when figuring out sidebar items

---

src/book/summary.rs

in suffix_items_cannot_be_followed_by_a_list

check content of the error message

---

tests/alternative_backends.rs

Check content of the error message.

---

triagebot.toml

This adds some more features (merge conflicts, review auto-labels) that I tend to use in other repositories.

Add more triagebot features

---

examples/nop-preprocessor.rs
src/config.rs
tests/init.rs

As it is seems it has never been in real use.
Closes #2636

Remove the book.multilingual field

---

src/front-end/searcher/searcher.js

Missed this in https://github.com/rust-lang/mdBook/pull/2668

Fix wrong quotes for eslint

---

src/renderer/html_handlebars/helpers/toc.rs

https://rust-lang.github.io/rust-clippy/master/index.html#needless_late_init

[refactor] eliminate needless_late_init

---

src/front-end/css/variables.css
src/front-end/js/book.js

fix(css): sidebar can no longer be larger than 80% of viewport width

---

tests/gui/help.goml

Somehow I missed including this file in https://github.com/rust-lang/mdBook/pull/2608.

Add help gui test

---

test_book/src/individual/code.md

New contributor here! I started by fixing a small typo.

Fix typo 'isn't is?' -> 'isn't it?' in test_book/src/individual/code.md

---

package.json

Needs https://github.com/rust-lang/mdBook/pull/2735 to be merged first.

Update browser-ui-test version to `0.21.0`

---

src/renderer/html_handlebars/search.rs

Some unit-tests for the tokinze() function.

add tests to the tokenize() function

---

tests/testsuite/book_test.rs

This adds a basic debug method to the testsuite command to help with diagnosing tests that aren't working as expected.

Add debug option to the testsuite

---

.github/renovate.json5

This adds a configuration to enable Renovate to do some basic automated updates.

Add Renovate configuration

---

CHANGELOG.md

This adds a migration guide for the breaking change in 0.5. This also includes the changelog entries for 0.5-alpha.1.

Add 0.5 migration guide
